project_id = "fucvkmsaappphsvuabos"

[functions.extract-dcli-invoice]
verify_jwt = false

[functions.extract-ccm-invoice]
verify_jwt = false

[functions.extract-flexivan-invoice]
verify_jwt = false

[functions.extract-trac-invoice]
verify_jwt = false

[functions.extract-wccp-invoice]
verify_jwt = false

[functions.extract-scspa-invoice]
verify_jwt = false

[functions.extract_invoice_data]
verify_jwt = false

[functions.build-embeddings]
verify_jwt = false

[functions.chat-vendors]
verify_jwt = false