('Cargoways Transportation LLC','012596','NMRT','Drayage','07/08/2020',NULL,'Houston','TX','Carrier','250,000','12/04/2020','6,000,000','07/08/2020','1,000,000','02/21/2021'),
('Caribe Xpress LLC','1147891','CBXY','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Carlos O Duchimaza Encalada','0476728','2318','Intermodal',NULL,'Flat Bed Trailer (FT); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Carolina Transportation Inc','574276','CARO','LTL, TL','09/30/2020',NULL,'Candler','WA','Carrier','300,000','09/30/2020','1,000,000','09/30/2020','1,000,000','09/30/2020'),
('Carolines Transport Services, Inc','720845','2566','LTL',NULL,'(SV); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Carpa Transport Inc','777058','CTIP','Drayage',NULL,'Chassis (CH); TRACTOR (G4)','Carson','CA','Carrier',NULL,NULL,NULL,NULL,NULL,NULL),
('Carpathian Way Inc','085866','CWYO','LTL',NULL,'Cargo Van (CV); Flat Bed Trailer (FT); Controlled Temperature Trailer (Reefer) (RT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Carrier Incorporated','983008','CICS','Drayage',NULL,'TRACTOR (G4);  (SV); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Carrington Transport LLC','949290','CRPP','Drayage',NULL,NULL,'North Hollywood','CA','Carrier','250,000','11/06/2020',NULL,NULL,NULL,NULL),
('Carry Logistics LLC','1687735','CYLM','Drayage, Intermodal, LTL, Rail',NULL,'Chassis (CH);  (SV); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Carry On Trucking, Inc.','503465','CCBJ','Cartage',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Carrycargo Logistics LLC','1368240','CYGR','Drayage, Intermodal, LTL, Truckload',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Carvago LLC','1682432','3145','Drayage, Intermodal, LTL, Rail',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Castle Bro''s Trucking Inc','1429002','2314','Drayage',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Castro Freight Express','1197123','2440','Drayage',NULL,'Container (CN); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Cat And Sons Transportation LLC','792489','CASH','LTL, Truckload',NULL,'TRACTOR (G4); Trailer, Dry Freight (TF); Trailer (not otherwise specified) (TL)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Cazares Boy''s Transport LLC','1300672','2416','Drayage',NULL,'(SV); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Cb4 Enterprises LLC','1026500','CFCC','Drayage','05/04/2020',NULL,'Whittier','CA','Carrier','100,000','03/21/2020','1,000,000','05/04/2020','1,000,000','05/04/2020'),
('Cbj Trucking Inc','928263','CBJN','Drayage',NULL,'Chassis (CH); Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Cbn Transportation Inc','957864','CBUK','Drayage, Intermodal, Ocean, Rail',NULL,'Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Cbt Trucking','578230','CBTJ','Drayage',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Cc Torroella Corp','1334236','CCBL','Drayage, Ocean',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Cca Transport LLC','1338762','CNBE','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ccl Group LLC','1150339','CZGP','Drayage, Intermodal, LTL',NULL,'Chassis (CH); Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ccr Trucking Inc','1153826','1061','Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Cdl Express Transport LLC','1255943','CDDS','Drayage',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Cdl Transportation Inc','020118','CDLV','Drayage, Intermodal, Rail',NULL,'TRACTOR (G4); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Cec Transport Inc','761894','CEAQ','Drayage, Intermodal',NULL,'Chassis (CH); Double-Drop Trailer (DD); Single-Drop Trailer (SD)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Cecia Transportation Inc','1185196','CIHT','Intermodal',NULL,'Container (CN); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Cedric & Benzi Trucking LLC','1388872','CBQK','Drayage',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Centerstone LLC','1106634','CSOD','Drayage, Ocean',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Centrans Truck Lines LLC','190266','CNLE','Intermodal','07/31/2023','Cargo Van (CV)',NULL,NULL,NULL,'250,000','07/31/2023',NULL,NULL,NULL,NULL),
('Ces Development Inc','681774','CEVF','Intermodal, LTL, Truckload',NULL,'Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Champ''s Transport Inc','1168886','2289','Drayage',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Charleston Container Co LLC','136179','CCJJ','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Charlie Transportation Inc','1141749','2496','Cartage',NULL,'Cargo Van (CV);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Charlotte Bay Trading Company','173427','CHBY','Drayage',NULL,'Chassis (CH); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Charly Transportation LLC','1348065','1177','Drayage, Intermodal',NULL,'Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Chaser, LLC','397346','CSVH','Truckload',NULL,'Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Cheema Transportation Inc','047941','CKQV','Drayage, Ocean, Rail',NULL,'TRACTOR (G4); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Chellco Logistics LLC','1025704','CEOB','Drayage, Intermodal, LTL, Rail, Truckload',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Chicago Intermodal Inc','1245233','CIIR','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Chicago Intermodal Trucking, Inc.','355376','CGIT','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Chicali On The Run Transport LLC','1296620','CJZI','Drayage, Rail',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Chicas & Co Logistics Inc','1001883','CHCS','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Chosen Freight Logistics','1304972','CLYH','Drayage, Intermodal, Truckload',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Chozen One Transport, LLC','1245627','CZAJ','Drayage, Intermodal, Rail',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Christ Central','478797','CRCT','Truckload',NULL,'Cargo Van (CV); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Christy Transport LLC','1019404','CHRL','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Churchill Transportation, Inc.','147259','CHUH','Drayage','07/01/2021',NULL,'Detroit','MI','Carrier','500,000','07/01/2021','1,000,000','07/01/2021','1,000,000','07/01/2021'),
('Chuyon Transport LLC','1135064','2399','LTL',NULL,'Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ciprian Logistics Inc','1225092','2543','Cartage, Drayage, Intermodal, LTL',NULL,'TRACTOR (G4);  (SV); Trailer, Bulk (TB); Trailer, Dry Freight (TF); Truck, Van (TV); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Citizen Trucking','1326168','2945','Truckload',NULL,'Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Citrus Transport LLC','580527','CPCQ','Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('City To Country Logistics Corp','124182','CIKV','Drayage, Intermodal, Rail',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Cj Logistics Transportation LLC','074379','CJLQ','Drayage, Intermodal, Truckload','08/01/2026','Chassis (CH); TRACTOR (G4);  (SV); Trailer, Refrigerated (TW)',NULL,NULL,NULL,'100,000','08/01/2026',NULL,NULL,NULL,NULL),
('Cjm Express Inc','995500','3895',NULL,NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ck Bros Carrier Inc','805993','CKBR','Truckload',NULL,'(SV); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Classic Logistics LLC','1155827','2528','LTL',NULL,'LARGE STRAIGHT (G3)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Classic Transportation Services, Inc.','209918','CTSP','Drayage, Intermodal',NULL,'TRACTOR (G4); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Claude Laguerre Transport','1183974','3714','Drayage, Intermodal',NULL,'Chassis (CH); Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Clemons Trans LLC','1071947','CMJT','Air Freight, Drayage, Intermodal, LTL, Rail',NULL,'Cargo Van (CV); TRACTOR (G4); Trailer (not otherwise specified) (TL)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Clockwork Freight Solutions Ltd','1123111','CWFR','Drayage, Intermodal, LTL, Ocean, Parcel, Rail, Truckload',NULL,'Chassis (CH); Container (CN); Double-Drop Trailer (DD); Flat Bed Trailer (FT); LARGE STRAIGHT (G3); TRACTOR (G4); Controlled Temperature Trailer (Reefer) (RT);  (SV); Trailer, Bulk (TB); Trailer, Dry Freight (TF); Trailer, Tank (Chemicals) (TJ); Trailer, Tank (Food Grade-Liquid) (TK); Truck, Van (TV); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Cloud Trucking Inc','927267','CDKN','Drayage, Intermodal, Parcel',NULL,'Chassis (CH); TRACTOR (G4); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Cls Transport LLC','1290655','CNIP','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Cms Transport Inc','878559','CZMN','Drayage, Intermodal, Rail',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Cnj Freight  LLC','1306374','CNJO','Drayage, Intermodal, Ocean',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Coast To Coast Movers LLC','1576846','2569','LTL, Truckload',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Coastal Freight Carriers LLC','1009406','CFCL','Drayage, Intermodal, Truckload',NULL,'Chassis (CH); Cargo Van (CV); Flat Bed Trailer (FT); Fixed-Rack, Double Drop Trailer (RD); Single-Drop Trailer (SD);  (SV); Trailer, Bulk (TB); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Coastal Freight System Inc','1368170','CFZM','Drayage',NULL,'TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Coastal Investments Of Savannah LLC','1080701','CIJI','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Cobian Transportation LLC','0553954','1055','Drayage',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Cobra Transportation Services, Inc.','220329','CBQT','Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Colonel Boy''s Trucking LLC','1196072','CBEP','Drayage, Intermodal',NULL,'Chassis (CH); Container (CN); Cargo Van (CV); Double-Drop Trailer (DD); Flat Bed Trailer (FT); SMALL STRAIGHT (G2); LARGE STRAIGHT (G3); TRACTOR (G4); High Cube Van (HV); Load/unload Device on Equipment (LU); Open Top Van (OV); Fixed-Rack, Flat-bed Trailer (RA); Fixed-Rack, Double Drop Trailer (RD); Fixed-Rack, Single Drop Trailer (RS); Controlled Temperature Trailer (Reefer) (RT); Single-Drop Trailer (SD); Removeable Side Trailer (ST);  (SV); Trailer, Heater/Insulated/Vented (TA); Trailer, Bulk (TB); Trailer, Dry Freight (TF); Trailer, Tank (Gas) (TG); Trailer, Insulated (TI); Trailer, Tank (Chemicals) (TJ); Trailer, Tank (Food Grade-Liquid) (TK); Trailer (not otherwise specified) (TL); Trailer, Insulated/Ventilated (TM); Trailer, Pneumatic (TP); Trailer, Electric Heat (TQ); Truck, Van (TV); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Colton Transportation LLC','1262743','CJNT','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Columbus Transport','917117','CMBB','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Commercial Transportation, LLC','002605','CMRL','Drayage',NULL,'Cargo Van (CV); Flat Bed Trailer (FT);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Concord Express LLC','960258','CEXA','Drayage, Intermodal, LTL, Ocean',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Conglobal Industries ,Llc','265811','CGIN','Drayage',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Congo Express LLC','1200218','CELD','Drayage, Intermodal',NULL,'Chassis (CH); LARGE STRAIGHT (G3); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Connect Transport LLC','093717','CTCN','LTL',NULL,'Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Connections Logistics Inc','1680516','3709','Truckload',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Conquest LLC','1164379','2549','Drayage',NULL,'Container (CN); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Consolidated Freight Systems LLC','1090698','CFSR','Drayage, Intermodal, LTL, Ocean',NULL,'Chassis (CH);  (SV); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Container Cargo Carriers Inc','0638194','3205','Drayage',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Container Logistics Inc','1124666','CNRE','Drayage, Intermodal, Rail',NULL,'Chassis (CH); Flat Bed Trailer (FT); TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Container Transportation Experts Inc','756581','CTES','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Container Transportation Of New England LLC','870676','CTON','Drayage',NULL,'Chassis (CH); Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Containerport Group, Inc.','152125','CPGP','Drayage',NULL,'Cargo Van (CV);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Continental Freightway Inc','917833','CFWB','Drayage',NULL,'(SV); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Continental Transfer Inc','786819','CTFM','Drayage',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Contract Freight Management LLC','654870','CFMA','Drayage, Intermodal, Truckload',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Conventional Carrier Services LLC','1183236','2448','Intermodal, LTL',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Convoy Avenue Inc','1203891','1081','LTL, TL',NULL,'(SV); Truck, Van (TV); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Conway Logistics LLC','1051038','1200','Drayage, Intermodal, LTL',NULL,'Chassis (CH);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Cool Mountain Transport','879475','OSSE','Drayage','06/01/2020',NULL,'Nampa','ID','Carrier','150,000','06/01/2021','1,000,000','06/01/2020','1,000,000','06/01/2020'),
('Cooperative Logistics LLC','0528866','COOP','Drayage, Intermodal','02/11/2002','Chassis (CH)','FULLERTON','CA','Carrier','100,000','02/11/2021','0',NULL,'1,000,000','02/11/2002'),
('Cope/Bestway Express, Inc.','140349','COPB','Drayage, Intermodal, Rail, Truckload',NULL,'Chassis (CH); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Coqui LLC','1002109','2866','LTL, Truckload',NULL,'Flat Bed Trailer (FT); TRACTOR (G4); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Corbin Transportation Corp','1167876','CBNB','Drayage, Intermodal, LTL, Truckload',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Corner Carriers Inc','066699','CCII','Drayage, Intermodal',NULL,'Chassis (CH); Flat Bed Trailer (FT); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Corporal Drayage LLC','1424613','2442','Drayage',NULL,'Container (CN);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Cortez Enterprise LLC','1277535','CZEH','Drayage, Intermodal',NULL,'Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Cortez Jr Trucking LLC','1145999','CZJK','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Cosic','597710','COIC','LTL',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Cougar Truck Lines Inc','647675','CGRV','Drayage',NULL,'Cargo Van (CV);  (SV); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Country Boy Logistics LLC','1367539','CBGK','Intermodal',NULL,'Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Covered By Angels LLC','1355030','CBAH','Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Cowan Intermodal Group, LLC','155424','CIGL','Drayage, Intermodal, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Cowan Systems, LLC','271882','CWAW','Drayage',NULL,'(SV); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Cowan Transport Services, LLC','396918','CWPV','Drayage, LTL',NULL,'Chassis (CH);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Cowboys Trucking','123860','CWBJ','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Coyote Xpress LLC','089783','3649','LTL',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Craig Michael Express & Logistic Services LLC','1282217','1263','Drayage, Intermodal, LTL, Ocean, Parcel, Rail',NULL,'Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Craigs Transport LLC','1161919','CTEP','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Crespo Trucking LLC','714027','COKT','LTL, Truckload',NULL,'TRACTOR (G4); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Crockett Freight Lines LLC','1152013','CKFN','Drayage, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Crossroads Logistics Usa LLC','1043510','1211','LTL',NULL,'Cargo Van (CV); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Crown Trucklines Inc','1488962','2431','LTL, Truckload',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Crown Xpress Transport Inc','453813','CXPJ','Drayage',NULL,'Chassis (CH)','Chula Vista','CA','Carrier','250,000','03/17/2021',NULL,NULL,NULL,NULL),
('Crp Logistics LLC','1090412','1221','Air Freight, Drayage, Intermodal, LTL, Ocean, Parcel, Rail, Truckload',NULL,'Chassis (CH); Container (CN); TRACTOR (G4); Controlled Temperature Trailer (Reefer) (RT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Crr Logistics, Inc.','1398013','NCIT','Drayage, Intermodal, Parcel, Rail',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Csm Trucking LLC','1223703','CMYW','Drayage',NULL,'Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ctmp Transport LLC','1022268','1231','Drayage',NULL,'TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Cuadros Trucking LLC','077336','NONE','TL',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Cudjoe Transport L L C','1163625','CDJE','Intermodal, Ocean, Rail',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Customer Pickup',NULL,'CPUP','CustomerPickup',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Cyme Transports Inc','1194463','3252','Truckload',NULL,'TRACTOR (G4); Controlled Temperature Trailer (Reefer) (RT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('D & D American Transportation LLC','1217052','NONE','TL',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('D & E Multi Carrier Inc','1258645','DFGV','Drayage, Intermodal, LTL, Rail',NULL,'Chassis (CH); Container (CN); TRACTOR (G4); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('D & G Transport LLC','1046040','DGPK','Drayage, Intermodal, Ocean, Rail',NULL,'Chassis (CH); Double-Drop Trailer (DD); Flat Bed Trailer (FT); Fixed-Rack, Double Drop Trailer (RD)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('D & L Transport Services, LLC','1266703','2526','Intermodal, LTL, Truckload',NULL,'LARGE STRAIGHT (G3)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('D & M Logistics LLC','1022293','1175','LTL',NULL,'LARGE STRAIGHT (G3)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('D & W Trucking','976422','DWTK','Drayage, Intermodal, LTL, Rail',NULL,'Container (CN); LARGE STRAIGHT (G3); TRACTOR (G4); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('D C Family Logistics LLC','1372141','DFGE','Drayage, Intermodal, LTL, Rail',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('D H Trucking Inc','867618','1013','Drayage','11/21/2020',NULL,'Romulus','MI','Carrier','100,000','10/08/2020','1,000,000','11/21/2020','1,000,000','08/02/2021'),
('D L R Trucking & Contracting LLC','1064249','1105','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('D M Johnson Logistics LLC','1227183','JDGH','Drayage, Intermodal, LTL',NULL,'Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('D P T L LLC','754825','DPTH','LTL',NULL,'Flat Bed Trailer (FT); Trailer, Dry Freight (TF)','DIAMOND BAR','CA','Carrier',NULL,NULL,NULL,NULL,NULL,NULL),
('D&S Custom Transporter','1410995','2354','Drayage, Intermodal, Rail',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('D2 Trucking LLC','077555','D2TL','Drayage','02/27/2021',NULL,'Los Angeles','CA','Carrier','100,000','02/27/2021',NULL,NULL,'1,000,000','02/27/2021'),
('DNU - TEST Carrier','123456','TEST','Drayage, LTL, TL',NULL,NULL,'Phoenix','AZ','Carrier','0',NULL,'0',NULL,'0',NULL),
('DO_NOT_USE','5412214','DONO','LTL, TL',NULL,NULL,NULL,NULL,NULL,'0',NULL,'0',NULL,'0',NULL),
('Dan Trucklines Inc','1500786','2401','Drayage, Truckload',NULL,'Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Dana Express Trucking Inc','1346110','DETC','Drayage, Intermodal, Rail',NULL,'Chassis (CH); Container (CN); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Daniel & Son Trucking Inc','1496309','DAZS','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,'0',NULL,'0',NULL,'0',NULL),
('Daniel P Yeomans','1287375','YDPC','Drayage, Intermodal',NULL,'Container (CN);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Dara Transport Inc.','993442','DARA','Drayage','06/25/2021',NULL,'Bakersfield','CA','Carrier','100,000','06/25/2021','0',NULL,'1,000,000','06/25/2021'),
('Dargreens Trucking Inc','077967','DARG','Drayage',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Dart Logistics Express Inc','1121042','DLEG','Drayage, Intermodal, Rail',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Dash Transport LLC','1110736','2293','Truckload',NULL,'Chassis (CH); Container (CN); Cargo Van (CV); Double-Drop Trailer (DD)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Dat Daddy Trucking, LLC.','913385','DTDT','Drayage, Intermodal, Rail',NULL,'Chassis (CH);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Daver Trans Group, Inc','796547','1138','Drayage',NULL,'(SV); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Davidson Transportation Marketing, Inc.','192848','DVDO','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Daylight Logistics Inc','892461','DYLD','Drayage, Intermodal, Ocean, Rail',NULL,'Chassis (CH);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Daynite Express LLC','1085405','DEXR','Cartage, Drayage, Intermodal, Rail',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Dc Kinloch Transport LLC','1243999','KDAH','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Dc Trux Inc','1418872','2324','Drayage',NULL,'Chassis (CH); TRACTOR (G4); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Dch Transport','1109197','DCHW','Drayage, Intermodal, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Dda Transport LLC','314773','1187','Drayage, Intermodal, Rail',NULL,'Chassis (CH); Container (CN); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ddr Transport Inc','561968','DDRS','Drayage',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ddsi Transport LLC','972135','DSOL','Intermodal, Rail',NULL,'Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('De Jesus Trucking LLC','1133976','DJKD','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('De Lira Transport LLC','1579972','2479','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('De Mase Trucking Co., Inc.','150176','DEME','Drayage, Intermodal',NULL,'Chassis (CH); Double-Drop Trailer (DD); Flat Bed Trailer (FT); Single-Drop Trailer (SD)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Decatur Transport Inc','1443800','NONE','Air Freight, Drayage, LTL',NULL,'Flat Bed Trailer (FT);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Dee Trucking LLC','952384','DKGL','Drayage',NULL,'Container (CN); Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Deezy Trucking LLC','1182912','DTLF','Drayage',NULL,'Container (CN); TRACTOR (G4); Trailer (not otherwise specified) (TL)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Del Mar Tire Services Inc','056297','DMTY','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Delco Logistics Inc','089944','DECW',NULL,NULL,'TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Delivrance Enterprises Inc','885058','DVPQ','Drayage',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Dell''s Trucking LLC','147569','DTJJ','Drayage, Intermodal, LTL, Ocean, Rail, Truckload',NULL,'Chassis (CH); TRACTOR (G4); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Delmar Logistics LLC','1056769','DLMT','Drayage, Intermodal, LTL','10/03/0020','Chassis (CH)','Downey','CA','Carrier','100,000','10/03/2020','1,000,000','10/03/2020','1,000,000','10/03/0020'),
('Delow Logistics LLC','897783','DWLQ','Drayage, Intermodal, LTL, Rail',NULL,'Chassis (CH); Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Delphi Trucking Inc','1462595','2355','Air Freight, LTL, Truckload',NULL,'Cargo Van (CV); LARGE STRAIGHT (G3)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Delta Logistics, Inc.','577331','DLXI','Drayage',NULL,'Cargo Van (CV);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Delta Trucking Logistics Inc','027767','2884','LTL',NULL,'Double-Drop Trailer (DD); Flat Bed Trailer (FT); Fixed-Rack, Single Drop Trailer (RS); Trailer (not otherwise specified) (TL)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Delve Intermodal LLC','1462714','DEVC','Drayage, Intermodal, LTL, Rail',NULL,'Chassis (CH); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Dem Trucking LLC','803467','DEMK','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Deniz Transportation LLC','1445329','DFIJ','Intermodal, LTL',NULL,'Single-Drop Trailer (SD)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Denver Cartage Company','179578','DNCG','Drayage',NULL,'Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Denver Intermodal Express, Inc.','273706','DNVR','Drayage, Intermodal, LTL',NULL,'Chassis (CH); Cargo Van (CV); Flat Bed Trailer (FT); SMALL STRAIGHT (G2); Controlled Temperature Trailer (Reefer) (RT); Trailer (not otherwise specified) (TL); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Deo Transport LLC','009121','DEOO','Drayage, Intermodal, LTL',NULL,'Cargo Van (CV);  (SV); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Deol Transport','1088113','2267','Air Freight',NULL,'Truck, Van (TV); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Deossa Transportation LLC','1489202','3854','Drayage, Intermodal, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Dependable Express LLC','1125906','DELA','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Desert Diamond Transportation LLC','1019953','2485','TL',NULL,'Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Desert Eagle Express Inc','1441246','DEEE','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Deuces Trucking Inc','669126','DEUC','Drayage, Ocean, Rail',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Devoe Transportation LLC','1136775','DVOR','Drayage, Intermodal, Rail',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Dgb Trucking LLC','1186297','DGBY','Air Freight, Cartage, Drayage, Intermodal, LTL',NULL,'TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Dgc Logistics LLC','1669262','DGCQ','Drayage, Intermodal',NULL,'Chassis (CH); Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Dgo Transportation Inc','092356','DGON','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Dh Carriers','560955','DHCA','Intermodal, Truckload',NULL,'TRACTOR (G4);  (SV); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Dhe','139496','DPHE','Drayage, Intermodal, LTL',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Dhesi Transport Inc','1062392','DHGJ','Drayage, Intermodal, Rail',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Dhillon 4 Trucking Inc','760586','A101','Drayage','10/11/2020',NULL,'Upland','CA','Carrier','250,000','10/11/2020','1,000,000','10/11/2020','1,000,000','10/11/2020'),
('Dhuri Transport LLC','036512','2904','Drayage',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Diamante Negro Carrier','1271211','2488','Ocean',NULL,'Chassis (CH); Container (CN); Controlled Temperature Trailer (Reefer) (RT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Diamond Freight Distribution Inc.','372583','DFDO','Drayage',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Diamond P Enterprises LLC','1173427','DPEF','Drayage, Intermodal',NULL,'Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Diamond Trucking Express Inc','882149','DTVF','Drayage, Intermodal',NULL,'Chassis (CH);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Diamonds & Decades Transportation Inc','1464714','DDBD','LTL, Ocean',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Diaz & Ramos Trucking','006758648C','DIAZ','Drayage','12/02/2020',NULL,'Pflugerville','TX','Carrier','100,000','12/02/2020','0',NULL,'1,000,000','12/02/2020'),
('Dibenedetto Distribution Inc','1334737','DDID','Drayage, Intermodal, Ocean',NULL,'Chassis (CH); Container (CN); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Dickey Logistics','1186770','DKYJ','LTL, Truckload',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Diesel Bully Transportation LLC','1629004','3509','Drayage, Intermodal, LTL, Ocean, Rail',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Diggs And Sons Transport LLC','1072253','DGGS','Drayage, LTL, Rail, Truckload',NULL,'Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Direct Drive Transportation LLC','1234567','1186','Drayage, Intermodal, LTL, Rail',NULL,'Cargo Van (CV); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Dirty Bird Trucking LLC','1239812','DBDK','Drayage',NULL,'TRACTOR (G4); Single-Drop Trailer (SD)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Divas Transportation Inc','1338576','DTUP','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Divine Exodus Transport LLC','1332396','DVXS','Drayage, Intermodal, LTL',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Dixie Express','415801','DXES','Intermodal',NULL,NULL,'Hillsboro','OH','Carrier','100,000','08/18/2021','0',NULL,'0',NULL),
('Diya Transportation LLC','1088827','DYAS','Drayage',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Djl Transport LLC','1228981','DJLP','Drayage, Intermodal',NULL,'Chassis (CH); Cargo Van (CV); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Dk Express','505056','DEXG','Drayage','07/08/2020',NULL,'Garden Grove','CA','Carrier','250,000','05/17/2021','1,000,000','07/08/2020','1,000,000','07/08/2020'),
('Dk Express LLC','1305012','DKEW','Drayage, Intermodal, LTL, Parcel, Rail',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Dlc Transport','1152821','1063','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Dlc Trucking LLC','1205622','DLCT','Drayage',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Dlee Logistics LLC','1063612','DLPY','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Dlha Transport LLC','1390713','DHAE','Drayage, Rail',NULL,'TRACTOR (G4); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Dlt','657445','DLHW','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Dm & Sons Trucking LLC','1059728','DMEK','Intermodal, LTL',NULL,'Chassis (CH); TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Dmc Transport LLC','1259201','2558','Drayage, Intermodal, Rail',NULL,'Cargo Van (CV); TRACTOR (G4); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Dmm Express','772796','DMMP','LTL','01/27/2021',NULL,'Vancouver','WA','Carrier','100,000','01/27/2021',NULL,NULL,'1,000,000','01/27/2021'),
('Dmo Transport Services LLC','1203397','DTSE','Drayage, Intermodal, LTL',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Dnj Intermodal Services LLC','712938','DNJI','Drayage, Intermodal, Rail',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Doan Trucking Inc','067756','2944','Air Freight',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Dock 2 Dock Transport LLC','1325339','DTTG','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Dolomite & Associates Inc','1386639','DAIL','Drayage, Intermodal',NULL,'TRACTOR (G4); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Dolphin Trucking LLC','753464','DPHK','Drayage, Rail',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Don''t Stop Trucking','596546','DNSI','Drayage',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Donald And Sons, Inc.','134515','DONA','LTL','08/26/2020',NULL,'Burbank','CA','Carrier','100,000','06/30/2020',NULL,NULL,'1,000,000','08/26/2020'),
('Doran Freight Solutions LLC','1689584','DORJ','Intermodal, LTL',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Dot-Line Transportation','151374','DOLR','LTL',NULL,'Cargo Van (CV); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Double Ja Trucking LLC','1256078','DJBH','Intermodal, LTL',NULL,'Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Double N Logistics LLC','1211028','1115','Drayage',NULL,'TRACTOR (G4)',NULL,NULL,NULL,'0',NULL,'0',NULL,'0',NULL),
('Dr Drayage Inc','1358632','DDZH','Drayage',NULL,'Chassis (CH); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Dr Transportation Corp','1252065','1218','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Draco Freight Trucking Logistics Corp','1065862','DFTM','Drayage, Intermodal, Ocean, Rail',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Dragon X LLC','1269517','DXLK','Drayage, Intermodal',NULL,'Chassis (CH); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Drayage Connection Inc','1302107','DCFV','Drayage, Intermodal, LTL, Ocean, Rail',NULL,'Container (CN); Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Drayage Group Inc','1139953','DGBW','Drayage',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Drayage Solutions LLC','068030','DYGS','Drayage',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Drd Logistics LLC','1467788','DRDM','Drayage, Intermodal, Rail',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Dreamers Trucking LLC','1311829','3027','Drayage',NULL,'TRACTOR (G4); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Dreamhunt Transport Inc','1161838','DHFF','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Dreamville Trucking Company','1154846','DRMK','LTL',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Drf Transport LLC','056569','1103','Drayage, Intermodal, LTL, Ocean, Rail',NULL,'Chassis (CH); Container (CN); Flat Bed Trailer (FT); TRACTOR (G4); Controlled Temperature Trailer (Reefer) (RT);  (SV); Trailer (not otherwise specified) (TL)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Drivr Transports And Logistics Limited Liability C','1317521','DRHJ','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Drt Trucking LLC','1066935','1088','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Drua Logistics Inc.','537966','DLIA','Air Freight, Drayage, Intermodal, Ocean, Rail',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Dscs Trucking LLC','1473806','3185','Drayage, Intermodal',NULL,'Chassis (CH); Flat Bed Trailer (FT); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Dsm Carriers Inc','1272614','3712','LTL',NULL,'Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Dst','1297272','2540','Intermodal, LTL, Truckload',NULL,'Single-Drop Trailer (SD)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Dsync Transport, LLC','811317','DUEQ','Drayage, Intermodal, Rail',NULL,'Container (CN); Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Dub C Logistics LLC','1353568','DCQN','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Dubai Transport LLC','1216404','DUBA','Air Freight, Cartage, Drayage, Intermodal, LTL, Ocean, Parcel, Rail, Truckload',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Duncan & Son Lines','144606','DNSL','Drayage',NULL,NULL,'Buckeye','AZ','Carrier','250,000','03/01/2021',NULL,NULL,NULL,NULL),
('Dunn & Gipp Logistics LLC','1396962','DGLJ','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Dunston Trucking LLC','1197065','DNKL','Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Dupre Logistics, LLC','158069','DUPR','Drayage, Intermodal, LTL',NULL,'Chassis (CH); Container (CN); Cargo Van (CV); Double-Drop Trailer (DD); Flat Bed Trailer (FT); TRACTOR (G4); Controlled Temperature Trailer (Reefer) (RT);  (SV); Trailer, Heater/Insulated/Vented (TA); Trailer, Bulk (TB); Trailer, Tank (Gas) (TG); Trailer, Tank (Chemicals) (TJ); Trailer, Pneumatic (TP); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Dustin L Reed Trucking LLC','761533','RDJG','Drayage',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Dvd Trucking Corp','893342','DVDD','Drayage',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Dwoodmyr LLC','1306781','DWBB','Drayage, Intermodal, LTL',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Dwright Trucking LLC','1206007','DWGH','Drayage, Intermodal, LTL, Ocean, Parcel, Rail',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Dy Express Corp','1136329','DECO','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('E & C Empire Inc','1416185','2483','Air Freight, Cartage',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('E & D Services Of El Paso, Inc.','199368','JPRT','Drayage',NULL,'Chassis (CH); Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('E & J Container Drayage','1001179','EJCA','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('E Circuit Transport Inc','1186583','1214','Drayage',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('E Logistics','850813','ELVC','Drayage, Intermodal',NULL,'Chassis (CH); Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('E Martinez Trucking LLC','1263734','2282','Drayage',NULL,'TRACTOR (G4)',NULL,NULL,NULL,'0',NULL,'0',NULL,'0',NULL),
('E6 Transport LLC','1439341','ESEV','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ea & L Logistics Inc','042608','EALQ','Drayage','06/28/2020',NULL,'South Gate','CA','Carrier','100,000','06/28/2021','1,000,000','06/28/2020','1,000,000','06/28/2020'),
('Eag Trucking LLC','1143106','ETYJ','Air Freight, Drayage, Intermodal, Rail',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Eagle Claws Trans Inc','1189650','ECNP','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Eagle Freight LLC','1101307','EFAL','Drayage',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Eagle Logistics LLC','832097','EGLG','Truckload',NULL,'Chassis (CH); Container (CN); Cargo Van (CV); Controlled Temperature Trailer (Reefer) (RT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Eagle Motor Freight LLC','870493','3896','Intermodal',NULL,'Chassis (CH); Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Eagle Systems, Inc.','157824','EGSY','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Eagle Transco - Et','1488794','2702','LTL, Truckload',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Eagle Transport LLC','1137935','2575','LTL',NULL,'Cargo Van (CV);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Eagle Transportation , LLC','587359','2425',NULL,NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Eai Overnight Express LLC','1447224','2474','Drayage',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Earlie Boys Transport LLC','1449060','EBPT','Intermodal',NULL,'Chassis (CH); Container (CN); Cargo Van (CV); Double-Drop Trailer (DD); Flat Bed Trailer (FT); SMALL STRAIGHT (G2); LARGE STRAIGHT (G3); TRACTOR (G4); High Cube Van (HV); Load/unload Device on Equipment (LU); Open Top Van (OV); Fixed-Rack, Flat-bed Trailer (RA); Fixed-Rack, Double Drop Trailer (RD); Fixed-Rack, Single Drop Trailer (RS); Controlled Temperature Trailer (Reefer) (RT); Single-Drop Trailer (SD); Removeable Side Trailer (ST);  (SV); Trailer, Heater/Insulated/Vented (TA); Trailer, Bulk (TB); Trailer, Dry Freight (TF); Trailer, Tank (Gas) (TG); Trailer, Insulated (TI); Trailer, Tank (Chemicals) (TJ); Trailer, Tank (Food Grade-Liquid) (TK); Trailer (not otherwise specified) (TL); Trailer, Insulated/Ventilated (TM); Trailer, Pneumatic (TP); Trailer, Electric Heat (TQ); Truck, Van (TV); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Easley Transportation, LLC','360941','ELEY','Air Freight, Cartage, Drayage, Intermodal, LTL, Rail',NULL,'Chassis (CH); Cargo Van (CV); Controlled Temperature Trailer (Reefer) (RT); Trailer (not otherwise specified) (TL); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('East Coast Logistic','640644','ECRR','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4)','Fontana','CA','Carrier',NULL,NULL,NULL,NULL,NULL,NULL),
('East Coast Logistics Inc','082976','ECGQ','Drayage, Intermodal',NULL,'Chassis (CH); Cargo Van (CV); Double-Drop Trailer (DD)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('East Da West LLC','1259335','3954',NULL,NULL,'Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('East To West Transporters Inc','795421','1014','LTL','06/04/2021',NULL,'Glendale','CA','Carrier','250,000','06/04/2021','1,000,000','06/04/2021','1,000,000','06/04/2021'),
('Eastern Express, Inc.','149582','EARL','LTL, Truckload',NULL,'Cargo Van (CV); Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Easy Money Trucking LLC','1496043','2519','Drayage, Intermodal, Rail',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Easy Rider Inc','1503363','NONE','Drayage, LTL',NULL,'Cargo Van (CV);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Easy-Haul Intermodal Inc','1336123','EHAQ','Drayage, Intermodal',NULL,'Chassis (CH); Container (CN); Cargo Van (CV); Double-Drop Trailer (DD); Flat Bed Trailer (FT); SMALL STRAIGHT (G2); LARGE STRAIGHT (G3); TRACTOR (G4); High Cube Van (HV); Load/unload Device on Equipment (LU); Open Top Van (OV); Fixed-Rack, Flat-bed Trailer (RA); Fixed-Rack, Double Drop Trailer (RD); Fixed-Rack, Single Drop Trailer (RS); Controlled Temperature Trailer (Reefer) (RT); Single-Drop Trailer (SD); Removeable Side Trailer (ST);  (SV); Trailer, Heater/Insulated/Vented (TA); Trailer, Bulk (TB); Trailer, Dry Freight (TF); Trailer, Tank (Gas) (TG); Trailer, Insulated (TI); Trailer, Tank (Chemicals) (TJ); Trailer, Tank (Food Grade-Liquid) (TK); Trailer (not otherwise specified) (TL); Trailer, Insulated/Ventilated (TM); Trailer, Pneumatic (TP); Trailer, Electric Heat (TQ); Truck, Van (TV); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Easydray Inc','1212183','EDYN','Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ebannerman Trucking LLC','425592','ELAF','Air Freight, Cartage, Drayage, Intermodal, LTL, Ocean, Parcel',NULL,'Chassis (CH); Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ebc Transport LLC','1198767','EBCN','Drayage, Intermodal, Truckload',NULL,'Flat Bed Trailer (FT); TRACTOR (G4); Trailer, Dry Freight (TF); Trailer (not otherwise specified) (TL)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ebenezer Express Trucking LLC','1073657','EBZE','Cartage, Drayage, Intermodal, LTL, Ocean, Parcel, Rail',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ecko Transportation & Logistics, LLC','950338','ECKP','Drayage, Intermodal, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Eda Transports LLC','1525687','2506','Truckload',NULL,'SMALL STRAIGHT (G2); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Edison Trucklines Inc','1468231','2295','LTL, TL',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Edith''s Trucking','577502','2494','TL',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Edmiston Trucking','422402','1213','Drayage, LTL',NULL,'Cargo Van (CV);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Edwards Express, LLC','617938','EELL','Drayage, Intermodal, LTL',NULL,'Controlled Temperature Trailer (Reefer) (RT); Trailer, Dry Freight (TF); Trailer (not otherwise specified) (TL)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Eg Logistics Inc','976963','EGLC','Drayage, TL',NULL,'(SV); Trailer, Dry Freight (TF); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('El Chan Transport LLC','1130487','2550','Drayage, Intermodal, LTL, Rail',NULL,'Container (CN); TRACTOR (G4);  (SV); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('El Pollo O Galdamez LLC','045607','EPOG','Drayage',NULL,'Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Elai Group Inc','065394','EGIN','Drayage',NULL,NULL,'Bell','CA','Carrier','100,000','03/02/2021','0',NULL,'0',NULL),
('Elai Group Inc','065394','EGIN','Drayage',NULL,NULL,'Bell','CA','Carrier',NULL,NULL,NULL,NULL,NULL,NULL),
('Elevate Trucking Corp','1399966','ETCM','Drayage, Intermodal',NULL,'Chassis (CH); Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Elevated Express 05 LLC','1409512','EEZA','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Elite Drayage Carriers LLC','025354','EDYC','Drayage',NULL,'Chassis (CH)','LONG BEACH','CA','Carrier',NULL,NULL,NULL,NULL,NULL,NULL),
('Elite Hauling Inc','1212330','1247','Drayage, Intermodal, LTL, Rail',NULL,'TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Elite Logistics Corporation','445668','ELLC','Drayage, Intermodal',NULL,'LARGE STRAIGHT (G3)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Elite Routing Transportation','927134','ERTN','Drayage',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Elite Transport & Logistics','1285005','ETXB','Drayage',NULL,'Chassis (CH); TRACTOR (G4); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Elite Trucking Services, LLC','758503','ETSE','Drayage',NULL,'Chassis (CH); Flat Bed Trailer (FT); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Eliteone Transportation','890424','ELIT','Drayage, LTL','08/10/2020','Chassis (CH); Container (CN); Cargo Van (CV); Double-Drop Trailer (DD); Flat Bed Trailer (FT); Fixed-Rack, Flat-bed Trailer (RA); Trailer, Refrigerated (TW)','Schaumburg','IL','Carrier','300,000','08/10/2021','1,000,000','08/10/2020','1,000,000','08/23/2020'),
('Ella Trucking Inc','1340237','1229','Drayage',NULL,'Chassis (CH); Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ellis Reliable Transport LLC','108367','ERBP','Drayage, Intermodal, LTL',NULL,'TRACTOR (G4); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Elvis-Nathaniel Inc','1047092','1015','Drayage','07/03/2021',NULL,'Chino Hills','CA','Carrier','100,000','07/03/2021','0',NULL,'1,000,000','07/03/2021'),
('Emerald Coast Transport Inc','549854','EDCP','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Emerson Transportation Inc.','813723','SLII','Drayage, Intermodal','12/17/2020','Chassis (CH)','Harbor City','CA','Carrier','250,000','12/17/2020','1,000,000','12/17/2020','1,000,000','12/17/2020'),
('Emj Transport LLC','1136511','EMJP','Drayage, Intermodal',NULL,'Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Empire Global LLC','1174354','2574','Truckload',NULL,'TRACTOR (G4); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Empire National Inc.','966111','ENIC','LTL, Ocean',NULL,'Cargo Van (CV);  (SV); Trailer, Dry Freight (TF); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Emuna Transport Inc','1500834','NA','Intermodal',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('En Route Logistix Inc','1070943','ERLA','Drayage, Ocean',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('En Transportation LLC','137249','ENTL','Drayage','10/13/2020',NULL,'Wayne','NJ','Carrier','100,000','09/26/2020','1,000,000','10/13/2020','1,000,000','10/13/2020'),
('Endeavor Freightways Inc','809599','EDVH','LTL',NULL,'TRACTOR (G4); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Endeavour Transport Services Inc','893709','EVTE','Drayage, Intermodal',NULL,'Chassis (CH); Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Energy Transport Logistics','865694','ETLT','Drayage','04/01/2020',NULL,'Tolleson','AZ','Carrier','300,000','06/22/2021','1,000,000','06/22/2020','1,000,000','04/01/2020'),
('Enlace Strategies Inc','027832','ESIR','Drayage',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ennels Enterprises LLC','621806','ENEL','Drayage, Intermodal, Rail',NULL,'Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ensure Trucking Inc','868044','ENSI','Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ensz Transport LLC','1379688','2309','Air Freight, Drayage',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Enterprise Truck Line, Llc.','123194','ENTP','Cartage, Drayage, Intermodal, LTL, Rail',NULL,'Chassis (CH); TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Envio Logistics Transport','1040842','ENVM','Drayage, LTL',NULL,'Flat Bed Trailer (FT); TRACTOR (G4); Single-Drop Trailer (SD)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Eog Inc','1079488','EOGI','Drayage, Intermodal, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Eos Group Inc','011209','EOSJ','Air Freight',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Epic Transport LLC','027110','EPIT','Drayage',NULL,'Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Erazo Enterprises Inc','1483460','3488','Drayage, Intermodal',NULL,'Flat Bed Trailer (FT); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Erd Express, Inc.','680678','2343','Air Freight, Drayage, Intermodal, Truckload',NULL,'TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ernest Trucking LLC','1419918','ETOT','Drayage, Intermodal, Rail',NULL,'Chassis (CH); Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Erod Trucking Inc','1478371','2339','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Esco Logix LLC','1670135','ESDT','Drayage, Intermodal, Ocean, Rail',NULL,'TRACTOR (G4); Trailer (not otherwise specified) (TL)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Espino Truck Lines LLC','1429510','2394','Air Freight, LTL, Truckload',NULL,'Cargo Van (CV); TRACTOR (G4); Truck, Van (TV); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Esquivel Trucking','1258821','3044','Air Freight, Cartage, Drayage, LTL',NULL,'Container (CN); Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Estrada Trucking','859522','2413','LTL',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Etv Trucking Inc','1417773','2344','LTL',NULL,'TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Eva Trans Inc','1184862','EVA','Drayage, LTL',NULL,'TRACTOR (G4);  (SV); Trailer, Dry Freight (TF); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Eva Trucking Inc','1174627','1109','TL',NULL,'(SV); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Evag Logistics Corp','1167371','ELCJ','Drayage, Intermodal, Ocean',NULL,'Container (CN); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Evans Delivery Company, Inc.','057591','EDFF','Drayage','06/28/2020',NULL,'Pottsville','PA','Carrier','50,000','06/28/2025','1,000,000','06/28/2020','2,000,000','06/28/2020'),
('Ever Forth LLC','065605','EVER','Drayage','12/19/2020',NULL,'Bakersfield','CA','Carrier','100,000','12/19/2020','0',NULL,'1,000,000','12/19/2020'),
('Ever Freight Transport Inc','1090586','EFTT','Drayage',NULL,'Chassis (CH); Fixed-Rack, Single Drop Trailer (RS); Single-Drop Trailer (SD)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Evergreen Hotshot LLC','1217770','2517','Truckload',NULL,'Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Everrank Express Inc','867696','EEIC','Drayage, Intermodal, LTL',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Everything 2 Logistics LLC','1309299','EVBJ','Drayage, Intermodal, LTL, Ocean, Parcel, Rail',NULL,'Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Evn Global','1015325','1016','Drayage','12/09/2020',NULL,NULL,NULL,NULL,'100,000','12/09/2020','1,000,000','03/06/2021','1,000,000','12/09/2020'),
('Excell Services Of Savannah LLC','1048484','ESOA','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Exceptional Logistics LLC','010452','EXGT','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Exclusive Logistics LLC','1136063','EXVT','Drayage, Intermodal, Ocean, Rail',NULL,'Chassis (CH); Container (CN); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Executive Transportation LLC','1087895','3254','Drayage, Intermodal',NULL,'Container (CN); Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Experts Transportation LLC','1363980','ETWY','Drayage, Intermodal',NULL,'Chassis (CH); Container (CN); Controlled Temperature Trailer (Reefer) (RT); Trailer (not otherwise specified) (TL)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Express Lane, Inc.','735491','1119','Drayage, Intermodal, LTL, Ocean, Parcel, Rail',NULL,'(SV); Trailer, Dry Freight (TF); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Eze Trucking LLC','1091061','EZEK','Drayage, Intermodal',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('F & C Trucking And Repair LLC','1365658','FCAI','Drayage, Intermodal',NULL,'Chassis (CH); Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('F & J Express Inc','628778','1017','LTL','04/08/2020',NULL,NULL,NULL,NULL,'100,000','04/11/2021','1,000,000','04/08/2020','1,000,000','04/11/2021'),
('F & S Logistics LLC','592534','FSLR','Drayage, Intermodal, LTL',NULL,'Chassis (CH); TRACTOR (G4); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('F Williams Logistics LLC','883498','1101','Drayage, Intermodal, LTL',NULL,'Flat Bed Trailer (FT); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('F.A.L. Transportation Inc','429484','FALS','Drayage','10/29/2020',NULL,NULL,NULL,NULL,'100,000','10/29/2020','1,000,000','10/29/2020','1,000,000','10/29/2020'),
('F.s. Transport LLC','1045698','FSQA',NULL,NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('F2f Transport, LLC','168085','FTFE','LTL, TL',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('FORREST LOGISTICS',NULL,'FLJM','Drayage',NULL,NULL,NULL,NULL,NULL,'0',NULL,'0',NULL,'0',NULL),
('Fairfield Express Inc','1045516','FFXQ','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Fairmount Logistic LLC','833871','FMGS','Drayage, Intermodal',NULL,'Cargo Van (CV); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Faith Courier LLC','1308225','FCLD','Drayage, Intermodal',NULL,'Chassis (CH); Cargo Van (CV); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Faith Trucking LLC','961356','FHKM','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Falcon Express Freight Inc','1047697','FEFI','Cartage, Drayage, Intermodal, LTL, Rail',NULL,'(SV); Truck, Van (TV); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Falcon Transport, Inc.','145282','FALT','Cartage, Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Family First Enterprise LLC','1102713','FFEV','Drayage, Intermodal, Rail',NULL,'Container (CN); TRACTOR (G4);  (SV); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Fanatic Transportation Inc','1173332','NONE',NULL,NULL,'Controlled Temperature Trailer (Reefer) (RT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Fannum Trucks','079714','FNNK','Drayage, Intermodal, LTL, Ocean, Rail',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Farm Fresh Transport Inc','1005952','FFTI','Drayage','06/13/2020',NULL,'Oceanside','CA','Carrier','100,000','06/13/2021','1,000,000','06/13/2020','1,000,000',NULL),
('Fast & Easy Trucking LLC','1428411','2438','LTL',NULL,'TRACTOR (G4); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Fast Delivery Express,Inc.','432179','3306','LTL, Truckload',NULL,'Cargo Van (CV); TRACTOR (G4); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Fast Freight Transportation LLC','1297862','2546','Air Freight, Drayage, Intermodal, LTL, Parcel, Truckload',NULL,'LARGE STRAIGHT (G3); Load/unload Device on Equipment (LU); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Fast Line Trucking Inc','561851','FLAJ','Truckload',NULL,'Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Fast Route Transport LLC','1029472','FRJW','Drayage, Intermodal, Rail',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Fast Track Hauling LLC','1361781','FTHB','Drayage, Intermodal, LTL, Truckload',NULL,'Flat Bed Trailer (FT); TRACTOR (G4); Single-Drop Trailer (SD)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Fast&Reliable Trucking','031576','FRRQ','Drayage, Intermodal, LTL, Ocean',NULL,'Chassis (CH); Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Fate Express Inc','053006','FXAP','Drayage, Intermodal',NULL,'Chassis (CH); Container (CN); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Father & Sons Logistics, LLC','826891','2375','Ocean',NULL,'Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Father And Son Trucking Inc','923417','2393','Air Freight, Cartage, LTL, Truckload',NULL,'TRACTOR (G4); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Favorit Logistics Inc','068708','FBCH','LTL, Truckload',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Fc Transport Inc','1640936','4014','Truckload',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Featherlite Logistics LLC','940290','FHLR','Intermodal',NULL,'Chassis (CH);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Felix Freight Service LLC','131754','FXFK','Drayage, Intermodal, Rail',NULL,'Chassis (CH); Cargo Van (CV); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Felix Gallardo Transportation LLC','1252513','1197','Drayage',NULL,'Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Fent Logistics Corp','1457817','2480','Intermodal',NULL,'Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Fergusons Spot On Trucking','1328416','FSOI','Drayage, Intermodal, Rail',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ferns & Sons Trucking Co Inc','781940','FNOK','Drayage, Intermodal, LTL, Rail',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Fernway Transportation LLC','1677193','FEVI','Drayage, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ferrari Transportation Inc','1044437','FERP','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ferrer Logistics Llc.','934526','FERR','Drayage','12/10/2020',NULL,'Miami','FL','Carrier','100,000','12/10/2020','1,000,000','12/10/2020','1,000,000','12/10/2020'),
('Fgm Logistics LLC','716161','FGMC','Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Fida LLC','846108','2925','Drayage',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Fidaee Trucking Co','017569','2400','LTL, Truckload',NULL,'(SV); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Fierce Ft Trucking LLC','1311147','FFNQ','Drayage',NULL,'Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Fifty State Transportation Inc','744884','FIFT','Drayage, LTL',NULL,'(SV); Trailer, Heater/Insulated/Vented (TA); Trailer, Insulated (TI); Truck, Van (TV); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Fila Trucking Co','1264199','FLKD','Drayage, Intermodal',NULL,'Chassis (CH); Container (CN); Cargo Van (CV); Double-Drop Trailer (DD); Flat Bed Trailer (FT); SMALL STRAIGHT (G2); LARGE STRAIGHT (G3); TRACTOR (G4); High Cube Van (HV); Load/unload Device on Equipment (LU); Open Top Van (OV); Fixed-Rack, Flat-bed Trailer (RA); Fixed-Rack, Double Drop Trailer (RD); Fixed-Rack, Single Drop Trailer (RS); Controlled Temperature Trailer (Reefer) (RT); Single-Drop Trailer (SD); Removeable Side Trailer (ST);  (SV); Trailer, Heater/Insulated/Vented (TA); Trailer, Bulk (TB); Trailer, Dry Freight (TF); Trailer, Tank (Gas) (TG); Trailer, Insulated (TI); Trailer, Tank (Chemicals) (TJ); Trailer, Tank (Food Grade-Liquid) (TK); Trailer (not otherwise specified) (TL); Trailer, Insulated/Ventilated (TM); Trailer, Pneumatic (TP); Trailer, Electric Heat (TQ); Truck, Van (TV); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Finest Freight Transport LLC','122185','FFHP','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Finest Trans Group','086557','3610','LTL',NULL,'Trailer (not otherwise specified) (TL)',NULL,NULL,NULL,'0',NULL,'0',NULL,'0',NULL),
('Firefreight Inc','901910','FRFS','Drayage, LTL',NULL,'Chassis (CH); TRACTOR (G4); Load/unload Device on Equipment (LU)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('First Coast Logistics Of North Florida, LLC','705095','FCGN','Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('First Coast Transport LLC','1091397','1123','Drayage, Intermodal',NULL,'Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('First Eagle Logistics Inc','044326','FELA','Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('First Rate Trucking LLC','1118969','FRKA','Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Fishegg Trucking LLC','837188','FHGK','Drayage, Intermodal',NULL,'TRACTOR (G4);  (SV); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Fitted Transport Inc','1043131','FITT','Drayage, Intermodal',NULL,'Chassis (CH); Container (CN); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Five Rivers Express LLC','025807','2406',NULL,NULL,'(SV); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Five Times Inc','1497212','3995','LTL',NULL,'(SV); Trailer, Dry Freight (TF); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Flat-Line Xpress LLC','1140637','3550','Cartage, Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Flawless Logistics Inc','1223293','FWSG','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Fleetmasters LLC','890857','FEVP','Air Freight',NULL,'Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Fleites Transport LLC','007211075C','FLEIT','LTL','05/02/2021',NULL,'New Braunfels','TX','Carrier','100,000','05/02/2021',NULL,NULL,'1,000,000','05/02/2021'),
('Fly Interchange Inc.','721407','FIML','Drayage, Intermodal, LTL',NULL,'Chassis (CH); Container (CN);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Fm Logistics Corp','1019064','FMGE','Drayage, Intermodal, LTL, Rail, Truckload',NULL,'Container (CN); Cargo Van (CV); TRACTOR (G4);  (SV); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Fm Trucking Inc','1362417','1212','LTL',NULL,'(SV); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Fmb Global Express Inc','1136395','FGEE','Drayage, LTL',NULL,'Chassis (CH); Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Fmj Freight & Logistics LLC','1004147','FMJF','Drayage','01/14/2021',NULL,'Paramount','CA','Carrier','100,000','01/14/2021','1,000,000','01/14/2021','1,000,000','01/14/2021'),
('Focus Global Logistics Inc','013536','FGLW','Drayage, Truckload',NULL,'Chassis (CH); Flat Bed Trailer (FT); SMALL STRAIGHT (G2);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Fonseca & Sons LLC','1388578','FSOK','Truckload',NULL,'Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('For My Son Transport Of Savannah LLC','1309747','FMSH','Drayage',NULL,'Container (CN); TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Forceful Trans Inc','1183152','FTIV','Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ford 4 Trucking LLC','1108719','FDFK','Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Foreign Trade Export Packing Company','394897','FTEC','Air Freight, Drayage, Intermodal, LTL, Ocean','10/02/2025','Chassis (CH); Cargo Van (CV); Double-Drop Trailer (DD); TRACTOR (G4); Fixed-Rack, Single Drop Trailer (RS); Single-Drop Trailer (SD);  (SV); Truck, Van (TV)',NULL,NULL,NULL,'100,000','10/02/2025',NULL,NULL,NULL,NULL),
('Forever, Inc.','977606','1079','Drayage',NULL,'TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Forrest Transportation LLC','1062597','FRQT','Drayage','10/29/2020',NULL,'Phoenix','AZ','Carrier','100,000','10/29/2020','1,000,000','10/29/2020','1,000,000','10/29/2020'),
('Forsage Inc','907486','2395',NULL,NULL,'Cargo Van (CV);  (SV); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Forward Freight LLC','918569','1179','Air Freight, Drayage, LTL, Parcel',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Forward Intermodal','152337','1092','Drayage, LTL',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Forward Progress Trans LLC','1189444','1135','LTL',NULL,'Flat Bed Trailer (FT);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Forward Trans Inc','1093210','FWDM','Drayage',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Four Brothers Express, Inc.','843184','FBES','Drayage',NULL,'(SV); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Four Child Transport LLC','1263379','FOUF','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Fox Transportation Inc','528670','FXTR','Intermodal',NULL,'TRACTOR (G4); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Foxtran','631802','FOXF','Truckload',NULL,'Flat Bed Trailer (FT); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Fr8 Lyft LLC','1126498','1072','Drayage, LTL',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('France Delivery','1089738','FNDV','Drayage, Intermodal',NULL,'TRACTOR (G4); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Franco Trucking, Inc.','690842','FCKI','Drayage',NULL,'Chassis (CH); Container (CN); Flat Bed Trailer (FT); Trailer, Dry Freight (TF); Trailer (not otherwise specified) (TL)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
ON CONFLICT (scac) DO NOTHING;

INSERT INTO mg_carriers (name,mc_number,scac,modes,early_ins_exp,equipment,loc_city,loc_state,loc_type,cargo_ins_amt,cargo_ins_exp,general_ins_amt,general_ins_exp,liability_ins_amt,liability_ins_exp) VALUES
('Frcc','1158922','1163','Drayage, Intermodal',NULL,'Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Freedom 1 Freight LLC','1321875','FOFF','Drayage, Intermodal, Ocean, Truckload',NULL,'Chassis (CH); Cargo Van (CV); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Freedom 1, LLC','583627','FDLO','Drayage, Intermodal','08/01/2025','Chassis (CH); Cargo Van (CV)',NULL,NULL,NULL,'250,000','08/01/2025',NULL,NULL,NULL,NULL),
('Freedom Express Transportation LLC','1050515','FDXT','Drayage, Intermodal',NULL,'Chassis (CH); Cargo Van (CV); Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Freedom Transportation Services Inc','871319','FTPV','Drayage',NULL,NULL,'Bellflower','CA','Carrier','250,000','10/02/2020','0',NULL,'0',NULL),
('Freedom Transportation Services Inc','871319','FTPV','Drayage',NULL,NULL,'Bellflower','CA','Carrier',NULL,NULL,NULL,NULL,NULL,NULL),
('Freeman Bros Trucking LLC','366201','FBTG','Drayage, Intermodal, LTL',NULL,'Chassis (CH)','Bellflower','CA','Carrier','250,000','06/10/2021','0',NULL,'0',NULL),
('Freight Direct LLC','1256532','2414','LTL, Truckload',NULL,'Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Freight Here LLC','1474260','FUBA','Drayage, Intermodal, LTL, Rail',NULL,'TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Freight Horse Express LLC','794713','FHRC','Drayage',NULL,'Chassis (CH); Container (CN); TRACTOR (G4); Trailer (not otherwise specified) (TL)','Parlin','NJ','Carrier',NULL,NULL,NULL,NULL,NULL,NULL),
('Freight Intermodal','1054049','FING','Drayage, Intermodal','09/18/2020',NULL,'Oakland','CA','Carrier','100,000','09/18/2020','1,000,000','09/18/2020','1,000,000','09/18/2020'),
('Freight Line Inc','1121885','FSJA','Drayage, Intermodal',NULL,'Controlled Temperature Trailer (Reefer) (RT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Freight Line Trucking LLC','1088498','FLKG','Drayage, Intermodal, Rail, Truckload',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Freight Logistics Xpress LLC','1270193','FLXJ','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Freight Management LLC','092288','FMAE','Drayage','01/10/2020',NULL,'Gardena','CA','Carrier','250,000','03/08/2021','1,000,000','01/25/2020','1,000,000','01/10/2020'),
('Freight Service Inc','1444211','1246','Truckload',NULL,'(SV); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Freight United Inc','842973','FUIB','Drayage, LTL',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Freightmaster Usa LLC','633563','FMUS','Drayage, Intermodal, LTL, Rail',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Freightwell Logistics LLC','1478015','3367','Truckload',NULL,'Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Frenzies LLC','1195045','FZLA','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Friendos Freight Lines LLC','073561','FFNE','Air Freight, Cartage, Drayage, Intermodal, LTL, Ocean, Parcel, Rail, Truckload',NULL,'(SV); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Frierson & Sons Transport LLC','1335092','FSWB','Drayage, Intermodal, Rail',NULL,'Chassis (CH); Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Front & Center Services Inc','1050516','FCSI','LTL','03/01/2021',NULL,'Hampton','GA','Carrier','100,000','03/14/2021','1,000,000','03/01/2021','1,000,000','03/01/2021'),
('Front Door Delivery LLC','1262286','2376','Drayage, Intermodal',NULL,'Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Frosty G&C Transport LLC','0594716','2332','Truckload',NULL,'Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Fry Faith Transport LLC','582043','FRYN','Intermodal, Truckload',NULL,'Chassis (CH); TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Fti','1608647','FUGS','Drayage, Intermodal, Truckload',NULL,'Chassis (CH); Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Fti Transportation Corp','1352171','FTXJ','Drayage',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Fuchs Trucking LLC','539782','FUCH','Cartage, Truckload',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Full Circle Xpress, Inc.','467055','FCXV','Drayage, Intermodal, Rail',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('G A G Trucking LLC','1325095','1235','Drayage, Intermodal, Rail',NULL,'Chassis (CH); Container (CN); Double-Drop Trailer (DD); Controlled Temperature Trailer (Reefer) (RT); Single-Drop Trailer (SD); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('G Force Trucking','931224','2311','Drayage, Intermodal, LTL, Parcel',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('G R C Trucking Inc','899458','GRCB','Drayage, Intermodal, Ocean',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('G S Dhami LLC','013167','DGSF','Intermodal, LTL, Ocean, Rail',NULL,'Controlled Temperature Trailer (Reefer) (RT); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('G Source Transportation LLC','550928','GSUV','Drayage, Intermodal, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('G T H Transportation LLC','1431885','2437','Air Freight, LTL, Truckload',NULL,'LARGE STRAIGHT (G3);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('G T Logistics, Inc','562757','GLGM','Drayage',NULL,'(SV); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('G&H Warriors Trucking LLC','1286353','GHAO','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('G''s Logistics Solutions LLC','1498729','GSOG','Drayage',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('GOAL TRANSPORT','195-189-745','GOAR','Intermodal',NULL,'Chassis (CH); Container (CN); Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ga Dawg Transport LLC','1203335','GADR','Drayage, Intermodal',NULL,'Container (CN); Flat Bed Trailer (FT); Single-Drop Trailer (SD)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ga Express LLC','1203790','GXAS','Drayage, Intermodal, LTL, Rail',NULL,'Cargo Van (CV); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ga Transportation Inc','121461','1086','LTL',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Gadegbeku Logistics','1358792','GLOB','Intermodal',NULL,'TRACTOR (G4); Single-Drop Trailer (SD); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Galato.Llc','059634','GALW','Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Galaxia Xpress','054338','3855','Drayage',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Galaxy Connection LLC','0559838','1183','Drayage, Intermodal, Ocean, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Galindo Bros Trucking LLC','1272587','GBZK','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Gap Transportation LLC','1429966','2292','Drayage, LTL',NULL,'Cargo Van (CV); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Gar Trucking LLC','634337','GLRJ','Drayage',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Garj1 Transport, Inc.','932128','2417','LTL',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Garnet Transportation LLC','936991','1251','Drayage',NULL,'(SV); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Garza Transportation LLC','1107747','2264','Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Gato''s Trucking Corporation','1472791','2349','Drayage',NULL,'Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Gb Truxs Inc','1239138','GBXA','Drayage, Intermodal, LTL, Rail',NULL,'TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Gct','909600','GCYS','Cartage, Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Gd Express','831092','2412','Air Freight',NULL,'TRACTOR (G4); Trailer (not otherwise specified) (TL)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Gd Trans, Inc.','959415','GDAF','Drayage',NULL,'Chassis (CH); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Gdk Logistics Inc.','371013','GDKI','Drayage',NULL,'Container (CN); Cargo Van (CV); LARGE STRAIGHT (G3); TRACTOR (G4)','Fairfield','NJ','Carrier',NULL,NULL,NULL,NULL,NULL,NULL),
('Gdk Logistics Inc.','MC371013','1039',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Gdk Logistics Inc.',NULL,'1038',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Gds Logistics, Inc.','545201','NONE','Truckload',NULL,'Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Gdt Trans Inc','1104246','3690','Truckload',NULL,'Flat Bed Trailer (FT);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Gemini Services Transport LLC','1024611','GMNP','Drayage, Intermodal, LTL',NULL,'Container (CN); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Gemz Logistics LLC','079801','2367','LTL',NULL,'Controlled Temperature Trailer (Reefer) (RT);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Genesis Intermodal Services LLC','1098356','GEND','Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Genie Trucking LLC','835728','GENL','Intermodal',NULL,'Chassis (CH); Cargo Van (CV); Flat Bed Trailer (FT);  (SV); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Genki Transport Inc','1034507','GKIT','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Gentlemen Express LLC','1094619','OTR1','TL',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Gerson''s LLC Trucking','0530802','1018','Drayage','09/01/2020',NULL,'Norwalk','CA','Carrier','100,000','09/01/2021','0',NULL,'1,000,000','09/01/2020'),
('Get Intermodal Inc','519924','GETM','Intermodal',NULL,'Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Gettis Trucking LLC','1311078','GEJB','Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Gfc Trucking LLC','1571624','2568','Ocean',NULL,'Cargo Van (CV); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Gfm Logistics LLC','1210546','GFMS','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Gfm Trucking LLC','1294118','GFEG','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Gh Logistic Inc','817673','GHLI','Drayage, Intermodal, LTL','05/09/2021',NULL,'Tracy','CA','Carrier','100,000','05/09/2021','1,000,000','05/09/2021','100,000','05/09/2021'),
('Gh Transporter Inc','1439493','2302','Drayage',NULL,'Chassis (CH); Container (CN); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Gh Truckline Inc','1036377','GHNF','Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ghrindy LLC','1312927','GLWP','LTL, TL',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Gibraltar Trucking LLC','1145087','GRLV','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Gibson & Gibson Solutions LLC','1300078','1144','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Gibson & Sons Logistics Inc','1341112','GSZY','Drayage, LTL',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Gijima LLC','096372','GJMC','Drayage, Intermodal, Ocean, Rail',NULL,'Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Gil Transport Inc','674313','GILM','Drayage',NULL,NULL,'Turlock','CA','Carrier','100,000','08/12/2021',NULL,NULL,NULL,NULL),
('Gilbertson  Transport,   Inc.','285619','GISO','Intermodal','11/01/2020',NULL,'Vancouver','WA','Carrier','500,000','11/01/2020','1,000,000','11/01/2020','1,000,000','11/01/2020'),
('Gilco Trucking Company Agent Group Inc','721273','GTYQ','Drayage, Intermodal, LTL',NULL,'Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Gill Roadway Inc','1475031','GIMO','Drayage, Intermodal, Rail',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Gill Track Inc','1091738','GIMG','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Gindai Logistics LLC','1316541','GLDS','Drayage, Intermodal, Rail',NULL,'Cargo Van (CV); TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Gist Xpress','1198573','GXAT','Intermodal',NULL,'Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Glenda Jo''s Transportation LLC','1270733','1181','Drayage, Intermodal, LTL, Parcel, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Glez Freight Inc','1701010','GLIN','Drayage',NULL,'Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Glider Trucking Inc','1405612','GTWD','Intermodal',NULL,'Chassis (CH); Container (CN); Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Glo Logistics LLC','1271799','GOSM','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Global Freight Solutions, Inc.','479096','GFST','LTL',NULL,'Chassis (CH); Cargo Van (CV); TRACTOR (G4); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Global Jean LLC','1696106','3914','LTL',NULL,'LARGE STRAIGHT (G3)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Global K Logistics LLC','1430068','3994','Air Freight, Drayage, Intermodal',NULL,'(SV); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Global Solutions Planning, Inc.','137523','VEKA','Drayage','04/08/2021',NULL,'Gary','IN','Carrier','100,000','09/10/2021','1,000,000','04/08/2021','1,000,000','06/05/2021'),
('Global Transport Enterprise Inc','905504','GTEQ','Drayage',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Global Transporters Inc','725968','GBXO','Drayage, Intermodal, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Globe Logistics Inc','665442','GBLN','Intermodal, LTL',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Globe Trans LLC','945953','2554','Truckload',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Glova Link Corporation','502078','GLDI','LTL','08/10/2021',NULL,'Whittier','CA','Carrier','100,000','08/10/2021','1,000,000','08/10/2021','1,500,000','08/10/2021'),
('Gmd Logistics LLC','1447095','GMDK','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Gml Freight LLC','1038399','GMFE','Drayage, LTL',NULL,'Double-Drop Trailer (DD); Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Gn Trucking Inc','1430878','2305','LTL',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Gnn Logistics, Inc','970163','GNNG','Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Go Cargo LLC','1238343','GCGC','Drayage, Rail',NULL,'TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Go Freight Holdings Inc','036378','GFEF','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Go Get It Transportation LLC','1540816','GOIW','Drayage, Intermodal, Rail',NULL,'TRACTOR (G4); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Go Get It Trucking','816479','GGIG','Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Go Getter Trucking LLC','082433','GGKL','Intermodal',NULL,'Chassis (CH); Container (CN); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Go Go Express Inc','845609','GGEJ','Drayage',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Go Trucking Services Inc','722244','GOTH','Drayage, LTL','01/06/2021',NULL,'Pico Rivera','CA','Carrier','350,000','01/06/2021','1,000,000','02/06/2021','350,000','01/06/2021'),
('Go-Go Express LLC','1065264','GGEB','Drayage',NULL,'Chassis (CH); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Go-Yes Logistics Inc','1047651','GYAB','Drayage, Intermodal, Ocean, Rail',NULL,'Chassis (CH); Flat Bed Trailer (FT); Single-Drop Trailer (SD);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Goat Ryder Trucking LLC','1226709','GRYI','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('God Will Provide Inc','1349215','1254','Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Godel Trucking Inc','0496923','2352','Truckload',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Gold Link Transportation LLC','1252831','GQKP','Drayage',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Gold Medal Logistics Corp','1217369','GDGO','Drayage',NULL,'Chassis (CH); Container (CN); Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Gold Priority Transportation','554477','GTCD','Drayage',NULL,'Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Golden & Redmond Trucking Enterprise Inc','903180','GRTY','Drayage, Intermodal, Rail',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Golden Bear Express LLC','1274707','GBOW','Drayage, Intermodal, Rail',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Golden Gates Transportation Inc','1389447','GOQP',NULL,NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Golden King Transport Inc','1128677','GOQK','Cartage, Drayage, Intermodal, LTL, Ocean, Parcel, Rail',NULL,'Chassis (CH); Container (CN); Cargo Van (CV); Flat Bed Trailer (FT); SMALL STRAIGHT (G2); LARGE STRAIGHT (G3); TRACTOR (G4); Fixed-Rack, Flat-bed Trailer (RA); Controlled Temperature Trailer (Reefer) (RT);  (SV); Trailer (not otherwise specified) (TL); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Golden Logistics Inc','1118317','GDBS','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Golden State Carrier Inc','698898','2484','Truckload',NULL,'(SV); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Golden State Drayage Company','011571','GSDY','Drayage',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Golden State Freight','019138','GSHF','Drayage, Intermodal, Ocean, Rail',NULL,'Container (CN); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Goldy Trucking Inc','1264217','2564','LTL, Parcel, Truckload',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Goli Enterprises LLC','1136333','GOLY','Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Golovin Logistics LLC','1310295','1206',NULL,NULL,'Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Gomez Trucking Company LLC','1128080','1245','Drayage, Intermodal, Ocean',NULL,'TRACTOR (G4)',NULL,NULL,NULL,'0',NULL,'0',NULL,'0',NULL),
('Gony Trans Inc','1245504','2578','Drayage, Intermodal, LTL, Rail',NULL,'TRACTOR (G4); Trailer, Heater/Insulated/Vented (TA); Trailer, Dry Freight (TF); Trailer (not otherwise specified) (TL)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Gonzalez Carriers Inc','1062777','GZCI','Drayage',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Gonzalez Trans LLC','1169565','2298','Drayage, Intermodal, LTL, Ocean, Parcel, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Good Face Trucking LLC','1102107','GOUB','Drayage',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Good Hands Delivery Inc','1350693','GHDR','Drayage',NULL,'Chassis (CH); Container (CN); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Good Ship LLC','996324','GDHL','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Gooden-Gray Transportation LLC','1133682','GGTB','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Goodwin Trucking Group Inc','1019838','GTGG','Drayage',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Goodwin Trucking LLC','1331283','GOKO','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Gps Global Logistics Inc','1330383','2458','LTL',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
