('Rual Trucking Inc','628231','RUAL','LTL','09/11/2020',NULL,'El Paso','TX','Carrier','100,000','03/15/2021','1,000,000','09/11/2020','1,000,000','03/15/2021'),
('Rubalcado Trucking','1220728','1190','Drayage, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,'0',NULL,'0',NULL,'0',NULL),
('Rubber Meets Road, Inc.','977321','RMRB','Drayage',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Rubio''s Trucking Company Inc','618403','RBKI','LTL, Truckload',NULL,'Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Rudox Trucking LLC','836292','RUDG','Drayage, Intermodal, LTL',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ruff Riders Transportation LLC','1191293','1219','Drayage, Intermodal, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,'0',NULL,'0',NULL,'0',NULL),
('Rukele Transport LLC','1119760','2493','Cartage, LTL',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Runningback Express LLC','769892','1073',NULL,NULL,'Trailer, Insulated (TI); Trailer, Insulated/Ventilated (TM)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Runnit Express LLC','1134898','1237','Drayage, Truckload',NULL,'Flat Bed Trailer (FT); Controlled Temperature Trailer (Reefer) (RT);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Rush Transport LLC','006434','RSHN','Drayage, Intermodal, LTL, Ocean, Parcel, Rail',NULL,'Chassis (CH);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Russell E Spearman LLC','1004858','SZRH','Air Freight, Cartage, Drayage, Intermodal, Ocean, Rail',NULL,'Chassis (CH); Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Rw Logistics LLC','1118806','RWLI','Drayage, Intermodal, Truckload',NULL,'Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Rw Truck-lines Inc','1376965','NONE',NULL,NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ryan Surface Transportation LLC','1106476','RYHS','Drayage, Intermodal, LTL',NULL,'Chassis (CH); Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Rytal Trucking Inc','1284100','RYZI','Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('S  Line Transportation Inc.','451995','SLNY','Drayage, Intermodal',NULL,'Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('S & D Trucking Group, Inc.','457662','SDTT','Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('S & J Transportation Services, Inc.','261188','SJTS','Air Freight, Drayage, Intermodal, LTL, Rail, Truckload',NULL,'Chassis (CH); Flat Bed Trailer (FT); High Cube Van (HV);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('S And S Transportation LLC','010665','SAEV','Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('S I L Newline Express Inc','1139933','1049','Drayage, Intermodal, LTL',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('S&A Transportation Services LLC','1281691','SXYW','Drayage, Intermodal',NULL,'Chassis (CH); Container (CN); Cargo Van (CV); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('S&D Global Logistics','1022724','SDRS','Drayage, Intermodal',NULL,'Cargo Van (CV);  (SV); Trailer, Tank (Gas) (TG); Trailer, Tank (Food Grade-Liquid) (TK); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('S&M Transportation Inc','825306','SMAY','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('S&Mc Trucking LLC','1239500','SXOM','Drayage, Intermodal, LTL',NULL,'Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('S&N Transportation LLC','1201805','1173','Drayage',NULL,'Trailer (not otherwise specified) (TL)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('S-Town Transportation Inc','1443249','STPV','Drayage, Intermodal, LTL, Ocean, Rail',NULL,'Chassis (CH); Cargo Van (CV); TRACTOR (G4);  (SV); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('S.Prather Transportation LLC','1160246','PSQW','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('S2 Transport LLC','026322','STTK','Drayage, Intermodal, LTL, Parcel, Rail',NULL,'Chassis (CH); Flat Bed Trailer (FT); Controlled Temperature Trailer (Reefer) (RT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('S2 Way Trucking Inc','1329549','SOUT','Air Freight, Drayage, Intermodal, Ocean, Rail',NULL,'Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('SCHNEIDER NATIONAL, INC',NULL,'SNLU','Drayage, Intermodal',NULL,NULL,'GREENBAY','WI','Carrier','5,000',NULL,'0',NULL,'1,000,000',NULL),
('SNNPR Trucking','1453075','3125',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Saaja Trucking & Transportation','1038821','SJAR','Air Freight, Drayage, Intermodal, LTL, Ocean, Rail, Truckload',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Saba Trucking LLC','1050837','SLZD','Cartage, Drayage, Intermodal, LTL, Ocean, Parcel, Rail',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Sachkhand Express Inc','1201240','2473','LTL',NULL,'Cargo Van (CV); TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Saenz Logistics Inc','1196047','SAEB','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Safari Intermodal, LLC','883995','SFRF','Drayage, Intermodal, LTL, Ocean, Parcel, Rail',NULL,'Chassis (CH); Container (CN); Double-Drop Trailer (DD);  (SV); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Safe And Sound Logistics LLC','1194958','SQYS','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Safe Hands Transportation Inc','1130195','2443','Cartage, Drayage',NULL,'Cargo Van (CV);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Safe Road Transport Inc','1370848','NONE','LTL, Truckload',NULL,'(SV); Trailer, Dry Freight (TF); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Safe Way Freight Inc','0523328','2444','Drayage',NULL,'Cargo Van (CV); Flat Bed Trailer (FT); Trailer, Dry Freight (TF); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Safeland Transportation LLC','1191579','STDH','Drayage, Intermodal',NULL,'Chassis (CH); Container (CN); Cargo Van (CV); TRACTOR (G4); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Safer Trucking Inc','1056896','1137',NULL,NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Safeside Trucking Inc','1200053','SFDE','Drayage, Intermodal, LTL, Ocean, Parcel, Rail',NULL,'Chassis (CH); Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Safeway Transportation Co.,  Inc.','289699','SFYA','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Safiatou Transport LLC','1181057','SFUY','Drayage, Intermodal, LTL',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Sagal Transport Inc','1128551','STWE','Air Freight, Cartage, Drayage, Intermodal, Ocean, Parcel, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Saini Trucking Inc','1133019','2363','LTL, Truckload',NULL,'Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Sal Jimenez Jr Trucking','888187','2418','LTL',NULL,'Chassis (CH); Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Salas Swift Trucking','1215456','2445','Truckload',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Salson Logistics, Inc.','327035','SLOJ','Drayage, Intermodal, LTL','04/14/2020',NULL,'Newark','NJ','Carrier','500,000','11/14/2020','1,000,000','11/14/2020','1,000,000','04/14/2020'),
('Sam Fam Trucking LLC','1223421','SZQO','Drayage',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Sam Trucking LLC','891740','SAUG','Intermodal',NULL,'Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Samra Express Inc','340615','SXSI','Drayage, LTL',NULL,'(SV); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Samurai Transportation Inc','826883','1260','Drayage, LTL, Truckload',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Sand Dust Trucking LLC','1042347','SDGG','Drayage',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Sandeep Transit Inc','1408516','2341','LTL',NULL,'(SV); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Sanders Deland Transporting','1585009','QANP','Ocean',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Sandhu Transportation LLC','637997','2555','Air Freight',NULL,'TRACTOR (G4); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Sandino Freight Services','1426527','SORN','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,'0',NULL,'0',NULL,'0',NULL),
('Sandra''s Son Trucking LLC','1279507','SORO','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Savannah Cartage, Inc.','402144','SGEA','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Savannah Trading','1563385','SBHM','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Saviours Trucking LLC','1133305','SVRQ','Drayage, Intermodal, LTL',NULL,'Chassis (CH); TRACTOR (G4);  (SV); Trailer (not otherwise specified) (TL)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Sc Traders LLC','1718326','UANT','Drayage',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Sc Truck Lines LLC','046739','SCYY','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Schab Logistics LLC','1397051','SCFW','Drayage, Intermodal, Rail',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Schafer Bros. Transfer & Piano Movers, Inc.','185162','WSIC','Drayage, LTL, Truckload',NULL,'Chassis (CH); Container (CN); Cargo Van (CV); Flat Bed Trailer (FT);  (SV); Trailer, Dry Freight (TF); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Schmuhl Brothers, Inc.','312139','SMUH','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Schofield Transport & Logistics, LLC','026385','SDPQ','Drayage, Intermodal, LTL, Rail',NULL,'Chassis (CH); Cargo Van (CV); LARGE STRAIGHT (G3); TRACTOR (G4); High Cube Van (HV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Scm Intermodal, Inc.','112979','SCQW','Drayage, Rail, Truckload',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Scorpio Trucking','784908','SPKG','Drayage, Intermodal, LTL, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Scorpion Express','1085952','SXJR','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Scorpion Transportation LLC','1413273','STEV','Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Scs Drayage LLC','1047525','SGAT','Drayage',NULL,'Chassis (CH); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Sda Cargo','1106956','1056','TL',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Sdmj Trucking LLC','1311173','SDBW','Drayage, LTL',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Seaport Intermodal Inc','041127','SIDO','Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Seaport Trucking Services Inc','836375','SEAB','Drayage, Intermodal',NULL,'Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Seattle Intermodal LLC','935700','SMDW','Drayage, Intermodal, Ocean, Rail',NULL,'Chassis (CH); Flat Bed Trailer (FT); Controlled Temperature Trailer (Reefer) (RT); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Seattle Premium Logistics','929075','SLPY','Drayage, Intermodal','09/23/2020','Chassis (CH); TRACTOR (G4)','Seattle','WA','Carrier','100,000','09/23/2020','1,000,000','09/23/2020','100,000','09/23/2020'),
('Sega Motors Inc','113019','2408',NULL,NULL,'Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Sega Trucking LLC','091210','SGFD','Drayage, Ocean',NULL,'Chassis (CH); Cargo Van (CV); TRACTOR (G4);  (SV); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Self Made Logistics LLC','1282267','1174','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Selfmade Freight Logistics Inc','1381529','SFET','Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Semi Legal Addiction, Inc.','213263','SLGA','Drayage',NULL,'Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Semistar Trucks LLC','1351182','2364','LTL',NULL,'Flat Bed Trailer (FT);  (SV); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Sentake Transport LLC','1220374','1149','Drayage, Intermodal, LTL, Rail',NULL,'TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Sepulveda Logistics Inc','1061590','1050','Drayage, Intermodal, LTL',NULL,'Container (CN); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Serenity''s Transport LLC','1349575','SYSM','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Serv Transport, LLC','097497','SYJO','Drayage, Intermodal, Truckload',NULL,'Chassis (CH); Container (CN); TRACTOR (G4); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Service Transfer, Inc.','135652','SVTF','Drayage, Intermodal, Rail',NULL,'Chassis (CH); Cargo Van (CV); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Settemari Trucking','1164444','1099','Drayage, Intermodal',NULL,'Chassis (CH); Container (CN); Cargo Van (CV); SMALL STRAIGHT (G2); TRACTOR (G4); Single-Drop Trailer (SD); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Sfe, Inc.','505101','SFXP','Drayage, Intermodal',NULL,'Chassis (CH); Cargo Van (CV); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Sg Transportation Inc','752048','SGZN','Truckload',NULL,'Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Shahen Inc','972739','SHVQ','Drayage, Intermodal, LTL',NULL,'TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Shark Trucking, Inc.','269507','SHBD','Drayage, Intermodal',NULL,'Chassis (CH); Flat Bed Trailer (FT); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Sharks Trucking Inc','1428187','2268','Drayage, Intermodal, LTL',NULL,'Cargo Van (CV); SMALL STRAIGHT (G2);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Shayona World Transport Corp','1264318','SWMO','Drayage, Intermodal, Rail',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Sheldon Rivers, LLC','621395','SIVY','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4); Trailer (not otherwise specified) (TL)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Shell Transportation System LLC','1193734','SJHM','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Shell''s Transportation LLC','983047','SPLR','Drayage, Intermodal, LTL, Ocean',NULL,'Container (CN); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Shift Trucking Inc','0527593','SHFT','Drayage','07/18/2021',NULL,'WHITTIER','CA','Carrier','100,000','07/18/2021','0',NULL,'1,000,000','07/18/2021'),
('Shippers Intermodal Services Inc','1111497','SRMA','Drayage',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Shippers Preferred Express Inc.','473382','SPPV','LTL, Truckload',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Shoreline Enterprises  Inc','1682463','3146','Drayage, Intermodal, Rail',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Shorty''s Towing LLC','1637762','3672','Drayage, Intermodal, LTL, Ocean, Rail',NULL,'Chassis (CH); Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Sia Transport LLC','731771','SIAK','Drayage, Intermodal',NULL,'Chassis (CH);  (SV); Trailer, Bulk (TB); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Sidhu Logistics Inc','658869','SDUC','Intermodal',NULL,'TRACTOR (G4);  (SV); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Sidney Trucking','1005645','1165','Drayage, Intermodal',NULL,'Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Sierra Distribution Services Inc','1579925','2571','Air Freight, Cartage, Drayage, Intermodal, LTL, Ocean, Rail, Truckload',NULL,'TRACTOR (G4); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Sierra Transport LLC','941847','4034','Drayage',NULL,'Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Silver Point Trucking, Inc.','456013','SVPK','Drayage','12/08/2020',NULL,'Rancho Dominguez','CA','Carrier','100,000','12/08/2020','1,000,000','12/08/2020','1,000,000','12/08/2020'),
('Silver Transport LLC','1258161','1227','LTL, Truckload',NULL,'Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Silwady Express Trucking','1272620','SEQO','Cartage, Drayage, Intermodal, Rail',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Simart Transportation Inc.','981845','1009','Drayage',NULL,NULL,'Van Nuys','CA','Carrier','100,000','06/20/2021',NULL,NULL,NULL,NULL),
('Simi Valley Carriers Corp','1203934','1108','TL',NULL,'Controlled Temperature Trailer (Reefer) (RT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Simone Transportation LLC','1236736','SKQH','Drayage, Intermodal, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Simple Freight LLC','1359010','SFYV','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Sims Queen Bee Transportation LLC','1006530','SQBP','Drayage, Intermodal, LTL, Rail, Truckload',NULL,'Flat Bed Trailer (FT);  (SV); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Sin-Ley Transport','1366704','2455','Drayage',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Sinaia Logistics LLC','1326455','SIPN','Drayage, Intermodal, Rail',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Singh Bros','989694','SIHB','Drayage, Intermodal, Ocean',NULL,'Cargo Van (CV); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Singh Trucklines','865760','SIYG','Drayage, Intermodal','05/06/2021',NULL,'Kent','WA','Carrier','250,000','05/06/2021','1,000,000','05/06/2021','1,000,000','05/06/2021'),
('Singleton Transport LLC','1144323','SQNM','Drayage',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Sivar Express Transport','1537936','QIWD','Drayage, Intermodal, Rail',NULL,'Chassis (CH); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Six-figures Transportations LLC','1302379','SXSY','Drayage, Intermodal, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Sixpacklogistics LLC','1302357','SPZW','Drayage, Intermodal, LTL',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Sjd Trucking, LLC','1293219','SJRP','Drayage, Intermodal, Ocean, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Skilled Transport LLC','1342241','SKIH','Drayage, Intermodal, LTL, Truckload',NULL,'Chassis (CH); SMALL STRAIGHT (G2); TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Skl','1319820','SKBD','Drayage, Intermodal, Rail',NULL,'Chassis (CH); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Sky Harbor Trucking LLC','696286','SKHB','Drayage',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Sky Logistics LLC','839682','SKOQ','Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Skyline Express','253470','SXNB','Drayage','08/01/2021',NULL,'Chicago Ridge','IL','Carrier','250,000','08/01/2021','1,000,000','08/01/2021','1,000,000','08/01/2021'),
('Skyline Trucking Group Inc','1348217','NONE','LTL',NULL,'Cargo Van (CV); SMALL STRAIGHT (G2); Trailer, Dry Freight (TF); Trailer, Pneumatic (TP); Truck, Van (TV); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Skyline Trucking Inc','1263769','4035','LTL',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Skywheels Inc','1110432','SKWI','Drayage, Intermodal',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Skyworth Logistics Inc','093918','SYWD','Drayage',NULL,'Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Skyyway Transport And Logistics LLC','1229406','SQXB','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Sl Logistics','1025332','1171','Drayage',NULL,'Chassis (CH); Container (CN); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Slana X Corp','938288','SXCB','Intermodal',NULL,'Chassis (CH); Cargo Van (CV); Flat Bed Trailer (FT); Controlled Temperature Trailer (Reefer) (RT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Slr Industries LLC','088628','SIUD','Intermodal',NULL,'Chassis (CH); Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Sma Trucking Inc','1090573','2397','LTL',NULL,'Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Smart Freight Services','1601058','SMEA','Drayage, Intermodal, Ocean, Rail',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Smart Trucking LLC','1146232','SMRV','Drayage, Intermodal',NULL,'Chassis (CH); Cargo Van (CV); TRACTOR (G4); Open Top Van (OV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Smartway Trucking LLC','965487','SWDK','Drayage, Intermodal, LTL',NULL,'TRACTOR (G4); Trailer, Insulated/Ventilated (TM)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Smd Trucking Corp','1093033','SUXJ','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Smith Express Inc','868860','SERM','Air Freight, LTL, Parcel, Truckload',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Smitty Inc LLC','096366','SMDY','Drayage, LTL',NULL,'Chassis (CH);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Smj Transport LLC','662573','SJRA','Drayage, Intermodal','06/30/2020','Trailer (not otherwise specified) (TL)','Paramount','CA','Carrier','100,000','11/12/2020',NULL,NULL,'1,000,000','06/30/2020'),
('Smjohnson LLC','1346946','SMUI','Drayage, Intermodal, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Snnpr Trucking LLC','1453074','3124','Drayage, Intermodal, Ocean, Rail',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Snp Transport LLC','1212618','SNIP','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Snwshippingcompany LLC','1618082','3711','Drayage, Ocean',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('So Cal Drayage','109247','SOYB','Drayage',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Socal Xpress','1164632','1059','Drayage, Intermodal, LTL, Rail',NULL,'Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Sodo Logistics LLC','016955','SOOW','Drayage, Intermodal',NULL,'Chassis (CH); Container (CN); Flat Bed Trailer (FT); TRACTOR (G4); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Sohi Transport Inc.','587583','SOSQ','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Soku Logistics LLC','1353318','SKHQ','Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Sol Trucking Inc.','1026198','SOCT','Drayage, Intermodal','06/27/2021',NULL,'Portland','OR','Carrier','250,000','06/27/2021','1,000,000','06/27/2021','1,000,000','06/27/2021'),
('Soliana Logistics LLC','1669757','UAFJ','Drayage, Intermodal, Rail',NULL,'Chassis (CH); Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Soliman And Son Transport Inc','1281301','SNXM','Drayage, Intermodal, LTL',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Solo Express LLC','1221161','SOLW','Drayage, Intermodal, Ocean, Rail',NULL,'Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
ON CONFLICT (scac) DO NOTHING;

INSERT INTO mg_carriers (name,mc_number,scac,modes,early_ins_exp,equipment,loc_city,loc_state,loc_type,cargo_ins_amt,cargo_ins_exp,general_ins_amt,general_ins_exp,liability_ins_amt,liability_ins_exp) VALUES
('Solorio Trucking','931211','2433',NULL,NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Solvent Logistics Incorporated','1038504','SQVG','Drayage',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Sopac Southern Pacific Logistics Inc','977866','SSPY','Drayage',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Sophia Transport Inc','1361384','SOYW','LTL',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Sotelo Trucking','1337604','2409','Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Souder''s Legacy Iii Inc','1181417','SGYO','Drayage, Intermodal, LTL, Rail',NULL,'Flat Bed Trailer (FT); Trailer (not otherwise specified) (TL)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Sound Intermodal LLC','923999','SDML','Drayage, Intermodal',NULL,NULL,'Seattle','WA','Carrier','250,000','12/15/2020','1,000,000',NULL,'10,000,000',NULL),
('South Bay Drayage Inc','1233596','SBYB','Drayage, LTL',NULL,'Chassis (CH); Cargo Van (CV); TRACTOR (G4); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('South East Transport Inc','1087001','SEQS','Drayage, Intermodal, Ocean, Rail',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('South Star Express LLC','1083312','3409','Drayage',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Southern California Transportation LLC','1112937','SOQR','Drayage, Intermodal, LTL, Rail',NULL,'Chassis (CH); Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Southern Cartage','1536095','SOWV','Cartage, Drayage',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Southern Cartage, Inc.','140713','SOCE','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Southern Express LLC','1023054','2263','LTL',NULL,'Cargo Van (CV); TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Southern Freight Transport Inc','869487','SFQY','Drayage',NULL,'Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Southern Intermodal Drayage Services Inc','444013','SUDE','Drayage',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Southern Intermodal Xpress','593622','SIXP','Drayage',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Southern Linx Logistics LLC','1109036','SRXG','Drayage, Intermodal, Rail',NULL,'TRACTOR (G4); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Southern Pride Logistics LLC','401715','SDZJ','Truckload',NULL,'Flat Bed Trailer (FT);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Southside Transport Inc','929718','3629','LTL',NULL,'(SV); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Southwest Freight, Inc','151053','SOUW','Drayage, Intermodal, LTL, Rail',NULL,'Chassis (CH); Flat Bed Trailer (FT); LARGE STRAIGHT (G3); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Sp Logistics LLC','1210481','SPND','Drayage, Intermodal, LTL, Rail',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Speed Freight Inc.','919219','SFHS','Drayage','10/01/2020',NULL,'Bensenville','IL','Carrier','250,000','10/01/2020','1,000,000','10/01/2020','1,000,000','10/01/2020'),
('Speed Roadking Inc','1585258','SQPR','Drayage, Intermodal, LTL, Truckload',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Speedy Transportation LLC','817477','2511','Truckload',NULL,'TRACTOR (G4); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Speedymac Transportation LLC','1131651','SQYW','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Spence Trucking Inc','1142810','1093','Drayage',NULL,'Cargo Van (CV); Trailer, Dry Freight (TF); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Spg Transportation Inc','966872','SPGT','Drayage','05/20/2021',NULL,'Moreno Valley','CA','Carrier','250,000','10/27/2020',NULL,NULL,'1,000,000','05/20/2021'),
('Spirit Cargo Inc','1471831','SIJR','Drayage, Intermodal',NULL,'TRACTOR (G4); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Splendid Trucking LLC','1170853','SDRI','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Sr Trans Inc','1187868','2272','Truckload',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Srg Freight Lines Inc','976809','SRGF','Drayage','08/01/2020',NULL,'Gainesville','GA','Carrier','100,000','08/01/2021','100,000','08/15/2020','1,000,000','08/01/2020'),
('Srt Gzilla Trucking LLC','1400852','2294','Drayage',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ss Trucking','522107','SSRN','Drayage, Intermodal, Ocean, Rail',NULL,'Chassis (CH); Cargo Van (CV); Flat Bed Trailer (FT); TRACTOR (G4); High Cube Van (HV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ssm Transportation LLC','091753','2441','Truckload',NULL,'Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Stagecoach Cartage And Distribution, LLC','196747','VMGM','Drayage',NULL,'TRACTOR (G4); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Stallion Trucking Group LLC','1164401','SAAJ','Drayage, Intermodal, Ocean',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Stan Brown Trucking LLC','1083190','BQNK','Drayage, Intermodal, LTL, Truckload',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Stanley And Family Trucking Company','1081906','2548','Intermodal, LTL',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Star Accurate Intermodal Inc','021973','SCCM','Drayage, Intermodal',NULL,'Chassis (CH); Cargo Van (CV); TRACTOR (G4); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Star K Transportation Inc','570912','SKFS','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Star Transportation Pa Inc','542845','STAR','Drayage','05/21/2020',NULL,'Miami Gardens','FL','Carrier','250,000','05/16/2021','1,000,000','05/21/2020','1,000,000','05/21/2020'),
('Stark Trucklines Inc','1373350','1210','Drayage, LTL',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('State 2 State Trucking LLC','948056','STWI','Intermodal',NULL,'TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Steady Hauling Xpress','1384398','2505','Drayage',NULL,'Chassis (CH); Container (CN); Cargo Van (CV); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Steady Transportation LLC','748814','STYC','Intermodal, LTL',NULL,'Chassis (CH); TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Steel City Transport','1293864','SC','Drayage, LTL, Truckload',NULL,'Cargo Van (CV); SMALL STRAIGHT (G2);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Steel Line Transport','739497','SLXJ','Drayage, Intermodal, LTL',NULL,'Flat Bed Trailer (FT); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Step Trucking Inc','885341','STEP','Drayage','10/31/2020',NULL,'Arlington Heights','IL','Carrier','250,000','03/01/2021','1,000,000','03/01/2021','1,000,000','10/31/2020'),
('Sterling Transportation Inc','1075157','STGO','Drayage, LTL, TL','04/01/2022','Flat Bed Trailer (FT)',NULL,NULL,NULL,'250,000','04/01/2022',NULL,NULL,NULL,NULL),
('Steven Transport LLC','1461789','SUSI','Drayage, Intermodal',NULL,'Chassis (CH); Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Stewart Transportation Co. Inc.','236214','CMWS','Parcel',NULL,'(SV); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Sti Transportation Inc','849224','2538','Truckload',NULL,'Double-Drop Trailer (DD)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Stinger Trucking','933670','SIKR','Drayage','04/01/2021',NULL,'Anaheim','CA','Carrier','100,000','04/01/2021','1,000,000','04/01/2021','1,000,000','04/01/2021'),
('Stone Transportation','758385','SONT','Drayage','01/31/2021',NULL,'Norco','CA','Carrier','100,000','02/28/2021','1,000,000','01/31/2021','100,000','01/31/2021'),
('Stpw Inc','002126','STPB','Drayage, Intermodal','03/23/2020',NULL,'Maywood','CA','Carrier','100,000','03/23/2021','1,000,000','03/23/2020','100,000','03/23/2020'),
('Stradford Transportation LLC','606361','1120','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Stream Links Express Inc','666428','SLXB','Air Freight, Drayage, Intermodal, LTL, Rail, Truckload',NULL,'Chassis (CH); Double-Drop Trailer (DD); Flat Bed Trailer (FT); TRACTOR (G4); Fixed-Rack, Single Drop Trailer (RS); Single-Drop Trailer (SD); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Streamline Transportation','773009','SIOM','LTL, Parcel',NULL,'Cargo Van (CV);  (SV); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Strength Transport LLC','1397397','SRIV','Drayage, Intermodal, Rail',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Strong Trucking','979674','STZS','Intermodal',NULL,'Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Strtr Logistics LLC','1075331','SLLM','Drayage, Intermodal',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Sts Trucking Inc','1386525','NONE',NULL,NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Stuff In-transit LLC','1086388','STUFF','Drayage','02/13/2021',NULL,'Clemmons','NC','Carrier','100,000','02/13/2021','1,000,000','02/13/2021','1,000,000','02/13/2021'),
('Stukey Transportation LLC','1479803','TKJG','LTL',NULL,'TRACTOR (G4);  (SV); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Sultan Trans Inc','811111','1054','TL',NULL,'Trailer (not otherwise specified) (TL)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Sumair Transportation Inc','1593546','SUOP','Drayage, Intermodal, Rail',NULL,'Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Summa Logistics Corporation','1105422','SMLK','Drayage',NULL,'Chassis (CH); Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Summers Worth Transit LLC','1313631','SWQG','Intermodal',NULL,'Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Summit Transportation LLC','1003072','2389','Drayage',NULL,'(SV); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Sun Pacific Trucking','322149','SVZM','Drayage, Intermodal, Rail',NULL,'Chassis (CH); Flat Bed Trailer (FT); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Sunbelt Drayage','1496015','3164','Drayage',NULL,'Chassis (CH); Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Sunhing Logistics Inc','1349703','SGTR','Drayage',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Sunlit Us Transportation Inc','1528596','TJQN','Drayage, Intermodal, LTL',NULL,'Chassis (CH); TRACTOR (G4); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Sunny 91748 Inc','1243743','3749','LTL, Truckload',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Sunny Trucking LLC','850517','SNYK','Drayage, LTL, Ocean, Rail',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Sunrise Express Inc','1310949','2501','Truckload',NULL,'Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Sunshine Shipping LLC','999730','SSGZ','Drayage',NULL,'Chassis (CH); Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Super Star Freight Inc','1047471','SSRT','Drayage, Intermodal, LTL, Rail',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Superb Transport LLC','863062','SUBK','Drayage, Intermodal',NULL,'TRACTOR (G4); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Superior Drayage LLC','1496400','2411','Intermodal',NULL,'Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Superior Transportation Inc','1141236','SZPK','LTL',NULL,'Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Supply Chain Systems',NULL,'1062','Drayage, Intermodal, LTL, TL',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Supra National Express',NULL,'1006',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Supra National Express Inc','888409','SNEA','Drayage, Transload, Warehouse',NULL,NULL,'Wilmington','CA','Carrier','250,000','10/28/2020','0',NULL,'0',NULL),
('Supreme Team Co','1037109','1078','Drayage, LTL, Ocean, TL',NULL,'(SV); Trailer, Tank (Gas) (TG)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Suraj Enterprises LLC','093096','SJET',NULL,NULL,'Flat Bed Trailer (FT); TRACTOR (G4); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Sure Shot Transit Solutions LLC','137968','SUBG','Drayage, Intermodal, LTL, Rail, Truckload',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Suteco Trans Corp','943470','SUTN','Drayage, Intermodal','01/08/2021',NULL,'Kansas City','KS','Carrier','100,000','01/08/2021','1,000,000','01/08/2021','1,000,000','01/08/2021'),
('Suteco Transport, LLC','267908','SUTP','Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Sutton Global LLC','1112279','SJZG','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Swinton Transport LLC','916902','STHV','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Swish Trucking LLC','1305033','SWUD','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('System Rider Express Inc','1127090','2407','Air Freight, Truckload',NULL,'Truck, Van (TV); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('T & C Trucking LLC','124955','TCQK','Drayage',NULL,'Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('T & W Legacy LLC','1009680','TWLN','Drayage, Intermodal',NULL,'TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('T A G Logistics, LLC','1569535','2565','Drayage, Intermodal, LTL',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('T Great Transportation LLC','1394725','2471','LTL, Truckload',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('T N T Transportation Inc LLC','1025940','TOJO','Drayage, Intermodal, Ocean',NULL,'TRACTOR (G4); Trailer, Insulated (TI)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('T Walk Transport LLC','1285822','TWWW','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('T&D Touchdown Transportation LLC','1333935','TDKW','Drayage, Intermodal',NULL,'Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('T&J Contracting Services LLC','1308598','TJFV','Drayage, Intermodal, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('T&P Partners Inc','1345397','2270','Air Freight, LTL',NULL,'Trailer, Dry Freight (TF); Truck, Van (TV); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('T-Rex Transportation, Inc.','509333','TRXQ','Drayage',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('T. G. S. Transportation, Inc.','190230','TGSM','Drayage',NULL,NULL,'Fresno','CA','Carrier','300,000','02/09/2021',NULL,NULL,NULL,NULL),
('T. G. S. Transportation, Inc.',NULL,'1027',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('TEST',NULL,'CANC',NULL,'04/05/2021',NULL,NULL,NULL,NULL,'500,000','04/05/2021','0',NULL,'0',NULL),
('TEST2',NULL,'1002','TL',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Tabares Transport LLC','1435194','2313','Drayage, Intermodal, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Tangos Transportation LLC','646172','TGON','Drayage, Intermodal',NULL,'Chassis (CH); Flat Bed Trailer (FT); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Taomore Supply Chain Ltd','1153641','TSON','Drayage',NULL,'Chassis (CH); Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Tatum Trucking LLC','1027175','TUMH','Drayage, Intermodal, Ocean',NULL,'Chassis (CH); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Taz Trucking LLC','588965','TAZK','Intermodal',NULL,'LARGE STRAIGHT (G3); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Tbe Hauling LLC','1295394','TBEY','Drayage, Intermodal, LTL, Ocean, Rail, Truckload',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Tbt Express Inc','1116144','2551','Air Freight, Cartage, Drayage, Intermodal, LTL, Ocean, Parcel, Rail, Truckload',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Tc Carriers LLC','1660589','3025','Truckload',NULL,'Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Tcb Hauling LLC','058110','TCBF','Drayage, Intermodal, LTL, Rail, Truckload',NULL,'TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Tcg Logistics LLC','112459','TQUO','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4); Trailer, Dry Freight (TF); Trailer, Pneumatic (TP)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Tcw, Inc.','140539','TCWI','Drayage, Intermodal, LTL, Ocean',NULL,'Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Tdk Transportation LLC','1016619','TDKS','Air Freight, Drayage, Intermodal, LTL, Ocean, Parcel, Rail, Truckload',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Team Tag Trucking LLC','1302027','TEJE','Intermodal',NULL,'Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Teamway Trucking LLC','1177922','TUDA','Drayage',NULL,'Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Teasley Transportation, LLC','1175712','TEQA','Drayage, Intermodal, LTL',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Tee Trucking Inc','1277487','FCXV','Air Freight, Cartage, Drayage, Intermodal, Ocean, Rail',NULL,'Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ten 4 Transport','1103742','TEFV','Drayage, Intermodal, LTL',NULL,'Chassis (CH); TRACTOR (G4); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Teocal Transport, Inc.','405917','TEOC','Truckload',NULL,'Double-Drop Trailer (DD); Flat Bed Trailer (FT); High Cube Van (HV); Fixed-Rack, Double Drop Trailer (RD); Controlled Temperature Trailer (Reefer) (RT);  (SV); Trailer (not otherwise specified) (TL)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Termin8ors LLC','1031025','TINS','Drayage, Intermodal, LTL, Ocean, Rail, Truckload',NULL,'Chassis (CH); Cargo Van (CV); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Terminal Transportation Services','153790','TRMQ','Drayage, Intermodal, Truckload',NULL,'Chassis (CH); Flat Bed Trailer (FT); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Terminel LLC','782236','TMNL','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Terraform Transport','1129715','TFMR','Drayage, Intermodal, Rail',NULL,'Chassis (CH); Flat Bed Trailer (FT); High Cube Van (HV); Fixed-Rack, Flat-bed Trailer (RA)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Test',NULL,'1000',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Texas Roadway','992410','TXAR','Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Teyrachi Logistics LLC','1260630','TLLB','Drayage, Intermodal',NULL,'Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Tf Major Movers LLC','1309313','TMJF','Drayage, Intermodal, Ocean, Rail',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Tg Express, LLC','069674','2424','Intermodal',NULL,'(SV); Trailer, Dry Freight (TF); Trailer, Tank (Gas) (TG); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Tg Trucking, LLC','1171674','3286','Drayage, Intermodal, LTL, Truckload',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Tgz Freight LLC','1169746','TGZT','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Thach Star Transportation Inc','807227','3471','LTL, Truckload',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Thakur Trans Inc','1038290','2467','Truckload',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('The Best Choice Freight Inc','1539636','TBOP','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('The Blessing Logistics LLC','1204442','2477','Drayage, Intermodal',NULL,'Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('The Furious','1211111','FURT','Drayage',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('The Golden Standard Inc','1114760','3716','Rail',NULL,'Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('The Jam Xpress LLC','1358135','JXLH','Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('The Josiah Co., LLC','122925','JSHC','Intermodal',NULL,'Chassis (CH); TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('The Movement LLC','1121632','MVMY','Drayage, Intermodal, LTL, Ocean, Rail',NULL,'Chassis (CH);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('The North Truck LLC','153702','NHKT','Drayage, Intermodal, Ocean, Rail',NULL,'Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('The One Hauling Inc','991253','OHIT','Drayage, Intermodal, LTL, Rail',NULL,'Chassis (CH); Cargo Van (CV); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('The Road Runner King Transport Inc','1009937','RRKA','Drayage, Intermodal, Parcel',NULL,'Chassis (CH); Trailer (not otherwise specified) (TL)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('The Scared Cat Truck Line Corp','035941','NONE','Intermodal',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('The Transporter, Inc.','218060','TNPR','Drayage',NULL,'Chassis (CH); Flat Bed Trailer (FT);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('The Wolfs Trucking','829362','WTTE','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('There She Goes Transportation L.L.C.','1165132','3468','LTL, Truckload',NULL,'SMALL STRAIGHT (G2); LARGE STRAIGHT (G3); TRACTOR (G4); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Thiara Truckline Inc.','074364','1031','LTL',NULL,NULL,'Bakersfield','CA','Carrier','100,000','06/07/2021',NULL,NULL,NULL,NULL),
('Thiara Truckline Inc.',NULL,'1030',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Thiara Truckline Inc.',NULL,'1028',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Thika Enterprises LLC','1135262','TKEH','LTL',NULL,'SMALL STRAIGHT (G2); LARGE STRAIGHT (G3)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Third Coast Cartage, LLC','1380606','TCCC','Drayage, Intermodal, Rail',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Thomas & Company Trucking LLC','1364905','2508','LTL',NULL,'LARGE STRAIGHT (G3)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Thomas Cameron Trucking Inc','919577','CMYQ','Truckload',NULL,'TRACTOR (G4); Controlled Temperature Trailer (Reefer) (RT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Thomas Family Logistics LLC','1327459','TFBQ','Drayage, Intermodal, Ocean, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Thomas Logistics Concepts LLC','1255583','1192','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Thompson Hauling LLC','1093988','THLP','Drayage, Intermodal, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Three M Transport Service LLC','1288491','2862','Intermodal',NULL,'Container (CN); Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Tiger Freight Services Inc','1023534','TFVV','LTL',NULL,'Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Tiger Logistics Inc','697396','TLQF','Drayage, Ocean, Parcel, Rail',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Tiger Trucking LLC','473673','TZGI','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Tigerhawk Logistics','1428985','THAC','Drayage',NULL,'Chassis (CH); Container (CN)',NULL,NULL,NULL,'0',NULL,'0',NULL,'0',NULL),
('Tigran Indjarabian Trck Inc','378372','IJTG','Drayage',NULL,'TRACTOR (G4);  (SV); Trailer, Dry Freight (TF); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Time Dispatch Services Agent Group Inc','721269','TDSN','Drayage',NULL,'Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Time Traveller Transportation LLC','1078490','1249','Drayage, Intermodal, LTL, Rail',NULL,'Chassis (CH); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Timeless Trans Inc','1070662','TTQN','Drayage',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Tims Transportation LLC','1129926','1172','Intermodal',NULL,'Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Tina Logistics LLC','1268969','TIUG','Drayage',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Titan Logistics LLC','1133302','2559','LTL, Truckload',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Titanium Intermodal Inc','877499','TIMI','Drayage, Intermodal, Ocean, Rail',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Titus Logistics, LLC','1085001','TULT','Drayage, Intermodal',NULL,'Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Tjd Trucking','1013386','TTHG','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Tk & J Transport LLC','1187615','TKJP','Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Tk Norwood Enterprise LLC','1337658','TNEY','Drayage',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Tk Transport Services, Inc.','175784','TKPS','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Tkj Express LLC','1243709','TZZC','Drayage',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Tlm Express, LLC','720754','TLMV','Drayage, Intermodal, LTL, Truckload',NULL,'Chassis (CH); TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Tm Carrier Group Inc','1013800','TCGD','Drayage',NULL,'Chassis (CH); Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Tm3 Logistics LLC','1324124','TUHJ','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Tma Transport Inc','1335313','1196','Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Tmx Intermodal Inc','843711','TIMM','Drayage, Intermodal',NULL,'Chassis (CH); Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Tn Nguyen Transportation LLC','1273032','1146','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Tnt Express Inc','825419','TNTX','LTL','05/13/2020',NULL,'Chicago','IL','Carrier','100,000','05/13/2021','1,000,000','05/13/2020','1,000,000','05/13/2020'),
('Tnt Top Hauling Inc','015752','TTZG','Intermodal',NULL,'Flat Bed Trailer (FT); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Toledo''s Transportation LLC','1493885','2495','TL',NULL,'TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Toor Freight Inc','1373053','TPSC','Drayage, Ocean, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Top Freight Carriers Inc','1077208','TFQV','Drayage, Intermodal',NULL,'Chassis (CH); SMALL STRAIGHT (G2); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Top Notch Trucking , Inc','891494','TNCW','Drayage, Ocean',NULL,'Chassis (CH); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Top Road Inc','787508','TRIW','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Total Distribution Service, Inc.','323231','TLDV','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Touchdown Trucking LLC','1144248','TDWI','Drayage, Intermodal, LTL, Rail',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Town Trucking, Inc.','505619','TTUG','Drayage, Intermodal','01/31/2021',NULL,'Portland','OR','Carrier','100,000','01/31/2021','1,000,000','01/31/2021','1,000,000','01/31/2021'),
('Toyo Trucking Inc','1179654','TIEO','Air Freight, Drayage, Intermodal, Ocean',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Tr Logistics, LLC.','1008940','TRQB','Drayage, Intermodal',NULL,'Cargo Van (CV); Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Tradeconnectt Logistics LLC','1339486','TDIV','Drayage',NULL,'Container (CN);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Trail Lines, Inc.','278140','TRAI','LTL',NULL,'TRACTOR (G4); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Trans Am Logistics Inc','060150','1220','Parcel, Rail',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Trans It Logistics Group Inc','1124638','TILG','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Trans R Us LLC','1125826','TRUT','Drayage',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Trans Trucking Corp','1384717','2351','Truckload',NULL,'(SV); Trailer, Dry Freight (TF); Trailer (not otherwise specified) (TL); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Transatlantic Trucking LLC','1165996','TSGQ','Drayage, Intermodal, Rail',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Transforming Great Destinations Inc','000440','TGDV','Drayage, Intermodal, Rail',NULL,'Chassis (CH); TRACTOR (G4); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Transjet Cargo','074629','COAS','Drayage, Intermodal, Truckload',NULL,'(SV); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Transley Trucking LLC','122209','2426',NULL,NULL,'Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Transmaritime Inc','686192','TMAI','Air Freight, Cartage, Drayage, Intermodal, LTL, Ocean',NULL,'Chassis (CH); Container (CN); Cargo Van (CV); TRACTOR (G4); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Transone LLC','746942','TLLY','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Transource Logistics Inc','917918','TCGJ','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Transpier','1239021','TPFR','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Transport Solutions Inc','950806','TSJK','Drayage, Intermodal','08/14/2020',NULL,'Phoenix','AZ','Carrier','100,000','08/14/2021','1,000,000','08/14/2020','100,000','08/14/2020'),
('Transportation Express 218 LLC','1479040','TETE','Drayage, Intermodal, Rail',NULL,'Chassis (CH); Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Transportation Inc Agent Group Inc','721277','TIAN','Drayage','06/29/2021',NULL,'Heber City','UT','Carrier','250,000','12/15/2020','1,000,000','06/29/2021','1,000,000','06/29/2021'),
('Transporter Freight LLC','1282171','TFPR','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Transpro Intermodal Trucking Inc','826175','TITF','Drayage, Intermodal',NULL,'Chassis (CH); Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Traylor Transport LLC','1375608','2333','Drayage',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Traylor Transportation LLC','1017834','1037','Drayage',NULL,'TRACTOR (G4)','Los Angeles','CA','Carrier','100,000','03/07/2021',NULL,NULL,NULL,NULL),
('Trey Express LLC','1420004','2536','Air Freight, Drayage, LTL, Truckload',NULL,'Trailer, Dry Freight (TF); Trailer, Insulated (TI); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Tri Star Freight System, Inc.','203287','TSFS','Drayage, Intermodal, LTL',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Triangle-J Inc','469662','TNGJ','Drayage, Intermodal, LTL',NULL,'Chassis (CH); Container (CN); Flat Bed Trailer (FT); TRACTOR (G4); Controlled Temperature Trailer (Reefer) (RT); Trailer, Dry Freight (TF); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Tricon Transportation Inc.','247254','TNNR','Air Freight, Cartage, Drayage, Intermodal, LTL, Ocean, Truckload',NULL,'Double-Drop Trailer (DD); Fixed-Rack, Single Drop Trailer (RS);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Trifecta Logistics LLC','1352531','TLAT','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Trifecta Logistics LLC','1233307','TFLQ','Drayage, Intermodal, Truckload',NULL,'TRACTOR (G4); Trailer, Dry Freight (TF); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Trimar Shipping Lines','1191896','TMKT','Cartage, Drayage, Intermodal, Rail, Truckload',NULL,'TRACTOR (G4); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Triple 777 Trucking LLC','1313876','2499','Cartage, Drayage, Intermodal, Rail',NULL,'Chassis (CH); TRACTOR (G4); Controlled Temperature Trailer (Reefer) (RT); Trailer, Dry Freight (TF); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Triple Dat Logistics Inc.','965357','TIPQ','Intermodal, Rail',NULL,'Chassis (CH); Container (CN); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Triple H Services LLC','929503','TRHH','Drayage, Intermodal, LTL','09/17/2020',NULL,'Kent','WA','Carrier','100,000','09/17/2021','1,000,000','09/17/2020','1,000,000','09/17/2020'),
('Triple Jd Transport Inc','1097184','1259','Drayage, Intermodal, Ocean, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Triple L Logistics LLC','1286950','TJGQ','Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Triple T & Son''s Logistics LLC','1300368','TSDM','Drayage',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Triple Transport Inc','424238','TRPT','Drayage, Intermodal',NULL,'Container (CN); TRACTOR (G4); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Tripple Silver Star, Inc','716137','JOVE','TL',NULL,'Cargo Van (CV); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Tripz Enterprise LLC','1279516','TZDK','Drayage, Intermodal, LTL, Rail',NULL,'TRACTOR (G4); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Triton Logistics Inc','845677','TONC','Drayage, LTL',NULL,'Chassis (CH); Cargo Van (CV); Controlled Temperature Trailer (Reefer) (RT); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Trokiando Transportation Inc','1321193','TT','Drayage, Intermodal, Rail',NULL,'Chassis (CH); TRACTOR (G4); Trailer, Tank (Chemicals) (TJ); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Trt International Ltd','772309','TRTC','Drayage, Intermodal',NULL,'Chassis (CH); Double-Drop Trailer (DD); Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Tru Motion  Transport','1105080','TUMV','Drayage, Intermodal, LTL, Ocean, Parcel, Rail',NULL,'Chassis (CH); Cargo Van (CV); TRACTOR (G4);  (SV); Trailer (not otherwise specified) (TL); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Truck Mode Logistix LLC','1267155','TMLM','Truckload',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Truck Strong','025888','TKGA','Air Freight, Drayage, Intermodal, Ocean, Rail, Truckload',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Truckaboiz, LLC','1229436','TBZJ','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Trucker Kings Inc','1186124','1096','Drayage',NULL,'(SV); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Truckers Globe Logistics, Inc','981829','2359',NULL,NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Truckingrus Logistics Inc.','513273','TRUR','Drayage, Intermodal, LTL, Ocean, Rail',NULL,'Cargo Van (CV); TRACTOR (G4); Controlled Temperature Trailer (Reefer) (RT); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Truckland Inc','780379','TKLR','Drayage','10/03/2020',NULL,'Las Vegas','NV','Carrier','100,000','10/03/2020','1,000,000','10/03/2020','1,000,000','10/03/2020'),
('Trucklife Transport LLC','1323071','TJQW','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Truckport Express','093044','TEPO','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('True Friend Trucking LLC','1375395','TFVR','Drayage, Intermodal',NULL,'Chassis (CH); Cargo Van (CV); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Trulogistics LLC','1268472','TULV','Air Freight, Intermodal, LTL',NULL,'Chassis (CH); TRACTOR (G4); High Cube Van (HV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Trx Great Lakes, Inc.','770136','TGDK','Drayage','09/01/2020',NULL,'Cleveland','OH','Carrier','100,000','09/01/2021','2,000,000','09/01/2020','2,000,000','09/01/2020'),
('Trx Southeast, Inc.','770140','TSUA','Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Try Me Transport LLC','1334214','TYAE','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Tt Professional Trucking Inc','1076788','TPTP','Drayage, Intermodal, Rail, Truckload',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ttw Transport Inc','080656','TTWF','Drayage, Rail',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Tuff Trucking LLC','1387972','TFEG','Drayage, Intermodal, Ocean, Rail',NULL,'Chassis (CH); TRACTOR (G4); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Tvc Transport LLC','1604931','3670','LTL',NULL,'TRACTOR (G4); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Twin Bridges Transport LLC','936412','TIJS','Drayage, Intermodal, Rail',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Twinkle Star Logistics Inc','079688','1026','Drayage',NULL,NULL,'Manteca','CA','Carrier','100,000','09/18/2021','0',NULL,'1,000,000','09/18/2020'),
('Two & Two Trucking LLC','1266852','1132','Drayage',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ty-White Trucking LLC','912156','TYWH','Drayage, Intermodal, LTL',NULL,'Chassis (CH); TRACTOR (G4); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Tycol Trucking LLC','1175536','TYDY','Drayage, Rail, Truckload',NULL,'TRACTOR (G4); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Tyner Trucking LLC','1221122','3428','Drayage, Intermodal',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Tz Services Inc','091752','TZSS','Drayage, Intermodal, Rail',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('U Got Freight Inc','1453369','NONE','Cartage, Drayage, Intermodal, LTL, Truckload',NULL,'Flat Bed Trailer (FT);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('U S Freight Lines Inc','633468','1164','Drayage, Intermodal',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('U S Set-Transport','866015','USSN','Drayage',NULL,'Chassis (CH); Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Uca Express LLC','057370','UCAX','Drayage','08/30/2020',NULL,'Hesperia','CA','Carrier','100,000','08/30/2021','1,000,000','08/30/2020','1,000,000','08/30/2020'),
('Umana Trucking Inc','039298','UMAT','Drayage, Intermodal, Rail',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Underdog Wheelers LLC','1281575','UNWC','Drayage, Intermodal, Rail',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Underway Trucking Inc','1439067','2308','LTL',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Underwood Freight Lines LLC','1152447','UFLA','Drayage, Intermodal, Truckload',NULL,'Cargo Van (CV); TRACTOR (G4);  (SV); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Unex Freight LLC','1287480','UNXF','Truckload',NULL,'Trailer, Dry Freight (TF); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Unified Logistic Services LLC','902534','ULSD','Drayage',NULL,'TRACTOR (G4); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Unified Transports LLC','1433963','2366','Air Freight, Cartage, Drayage, Intermodal',NULL,'Flat Bed Trailer (FT);  (SV); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Union Transport LLC','1278931','2532','Drayage, Ocean, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Unique Courier Service Corporation','584866','UQCS','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Unique Delivery Transport Inc','011299','UQDT','Drayage',NULL,'Chassis (CH); Container (CN)','Rialto','CA','Carrier','100,000','03/13/2021','1,000,000','03/13/2021','1,000,000','03/13/2021'),
('Unique One Logistics Inc','1096235','UNQQ','Drayage',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('United American Transportation','107959','UATP','Drayage, Intermodal, Rail',NULL,'Chassis (CH); Cargo Van (CV); TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('United Auto Transport','650968','2312','LTL, Truckload',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('United Distribution System, Inc.','214285','UDST','Drayage',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('United Drivers Alliance','379584','UDAN','Intermodal, LTL, Truckload',NULL,'TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('United Freight & Logistics Ltd.','479957','UFLG','Cartage, Drayage, Intermodal, LTL',NULL,'Chassis (CH); Double-Drop Trailer (DD); Flat Bed Trailer (FT); Fixed-Rack, Flat-bed Trailer (RA); Fixed-Rack, Single Drop Trailer (RS)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('United Freight Transport','1330883','UFBF','Drayage, Ocean',NULL,'Single-Drop Trailer (SD); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('United Global Express Inc','747863','UGEI','Drayage',NULL,'Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('United Kings LLC','1337617','UKAB','Drayage, Intermodal, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('United Lane LLC','940725','UNOL','Drayage, Intermodal',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('United Logistic Services Group Inc','900009','ULSB','Drayage','05/01/2021',NULL,'Compton','CA','Carrier','250,000','05/01/2021','1,000,000','05/01/2021','250,000','05/01/2021'),
('United Logistics Trucking LLC','1166482','ULTG','Drayage',NULL,'Chassis (CH); Container (CN); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('United Petroleum Transports, Inc.','152151','UNPO','Drayage',NULL,'TRACTOR (G4); Trailer, Tank (Chemicals) (TJ)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('United S Inc','126818','USIB','Air Freight, Cartage, Drayage, LTL, Parcel, Truckload',NULL,'(SV); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('United Smith Transport LLC','1025323','USTN','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('United Trans Enterprises Inc','1499947','2463','Drayage, Intermodal, LTL',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('United Transportation Group Inc','1098825','UTGI','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('United Trucking Solutions','056547','UTKS','Truckload',NULL,'TRACTOR (G4);  (SV); Trailer, Dry Freight (TF); Trailer (not otherwise specified) (TL)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('United Van Lines','067234','UVLS','Drayage, Intermodal, LTL','10/01/2022',NULL,'Fenton','MO','Carrier','150,000','05/01/2021','1,000,000','10/01/2022','1,000,000','10/01/2022'),
('United Veterans Salute LLC','078474','2288','Drayage, Intermodal, LTL, Rail, Truckload',NULL,'TRACTOR (G4); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Universal Freight Solutions LLC','1022557','UFSL','Drayage',NULL,'Chassis (CH); TRACTOR (G4); Truck, Van (TV)','Chino','CA','Carrier','100,000','02/15/2021','0',NULL,'0',NULL),
('Unlimited Trucking Inc.','208987','ULMD','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Unlimitedfranklins LLC','493469','ULMF','Drayage, Intermodal, Rail',NULL,'(SV); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Upshift Transportation LLC','1129985','UPHP','Drayage',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ursinio Trucking LLC','007087554C','1024','Drayage','04/21/2021',NULL,'Austin','TX','Carrier','100,000','04/21/2021','0',NULL,'1,000,000','04/21/2021'),
('Us 1 Logistics, LLC','512290','USON','Drayage, Intermodal','07/31/2023','Chassis (CH); Container (CN); Cargo Van (CV)',NULL,NULL,NULL,'250,000','07/31/2023',NULL,NULL,NULL,NULL),
('Us Commercial Freight Inc','663221','USFC','LTL','12/01/2020',NULL,'Rochester','NY','Carrier','500,000','08/27/2021',NULL,NULL,'1,000,000','12/01/2020'),
('Us Connection','423357','UCNN','Drayage',NULL,'Chassis (CH); High Cube Van (HV);  (SV); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Us Flash Express Inc','084498','USFK','Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Us Fleet Transport LLC','1142250','UFTY','Drayage',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Us Riggs LLC','1212602','URAB','Drayage, Intermodal, Rail',NULL,'Chassis (CH); Container (CN); Cargo Van (CV); Double-Drop Trailer (DD); Flat Bed Trailer (FT); SMALL STRAIGHT (G2); LARGE STRAIGHT (G3); TRACTOR (G4); High Cube Van (HV); Load/unload Device on Equipment (LU); Open Top Van (OV); Fixed-Rack, Flat-bed Trailer (RA); Fixed-Rack, Double Drop Trailer (RD); Fixed-Rack, Single Drop Trailer (RS); Controlled Temperature Trailer (Reefer) (RT); Single-Drop Trailer (SD); Removeable Side Trailer (ST);  (SV); Trailer, Heater/Insulated/Vented (TA); Trailer, Bulk (TB); Trailer, Dry Freight (TF); Trailer, Tank (Gas) (TG); Trailer, Insulated (TI); Trailer, Tank (Chemicals) (TJ); Trailer, Tank (Food Grade-Liquid) (TK); Trailer (not otherwise specified) (TL); Trailer, Insulated/Ventilated (TM); Trailer, Pneumatic (TP); Trailer, Electric Heat (TQ); Truck, Van (TV); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Us Services, LLC','407574','USLR','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Us Smart Trucking Inc','858350','USMK','LTL',NULL,'(SV); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Us40 Logistics Inc','1159779','UFUY','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Usa Cargo LLC','878685','USAC','Drayage','04/20/2021',NULL,'Paterson','NJ','Carrier','250,000','04/20/2021','1,000,000','04/20/2021','0','04/20/2021'),
('Usa Investor Transport','944540','2516','Truckload',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Usamplitude','923156','USPD','Drayage','07/22/2020',NULL,'Irvine','CA','Carrier','100,000','07/22/2021',NULL,NULL,'1,000,000','07/22/2020'),
('Ushr LLC','882367','2427','Drayage',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Usko Expedite Inc','746242','UEAB','Drayage, Parcel',NULL,'Cargo Van (CV); SMALL STRAIGHT (G2); LARGE STRAIGHT (G3)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ust Express LLC','1371625','2515','Drayage, LTL',NULL,'Cargo Van (CV); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Utah Rail Runners Inc','1141560','URRA','Drayage, Intermodal',NULL,'Chassis (CH); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('V & S Transport Inc','1131015','VSPI','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('V&H Logistic LLC','1162639','VHLT','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('V7 Express LLC','095675','VSVA','Drayage, Intermodal, LTL, Rail',NULL,'Chassis (CH); Cargo Van (CV); Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Valencia Transport Service Inc','963523','VTSK','Drayage, Intermodal, LTL, Rail, Truckload',NULL,'Trailer, Dry Freight (TF); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Valery & Marlys Trucking LLC','1166367','VMAH','Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Vallejo''s World Logistics LLC','1012216','VWLQ','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Valley Express, Inc.','149591','VLEP','Drayage, Intermodal, Truckload',NULL,'Chassis (CH); Cargo Van (CV); Controlled Temperature Trailer (Reefer) (RT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Van Man Enterprises LLC','848180','GMSB','Drayage, Intermodal, LTL, Truckload',NULL,'Chassis (CH); Cargo Van (CV); SMALL STRAIGHT (G2); LARGE STRAIGHT (G3); TRACTOR (G4); High Cube Van (HV);  (SV); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Vanguard Transportation Inc','1417885','VTCM','Drayage',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Vann Logistics','851279','VLOL','Drayage, Truckload',NULL,'Trailer, Bulk (TB)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Vassel Transport LLC','1105291','VSSF','Drayage, Intermodal',NULL,'Chassis (CH); Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Vchos Transport Inc','1498116','VTYJ','Drayage, Intermodal, LTL',NULL,'Chassis (CH); Cargo Van (CV); TRACTOR (G4); Trailer, Bulk (TB); Trailer, Dry Freight (TF); Trailer (not otherwise specified) (TL)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Vedi Trucking, Inc.','693215','VEDI','Drayage','07/10/2020',NULL,'Riverside','CA','Carrier','100,000','07/10/2021',NULL,NULL,'1,000,000','07/10/2020'),
('Venture Logistics LLC','871545','3692','Drayage, Intermodal, LTL, Ocean, TL',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Veritas Dispatch LLC','094114','3874','LTL',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Vertex Logistics LLC','1257490','VRXL','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Veta Trucking 1 Corporation','1052712','VTFT','Drayage, Intermodal, LTL, Ocean, Parcel, Rail',NULL,'Chassis (CH); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Vetts LLC','141182','VETT','LTL','09/18/2020',NULL,'Basin','WY','Carrier','100,000','09/18/2021','1,000,000','09/18/2020','1,000,000','09/18/2020'),
('Vha Trucking Inc','1398566','NONE','LTL',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Vic RMIS Test','9999190','JFCG','LTL',NULL,'Controlled Temperature Trailer (Reefer) (RT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Victor Leon Harper','1067504','FCXV','Air Freight, Cartage, Drayage, Intermodal, Ocean, Rail',NULL,'Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Victory Transit Inc','578104','VCYA',NULL,NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Victory Transportation Systems, Inc.','469954','VICO','Drayage, Intermodal, Rail',NULL,'Chassis (CH); Cargo Van (CV); Flat Bed Trailer (FT); SMALL STRAIGHT (G2); LARGE STRAIGHT (G3)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Vida De Logistix LLC','121438','VDAS','Drayage, Intermodal, LTL, Truckload',NULL,'Chassis (CH); Cargo Van (CV); TRACTOR (G4); Trailer, Dry Freight (TF); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Vigo LLC','1507567','2490','LTL, Truckload',NULL,'TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Villa Alta Transport LLC','918047','VATF','Drayage',NULL,'Chassis (CH); Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Villalobos Cargo Express','1084525','2537','LTL',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Villamar Trucking','1143220','1058','Drayage',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Villanueva Trucking Inc','675059','3875','Drayage, Intermodal',NULL,'TRACTOR (G4); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Villavicencio Transport LLC','1316075','VTFW','Drayage, Intermodal, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Vincael LLC','1024854','VNCE','Drayage, Intermodal, Rail',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Vip Courier Express, LLC','414149','VORI','Intermodal, Truckload',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Viper Transportation Inc','565881','VIPS','Drayage, Intermodal','07/01/2020','Chassis (CH)','Clayton','CA','Carrier','150,000','07/01/2021','1,000,000','07/01/2020','1,000,000','07/01/2020'),
('Virtual Distribution Direct Inc','1380020','VDDI','Drayage, Intermodal, Parcel, Rail',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Vis Trucking Inc','1431611','VISV',NULL,NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Vision Transport','1013326','1043','LTL',NULL,'Cargo Van (CV); TRACTOR (G4); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Vision Transport Logistics LLC','032404','VSPL','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Vital Transportation Corporation','756571','VTCD','Drayage, LTL, Truckload',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Vkeep Logistics Inc','1231976','VLIL','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Vlk Transport LLC','799493','1102','Drayage',NULL,'Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Vmaxx Productions Inc','030579','VXPC','Drayage, Intermodal','08/11/2021',NULL,NULL,NULL,NULL,'100,000','08/11/2021','1,000,000','08/11/2021','1,000,000','08/11/2021'),
('Voyager Express Inc','698318','VYEI','Drayage, Intermodal',NULL,'Chassis (CH); Flat Bed Trailer (FT);  (SV); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Vpv','739314','VPVT','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Vr Transport Llp','122586','VRTV','Drayage, Intermodal, Ocean, Parcel, Rail',NULL,'Fixed-Rack, Single Drop Trailer (RS)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Vsb Transport LLC','1410972','VSBP','Drayage, Intermodal, Rail',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Vu Transportation','1157684','VUTP','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('W & M Transport','905251','WMTB','Drayage, Intermodal, Rail',NULL,'Chassis (CH); TRACTOR (G4); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('W C B Transport Corp','1620432','WCBW','Drayage, Intermodal',NULL,'Chassis (CH); Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('W C T Logistics LLC','809617','WCGT','Drayage, Intermodal, LTL, Ocean, Rail, Truckload',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('W&A Transporters LLC','1169642','WATR','Drayage, Intermodal, Rail',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('W. W. Rowland Trucking Company, LLC','161344','RWCO','Drayage, Intermodal, Truckload',NULL,'Chassis (CH); TRACTOR (G4); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('W.B. Container Service','243465','WBCN','Drayage, Intermodal',NULL,'Chassis (CH); Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('WFX Logistics',NULL,'WFXG','Drayage, TL',NULL,NULL,'OKLAHOMA CITY','OK','Dispatch',NULL,NULL,NULL,NULL,NULL,NULL),
('Wade Transportation Co','033739','WDEA',NULL,NULL,'Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Wafa Logistic LLC','1347550','WLPL','LTL, Rail',NULL,'Flat Bed Trailer (FT);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Wagon Transport Ltd','1002725','WGNT','Drayage','08/31/2020',NULL,'Surrey','BC','Carrier','250,000','06/11/2021','2,000,000','06/11/2021','10,000,000','08/31/2020'),
('Wagon Wheel Xpress Ltd','1136835','WWXE','LTL, Truckload',NULL,'Cargo Van (CV); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Walia Logistics LLC','098437','WLAG','Drayage, Intermodal, Rail',NULL,'Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Walia Trucking LLC','1332488','2283','Drayage, Intermodal',NULL,'Chassis (CH); Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Wall Street Systems, Inc.','203671','WASS','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Wallace & Sons Transport LLC','1091886','WSTA','Cartage, Intermodal, LTL, Rail',NULL,'SMALL STRAIGHT (G2); TRACTOR (G4); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Wallport Transit Xpress, Inc.','481126','WPTN','Drayage, Intermodal','12/01/2025','Chassis (CH); Flat Bed Trailer (FT); TRACTOR (G4)',NULL,NULL,NULL,'1,000,000','12/01/2025',NULL,NULL,NULL,NULL),
('Wango Trucking Inc','899942','WGKC','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Wanship Enterprises, LLC','211519','WSHE','LTL','06/01/2024','Trailer, Refrigerated (TW)',NULL,NULL,NULL,'250,000','06/01/2024',NULL,NULL,NULL,NULL),
('Want2ship LLC','1463381','3256','Drayage, Intermodal',NULL,'Chassis (CH); Container (CN); TRACTOR (G4); Fixed-Rack, Single Drop Trailer (RS); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Wardini H A Company','823816','WHAW','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4);  (SV); Trailer, Dry Freight (TF)','Santa Ana','CA','Carrier',NULL,NULL,NULL,NULL,NULL,NULL),
('Warhorse Transport LLC','1457814','WRHC','Drayage, Intermodal, Ocean',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Warriors Transport Inc','1228702','WTIG','Intermodal, LTL, Rail, Truckload',NULL,'TRACTOR (G4);  (SV); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Warvale Trucking Inc','1089863','WTIK','Drayage',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Washington Boi Transport LLC','1284675','WBAO','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Washington Freight Service LLC','884856','WFSW','Drayage, Intermodal, Rail',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Watkins Trucking','635934','1145','Drayage, Intermodal',NULL,'Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ways Express Inc','1145101','2430','TL',NULL,'(SV); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Wbh Transport LLC','1181656','WBHO','Air Freight, Drayage, Intermodal, LTL, Rail, Truckload',NULL,'Flat Bed Trailer (FT); TRACTOR (G4); Controlled Temperature Trailer (Reefer) (RT); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Wdm Logistics LLC','1691838','3085','Drayage, Intermodal, Rail',NULL,'Chassis (CH); Container (CN); Cargo Van (CV); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('We Logistics LLC','1181001','1116','Drayage',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('We Xpress Logistics LLC','1338566','WXAI','Air Freight, Drayage, Intermodal, Rail',NULL,'Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Weconomy Expeditors LLC','944505','WECY','Air Freight, Drayage, Intermodal, LTL, Parcel, Rail',NULL,'Chassis (CH); LARGE STRAIGHT (G3); TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Wes & Sons LLC','929675','WENC','Intermodal, Ocean',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('West Coast Express Enterprise Inc','441255','1161','Truckload',NULL,'Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('West Coast Intermodal LLC','091637','WCIM','Drayage, Intermodal',NULL,'Chassis (CH); Cargo Van (CV); Flat Bed Trailer (FT); TRACTOR (G4); High Cube Van (HV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('West Point Transportation LLC','812135','WPAR','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('West Port Logistics Inc','092345','WPLV','Drayage, Intermodal',NULL,'Chassis (CH); Cargo Van (CV); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('West Proline Logistics','752542','WPAA','LTL',NULL,'TRACTOR (G4);  (SV); Trailer, Insulated/Ventilated (TM)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Westar Cartage LLC','079305','WCLW','Drayage',NULL,'Container (CN); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Westpac Trucking Inc','932684','WPCG','Drayage',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Westport Carriers Inc','1400954','3717','Truckload',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Wharf Logistics Inc','1268486','WLFN','Drayage, Intermodal, Rail',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('White Horse Logistics And Transportation Inc','1552252','WHZT','LTL',NULL,'Chassis (CH); TRACTOR (G4); Trailer (not otherwise specified) (TL)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('White Mountain Trucking LLC','807029','WMTV','Truckload','06/22/2025','Flat Bed Trailer (FT); TRACTOR (G4)',NULL,NULL,NULL,'100,000','06/22/2026',NULL,NULL,NULL,NULL),
('Whittenburg Transport LLC','1307618','WHYV','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Wido Trucking LLC','889681','WIDO','Drayage, Intermodal, LTL, Ocean, Rail, Truckload',NULL,'Chassis (CH); Cargo Van (CV); Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Wilfred Mcgirt Transportation LLC','073657','1129','Drayage, Intermodal, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Will County Freight, Inc.','247026','WCFI','Drayage, Intermodal',NULL,'Chassis (CH); Container (CN); TRACTOR (G4); Controlled Temperature Trailer (Reefer) (RT);  (SV); Trailer, Dry Freight (TF); Trailer (not otherwise specified) (TL)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Williams Logistics LLC','1229589','WLHV','Drayage, Intermodal, LTL, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Williams Trucking','1310811','1150','Drayage, Intermodal, LTL',NULL,'Container (CN); Flat Bed Trailer (FT); TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Williams Way Transportation LLC','1348535','WWTR','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Wilmac Enterprises, LLC','475523','WMPC','Drayage, Intermodal',NULL,'Container (CN); Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Windcharger Transport  LLC','1544184','WZAD','Truckload',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Wingman Hauler','1152870','WHAI','Drayage',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Winkelman LLC','1443410','WKML','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Winsfargo Transport Inc','967858','WFGR','Drayage, Intermodal, LTL','10/01/2020',NULL,'Compton','CA','Carrier','100,000','10/01/2020','1,000,000','10/01/2020','1,000,000','10/01/2020'),
('Wlp Trucking LLC','1290543','2315','Drayage, Intermodal, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('World Logistics Usa','520352','MRNQ','Drayage, Intermodal, Rail',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('World Logistics Usa Inc.','365777','WUSA','Drayage',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('World Wide Transportation Inc','1359479','2269','Drayage',NULL,'Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Worldwide Express Transport Inc','1525641','WORL','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Worldwide Logistics LLC','1086801','WWDJ','Drayage, Ocean, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Xchange Trucking Inc','1449327','XTIG','Drayage, LTL, Ocean',NULL,'TRACTOR (G4); Trailer (not otherwise specified) (TL); Truck, Van (TV); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Xcuse Me Trucking LLC','1161907','XMTK','Drayage, Intermodal, Truckload',NULL,'Chassis (CH); Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Xlr8 Truck Lines, LLC','672754','XXTC','Intermodal',NULL,'Chassis (CH); TRACTOR (G4); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Xrp Trucking Inc','1217218','XTIB','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Xtreme Auto Group Inc','756095','XAGA','Drayage, Ocean, Rail',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Xtreme Freight Trucking LLC','1252180','2398','Drayage, Ocean, Rail',NULL,'Container (CN); Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
