-- ============================================================
-- MercuryGate Carriers + Users Reference Tables
-- Run in Supabase Studio at http://127.0.0.1:54323
-- ============================================================

CREATE TABLE IF NOT EXISTS mg_carriers (
  id                  bigserial PRIMARY KEY,
  name                text NOT NULL,
  mc_number           text,
  scac                text,
  modes               text,
  early_ins_exp       text,
  equipment           text,
  loc_city            text,
  loc_state           text,
  loc_type            text,
  cargo_ins_amt       text,
  cargo_ins_exp       text,
  general_ins_amt     text,
  general_ins_exp     text,
  liability_ins_amt   text,
  liability_ins_exp   text,
  created_at          timestamptz DEFAULT now(),
  UNIQUE(scac)
);

CREATE INDEX IF NOT EXISTS idx_mg_carriers_scac ON mg_carriers(scac);
CREATE INDEX IF NOT EXISTS idx_mg_carriers_name ON mg_carriers(name);
CREATE INDEX IF NOT EXISTS idx_mg_carriers_mc   ON mg_carriers(mc_number);

CREATE TABLE IF NOT EXISTS mg_users (
  id                  bigserial PRIMARY KEY,
  owner               text,
  user_id             text,
  last_login          text,
  password_update     text,
  first_name          text,
  last_name           text,
  email               text,
  roles               text,
  lockout_status      text,
  created_at          timestamptz DEFAULT now(),
  UNIQUE(user_id)
);

CREATE INDEX IF NOT EXISTS idx_mg_users_owner  ON mg_users(owner);
CREATE INDEX IF NOT EXISTS idx_mg_users_email  ON mg_users(email);

-- Carriers (2984 rows)
INSERT INTO mg_carriers (name,mc_number,scac,modes,early_ins_exp,equipment,loc_city,loc_state,loc_type,cargo_ins_amt,cargo_ins_exp,general_ins_amt,general_ins_exp,liability_ins_amt,liability_ins_exp) VALUES
('007 Express LLC','1085443','ZZSA','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,'0',NULL,'0',NULL,'0',NULL),
('1 & 1 Logistics Inc','000377','OOLN','Drayage',NULL,'Chassis (CH)',NULL,NULL,NULL,'0',NULL,'0',NULL,'0',NULL),
('1 2 3 Logistics Inc','093077','OWHG','Drayage, Intermodal','08/09/2020',NULL,'San Pedro','CA','Carrier','200,000','04/29/2020','1,000,000','08/09/2020','1,000,000','08/09/2020'),
('1 Alfa Transportation LLC','1080640','OATN','Drayage, Intermodal, Ocean, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,'0',NULL,'0',NULL,'0',NULL),
('1 Shot Transport LLC','1177219','OSBA','Intermodal',NULL,'Flat Bed Trailer (FT); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('1 Way Transportation LLC','1177844','OWAK','Drayage, Intermodal',NULL,'Chassis (CH);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('12 Express LLC','1039766','TXWH','Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('12 Transport Group LLC','1427202','TWTJ','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,'0',NULL,'0',NULL,'0',NULL),
('12Transs LLC','1283657','2278','Drayage',NULL,'TRACTOR (G4);  (SV); Trailer, Refrigerated (TW)',NULL,NULL,NULL,'0',NULL,'0',NULL,'0',NULL),
('1845060',NULL,'1029',NULL,NULL,NULL,NULL,NULL,NULL,'0',NULL,'0',NULL,'0',NULL),
('1St Class Trucking','098057','FSBK','Drayage',NULL,'Chassis (CH); Container (CN); TRACTOR (G4)',NULL,NULL,NULL,'0',NULL,'0',NULL,'0',NULL),
('2 Crows Trucking LLC','690462','TYVO','LTL',NULL,'Flat Bed Trailer (FT)',NULL,NULL,NULL,'0',NULL,'0',NULL,'0',NULL),
('2 Fast 2 Furious Trucking Inc','816197','1121','Drayage, LTL',NULL,'LARGE STRAIGHT (G3); High Cube Van (HV);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('201 Transport LLC','011684','TZOR','Drayage, Intermodal, LTL, Ocean',NULL,'TRACTOR (G4); Trailer, Refrigerated (TW)',NULL,NULL,NULL,'0',NULL,'0',NULL,'0',NULL),
('210 Express LLC','885874','TWOX','Drayage','11/03/2020',NULL,'San Antonio','TX','Carrier','100,000','11/03/2020','1,000,000','11/03/2020','1,000,000',NULL),
('236 Express Inc','1072449','1069','Drayage, Intermodal',NULL,'Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('24 07 Always Trucking Inc','1123018','TZHG','Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('2Way Transport Inc','754632','NONE','LTL',NULL,'Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('2nd St Transport LLC','1525602','SNRJ','Cartage, Drayage, Intermodal, LTL, Ocean, Rail',NULL,'Chassis (CH); Cargo Van (CV); TRACTOR (G4)',NULL,NULL,NULL,'0',NULL,'0',NULL,'0',NULL),
('3 Brothers Trucking LLC','532990','TBTK','Drayage, Intermodal, Ocean, Rail',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('3 Girls And Me Inc','1325668','TJFW','Drayage, Intermodal',NULL,'Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('3 Thirteen Fleet LLC','1349000','1215','Parcel',NULL,'Chassis (CH); Cargo Van (CV); Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('3-Jay''s Trucking Inc','1182930','2320','Drayage, Intermodal, LTL, Ocean, Rail',NULL,'Chassis (CH); Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('360 New Way Inc','726263','TSZW','Drayage, Intermodal, Ocean',NULL,'Chassis (CH); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('3A And K Transportation Services LLC','1331470','TALW','Drayage, Rail',NULL,'Chassis (CH); Container (CN); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('3M Transit LLC','937491','3226','Drayage, Intermodal, Rail',NULL,'Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('3T''s Trucking Container Division LLC','1055204','THKM','Intermodal',NULL,'Chassis (CH); Container (CN); Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('3km LLC','1214863','TKHV','Drayage, Intermodal, LTL, Rail',NULL,'Trailer, Heater/Insulated/Vented (TA)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('4 Cracker Jack Logistics Inc','1247497','FCJH','Drayage',NULL,'Chassis (CH); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('4 Crowns Trans Inc','1027722','FCWN','LTL',NULL,'Cargo Van (CV); TRACTOR (G4); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('413 Logistics Inc','1085085','FOTG','Drayage, Intermodal, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('442 Trinity Xpress LLC','157553','1136','Drayage, Intermodal, Rail',NULL,'Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('46 Logistics Inc','945948','FSLI','Drayage','10/01/2020',NULL,'Gallatin','TN','Carrier','200,000','07/01/2021','1,000,000','10/01/2020','1,000,000','10/01/2020'),
('4D Trucking & Logistics, Inc.','948057','FDDR','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('4Ourth Level Inc','1241065','FOLH','Drayage',NULL,'Chassis (CH); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('4Th Rider Trucking','1449730','2296','Drayage, Rail',NULL,'Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('4way Freight Transport Inc','927809','FWWN',NULL,NULL,NULL,'Perris','CA','Carrier','100,000','09/09/2021',NULL,NULL,NULL,NULL),
('503 Transportation Inc','1017678','FZTP','Drayage, Intermodal, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('562 Express Inc','935775','FVWI','Drayage, Intermodal, Ocean, Rail',NULL,'Chassis (CH)',NULL,NULL,NULL,'0',NULL,'0',NULL,'0',NULL),
('664 Transport LLC','1038030','SXFA','Drayage',NULL,'Chassis (CH); Cargo Van (CV); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('7 Santini Brothers Trucking Inc','937833','SSBH','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('777 Logistics LLC','1192116','SSDO','Drayage, Intermodal, LTL, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('9419-8546 quebec inc.','R-140199-2','TBDS','Drayage, Intermodal',NULL,'Chassis (CH); Cargo Van (CV); Flat Bed Trailer (FT); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('989 Q Transport','1143778','NEGT','Drayage, Intermodal, LTL, Rail',NULL,'Chassis (CH);  (SV); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('99 Trucking Inc','1185587','NNTL','Drayage',NULL,'Chassis (CH); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('A & A Transport Inc.','857659','AAA','LTL','03/10/2021',NULL,'Fresno','CA','Carrier','250,000','03/10/2021','1,000,000','03/10/2021','1,000,000','03/10/2021'),
('A & G Transport Inc','905744','AGRD','Drayage, Intermodal, Ocean',NULL,'Chassis (CH); Container (CN); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('A & Gto Trucker Inc','1541191','AGTP','Cartage, Drayage, Intermodal, Rail',NULL,'Chassis (CH); TRACTOR (G4);  (SV); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('A & W Heavy Haul Inc','801580','AWHH','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('A And E Trucking','849140','AAEQ','Intermodal',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('A And Z Transportation LLC','1169426','AAZS','Drayage',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('A Plus Global Transport Inc','1041372','APGT','Drayage, Intermodal',NULL,'Chassis (CH); Container (CN); TRACTOR (G4);  (SV)','HARBOR CITY','CA','Carrier',NULL,NULL,NULL,NULL,NULL,NULL),
('A R Terrazas Express Transport','0647687','3469','Cartage, Drayage',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('A R Transportation LLC','1474105','ARXD','Drayage, Intermodal, Rail',NULL,'Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('A Team Express Inc','1111148','2287','LTL, Parcel',NULL,'Cargo Van (CV);  (SV); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('A&A Carrier LLC','137943','2553','Cartage, Drayage, Intermodal, LTL, Ocean, Parcel, Rail',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('A&A Fields LLC','1317172','AIYF','Drayage, Intermodal',NULL,'Container (CN); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('A&A Garcia Trucking LLC','1247169','2275','Drayage',NULL,'Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('A&C Logistics LLC','615118','ACLL','Drayage','08/24/2021',NULL,'Edinburg','TX','Carrier','100,000','08/24/2021','0',NULL,'1,000,000','08/24/2021'),
('A&E Logistics And Transport LLC','1252388','1126','Drayage, Intermodal, LTL, Ocean, Parcel, Rail',NULL,'Chassis (CH); TRACTOR (G4); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('A&E Luna Trucking LLC','1387981','AEPD',NULL,NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('A&E Trucking','974072','AESJ','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('A&G Pro Transportation LLC','1430150','APMJ',NULL,NULL,'TRACTOR (G4); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('A&L Line Transportation LLC','034900','AOSQ','Drayage, Intermodal, Rail',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('A&L Trucking Inc','1181768','1234','Drayage, Ocean',NULL,'Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('A&R Truckline','810196','NONE',NULL,NULL,'TRACTOR (G4);  (SV); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('A&d Transport Experts LLC','1136582','1071','Drayage, Intermodal',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('A-1 Towing, Inc','792115','3693','Parcel',NULL,'Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('A-Baznian Express LLC','768332','2580',NULL,NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('A-one Trucking','584893','ATJI','Drayage, Intermodal, Rail',NULL,'Cargo Van (CV); TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('A. S. Logistics Corp.','568189','ALHQ','Drayage, Intermodal, LTL',NULL,'Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('A1 Burris Trucking Company','1541005','3368','Intermodal, LTL',NULL,'Flat Bed Trailer (FT); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('A1 Freight Inc','850014','A1FI','Drayage','12/18/2020',NULL,'Hickory Hills','IL','Carrier','250,000','12/20/2020','1,000,000','12/18/2020','1,000,000','12/18/2020'),
('A1 Value Logistics Inc','1338290','AOZJ','Drayage, Intermodal, LTL, Rail','03/25/2023','Chassis (CH)',NULL,NULL,NULL,'300,000','03/25/2024',NULL,NULL,NULL,NULL),
('A2b Express Inc','1463109','2491','LTL',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('A2b Express Trucking LLC','1118900','AWXK','Drayage',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('AMJAD KHAN TRUCKING INC','1665265','3729','Intermodal',NULL,'TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('ASAP TRANS LLC','1038846','APNS','Drayage, Intermodal',NULL,'Chassis (CH); Flat Bed Trailer (FT); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Aaa Express','885152','AAXS','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Aaa Logistics Usa Inc','1308799','AUJG','Drayage, Intermodal, Ocean',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Abazan Express Inc','945372','AEWE','Drayage, Ocean',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Abb Trucking & Hauling LLC','911528','ATHH','Intermodal',NULL,'Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Abby''s Logistics Inc','1035837','ABYB','Intermodal',NULL,'Container (CN);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Abc Williams Transportation','813788','1142','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Abel Trucks LLC','002647','ABEL','LTL','09/07/0020',NULL,'Los Angeles','CA','Carrier','100,000','09/07/2021',NULL,NULL,'1,000,000','09/07/0020'),
('Abilene Motor Express','194957','AEQC',NULL,NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Abm Express Inc','1084746','2512',NULL,NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Abo Logistics Inc','1035872','ABOS','Drayage, Intermodal',NULL,'Chassis (CH); Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Abo Sephen Transportation LLC','1396682','2461','Drayage',NULL,'(SV); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Above Hell Trucking LLC','1083159','ABVR','Drayage, Intermodal',NULL,'Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Abw Transportation LLC','1083594','AWGD','Drayage',NULL,'Trailer, Tank (Gas) (TG)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Access Tranz LLC','137890','2476','LTL',NULL,'Controlled Temperature Trailer (Reefer) (RT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Accord Express Services Inc','1409735','AEXJ','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Accord Transportation Ltd.','223172','ACTL','TL',NULL,'Trailer, Bulk (TB); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Accurate Cargo Expeditors LLC','1136932','ACEG','Drayage, Intermodal, LTL',NULL,'TRACTOR (G4); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ace Transportation Inc','1092611','ACYN','LTL',NULL,'Cargo Van (CV);  (SV); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Acies Transport LLC','1537699','QQQG','Intermodal, LTL',NULL,'LARGE STRAIGHT (G3);  (SV); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Aclass Express LLC','1201706','ACPB','Drayage, Ocean, Rail',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Acme Transportation Company','614518','ACMW','Cartage, Drayage, Intermodal, LTL, Ocean, Parcel, Rail',NULL,'Chassis (CH); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Acme Truck Line, Inc.','120675','ATKH','Drayage, Intermodal',NULL,'Double-Drop Trailer (DD); Flat Bed Trailer (FT); TRACTOR (G4);  (SV); Trailer (not otherwise specified) (TL)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Acosta Pro Logistics LLC','1379987','2446','Drayage',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Act','463184','ACRR','Drayage, Intermodal',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Act, Inc.','769006','ADNF','Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Acuna Transportation Inc','0547409','3551','Drayage',NULL,'TRACTOR (G4); Trailer (not otherwise specified) (TL)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Acw Logistics, LLC','609708','ACUK','Drayage',NULL,'Chassis (CH); Container (CN); Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ad Fordham Transport LLC','1243057','AFZF','Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ad Freight Express Inc','1081350','2452',NULL,NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ad Hoc Logistics LLC','009670','AHOY','Drayage, Intermodal, LTL, Rail',NULL,'Chassis (CH); Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ada Express, LLC','742637','ADAS','Drayage, Intermodal, LTL','08/22/2020','Chassis (CH); Container (CN); Double-Drop Trailer (DD);  (SV)','Federal Way','WA','Carrier','100,000','08/22/2021','1,000,000','08/22/2020','1,000,000','08/22/2020'),
('Adp Express LLC','086356','ADXH','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Adr Express Inc','1058518','AXDO','Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ads Express Trucking Enterprise LLC','1274799','AXEV','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Adt Freight Systems Inc','1218062','AFHL','Drayage',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Advance Cargo LLC','1036713','ACLK','Drayage, Intermodal, Rail',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Advance Transportation Systems Inc','721968','AVXY','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4); Controlled Temperature Trailer (Reefer) (RT);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Adventure Truckline LLC','1255008','AVUO','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Aeroship Transportation','1009843','AERV','Drayage, Intermodal, LTL',NULL,'Chassis (CH);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Afar Trucking Inc','690308','AFKC','Drayage, Intermodal','09/14/2020',NULL,'Seattle','WA','Carrier','100,000','09/14/2021','1,000,000','09/14/2020','1,000,000','09/14/2020'),
('Afx Logistics LLC','1147146','AFDJ','Drayage, Ocean',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ag Commodities Transload LLC','788490','AGRN','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ag Express LLC','1657033','AGHT','Intermodal, Truckload',NULL,'TRACTOR (G4); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Against All Odds Enterprises LLC','1421988','AAOR','Drayage, Intermodal, LTL',NULL,'Chassis (CH); TRACTOR (G4); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Agi Trucking Inc','890687','AIKW','Drayage, LTL, Truckload',NULL,'Cargo Van (CV); High Cube Van (HV);  (SV); Trailer, Dry Freight (TF); Trailer (not otherwise specified) (TL); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Agr Transport Services Corp','1660182','AMYP','Drayage, Intermodal, Rail',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Aguilar National Carriers Inc','013961','AHWP','Ocean, Rail',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Agx Intermodal','022883','AGFJ',NULL,NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Airborne Freight Lines Inc','554616','AFGL','Drayage',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Aivan Transportation LLC','1127448','AVRL','Drayage',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Aj Prime Inc','1078202','1076','LTL',NULL,'Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ajb Transportation Inc','722420','AJBT','Drayage',NULL,'Container (CN); Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ak Transport LLC','892911','AKPO',NULL,NULL,'Controlled Temperature Trailer (Reefer) (RT);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Al Trucking','500754','AZLK','Drayage','06/05/2021',NULL,'Torrance','CA','Carrier','100,000','06/05/2021','1,000,000','06/05/2021','1,000,000','06/05/2021'),
('Alanis Transport Group LLC','110705','ANYI','Drayage, Intermodal, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Alanis Trucking LLC','1252224','NONE','Drayage',NULL,'TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Albundy Trucking Inc','917979','AYKQ','Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Alcom Intermodal Inc','1014124','ALVC','Drayage',NULL,'Flat Bed Trailer (FT)',NULL,NULL,NULL,'0',NULL,'0',NULL,'0',NULL),
('Aldana Transport','822798','2460','LTL, Parcel',NULL,'TRACTOR (G4); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Aldc Professional Services','0526643','ALDC','Drayage',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Alemon Transportation LLC','1225906','AQEY','Drayage, LTL',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Alex T Trucking LLC','1218070','AQDH','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ali Transport LLC','934387','ALJT','Drayage',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ali Transportation LLC','766065','AXSN','Intermodal',NULL,'Chassis (CH); Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Alibella Transport Inc','0549030','1216','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Alikat Logistics LLC','876143','AKLE','Drayage, Intermodal',NULL,'Flat Bed Trailer (FT); TRACTOR (G4); Trailer (not otherwise specified) (TL)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Alkaro Trucking Inc','1082862','2489','Drayage, Intermodal, Ocean',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('All Harbor Transport LLC','913893','AHTL','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('All In One Logistics Carriers','1403691','2273','Drayage, Intermodal, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('All In Transport Inc','1177596','1253','Drayage, Intermodal, LTL, Rail, Truckload',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('All Modal Transportation Inc','832236','AMTJ','Drayage',NULL,'Chassis (CH); Cargo Van (CV); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('All Of Us # LLC','1036591','AOUH','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('All Ports Logistics, Inc.','477192','APLG','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('All Season Transport LLC','988260','AENO','Drayage, LTL',NULL,'Chassis (CH); Single-Drop Trailer (SD)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('All Seasons Trucking LLC','1399185','CDSY','Drayage, Intermodal, Rail',NULL,'Chassis (CH); Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('All Wheels Forward Trucking LLC','1006110','AWFK','Drayage, Intermodal','04/18/2021',NULL,'Cincinnati','OH','Carrier','100,000','05/10/2021','1,000,000','04/18/2021','1,000,000','04/18/2021'),
('All Wheels Turning','1043571','AWZT','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Allegiant Transportation LLC','112279','AGPL','Drayage','10/02/2020',NULL,'Queen Creek','AZ','Carrier','100,000','10/02/2020','1,000,000','10/02/2020','1,000,000','10/02/2020'),
('Alleyne Equality Transportation','1128221','AQYT','Drayage',NULL,'Chassis (CH); Container (CN); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Alliance Cargo Inc','009183','ANQO','Drayage, LTL',NULL,'Chassis (CH); Container (CN); Cargo Van (CV); SMALL STRAIGHT (G2); LARGE STRAIGHT (G3);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Alliance Logistics LLC','1032739','AIZW','LTL',NULL,'Cargo Van (CV); SMALL STRAIGHT (G2); LARGE STRAIGHT (G3)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Alliance Transportation Services','1317217','AZWH','Drayage, Ocean',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Alliance Worldwide Logistics Corp','1012965','AWLP','Drayage',NULL,'Chassis (CH); TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Allied Bros Transport Inc','825210','ABTA','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Allied Freight Systems Inc','684568','AFYE','Drayage',NULL,'Container (CN);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Allison Manier Investments LLC','1258792','1087','Drayage, Intermodal, LTL, Ocean, Parcel, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Alltrans Logistics LLC','959175','ATNC','Drayage, Ocean',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Alludrop Inc','1214761','AIRG','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Allure Logistics & Transportation Inc','1187641','ALHG','Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Almighty Logistics Inc','1111330','ALNI','Drayage, Intermodal',NULL,'Chassis (CH); Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Aloha Trucking & Transportation LLC','126883','ALVP','Drayage, Intermodal, Rail',NULL,'Container (CN); Cargo Van (CV); TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Alpha Cargo Transportation LLC','1355728','ALSG','Air Freight, Drayage, LTL',NULL,'Chassis (CH); SMALL STRAIGHT (G2)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Alpha Trans Ltd','486494','APHN','Truckload','07/13/2024','Cargo Van (CV); Controlled Temperature Trailer (Reefer) (RT);  (SV)',NULL,NULL,NULL,'300,000','07/13/2024',NULL,NULL,NULL,NULL),
('Alpha Transport LLC','1155116','ALPC','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Alshouli Trucking Inc','1217838','AUHN','Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Alston Trucking, LLC','574326','AOKW','Drayage, Rail',NULL,'Chassis (CH); Flat Bed Trailer (FT); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Altafa Corporation','1088990','AZJP','LTL',NULL,'LARGE STRAIGHT (G3); TRACTOR (G4); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Am Solutions Transport LLC','030102','ASUO','Drayage','01/23/2021',NULL,'Maywood','CA','Carrier','250,000','09/12/2020','1,000,000','01/23/2021','1,000,000','01/23/2021'),
('Ama Plus One LLC','1022765','AJPD','Drayage, Intermodal, LTL, Parcel, Truckload',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Amadeus Transport LLC','1212208','1057','Drayage',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Amado Trucking Inc.','181180','ATHN','Drayage, Intermodal, LTL, Truckload',NULL,'Chassis (CH); Double-Drop Trailer (DD); Flat Bed Trailer (FT); High Cube Van (HV); Single-Drop Trailer (SD); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Amaral Transport LLC','1127781','1242','Drayage, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Amazon Trucking','349532','AMZR','Drayage, Intermodal','10/01/2020',NULL,'Rancho Dominguez','CA','Carrier','250,000','10/01/2020','1,000,000','10/01/2020','1,000,000','10/01/2020'),
('Ambitious Inspired Trucking LLC','1169665','AITM','Drayage, Intermodal',NULL,'TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('America 1 Logistics LLC','752131','AOLQ','Drayage','07/31/2023','Cargo Van (CV)',NULL,NULL,NULL,'250,000','07/31/2023',NULL,NULL,NULL,NULL),
('American Cargo Enterprise LLC','067213','ACFY','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('American Container Transport, Inc.','208163','AMKA','Drayage, Intermodal',NULL,'Chassis (CH); Flat Bed Trailer (FT); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('American Empire Trucking Inc','863456','NA','Truckload',NULL,'TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('American Express Transport LLC','1332894','AYBQ','Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('American Flag Express Inc','035292','2384','Air Freight, LTL, Truckload',NULL,'Cargo Van (CV); Flat Bed Trailer (FT);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('American Hope Express Corp','1118214','AHEA','Drayage, Intermodal, Ocean, Rail',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('American Marine Express Inc','591312','AMXQ','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('American Pacific Forwarders, Inc.','142867','AMPF','Drayage, Intermodal',NULL,'TRACTOR (G4); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('American Quality Cargo LLC','930267','AQCG','Intermodal',NULL,'Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('American Roadways Trucking','935007','2509','LTL',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('American Transport','516525','ARNP','Drayage',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('American Transport Services, LLC','679228','AMGC','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('American Transport, Inc.','147734','ATQW','Drayage','08/01/2024','Flat Bed Trailer (FT); Fixed-Rack, Single Drop Trailer (RS)',NULL,NULL,NULL,'5,000','08/01/2026',NULL,NULL,NULL,NULL),
('American Trucking LLC','1229104','ANKP','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('American Way Trans LLC','114254','AWYY','LTL','10/12/2020',NULL,NULL,NULL,NULL,'100,000','10/12/2020','1,000,000','10/12/2020','1,000,000','10/12/2020'),
('Amex Transport Inc','1736296','ATEA','Drayage, Ocean',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Amf Transportation LLC','1200553','AZUI','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Amf Trucking LLC','060474','AFJK','Drayage, Intermodal, LTL, Ocean, Truckload',NULL,'Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Amg Trucking Inc','1140355','1185','Drayage, Intermodal, LTL, Truckload',NULL,'TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Amin Express & Trans LLC','094288','AETV','Drayage',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Amk Trucking Inc','051019','1134','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Amp Logis Transportation LLC','010362','AXVT','Drayage',NULL,'Chassis (CH)','Indianapolis','IN','Carrier','250,000','04/22/2021',NULL,NULL,NULL,NULL),
('Amt Transport LLC','1316450','AHXM','Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('An Enterprise Inc','648974','AEIH','LTL',NULL,'Controlled Temperature Trailer (Reefer) (RT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Anajo Enterprise LLC','034204','AJOE','Drayage, Intermodal','07/15/2020',NULL,'Seattle','WA','Carrier','100,000','07/22/2021','1,000,000','07/15/2020','1,000,000','07/15/2020'),
('Andale Trucking Co., LLC','980343','ATKF','Drayage',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Anderson Truckin LLC','1132678','ANZI','Intermodal',NULL,'Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Andes Logistics LLC','111807','ANDE','LTL','06/04/2020',NULL,'Monroe','NY','Carrier','100,000','10/01/2020','1,000,000','10/01/2020','1,000,000','06/04/2020'),
('Andrea Transport Inc','869644','1199','Drayage',NULL,'Chassis (CH); Container (CN); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Andy''s Trucking Inc','1226287','2380','LTL, Ocean',NULL,'Flat Bed Trailer (FT); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Aneiro''s Trucking LLC','1187824','ANTS','Drayage',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Angel''s Trucking, Inc.','450895','ATYH','Air Freight, Cartage, LTL, Ocean, Truckload',NULL,'Cargo Van (CV); TRACTOR (G4); Controlled Temperature Trailer (Reefer) (RT); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Angels Trucking, LLC','814295','1223','Intermodal, Parcel, Rail',NULL,'Flat Bed Trailer (FT); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Anomaly Management LLC','1365300','AMLI','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ansor Express LLC','122790','ANSR',NULL,NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Antman Trucking LLC','153554','AXQQ','Drayage',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Antonio And Sons Transit LLC','1520421','2419','LTL',NULL,'Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Antonio B Barajas','646634','BCAC',NULL,'05/14/2021',NULL,'Covina','CA','Carrier','100,000','05/14/2021','0',NULL,'0','05/14/2021'),
('Antonio Gonzalez','1077852','2291','Intermodal',NULL,'Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Antonio Sabusap','671515','SRKJ','Drayage, Intermodal',NULL,'Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Anyama Trucking Incorporated','713150','AYKI','Air Freight, Drayage, Intermodal, LTL, Ocean, Rail, Truckload',NULL,'Chassis (CH); Container (CN); Cargo Van (CV); TRACTOR (G4); Load/unload Device on Equipment (LU); Trailer, Dry Freight (TF); Trailer (not otherwise specified) (TL)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ape Express Trucking Inc','1235022','AQXS','Drayage, Intermodal, LTL',NULL,'Chassis (CH); Flat Bed Trailer (FT); TRACTOR (G4); Trailer, Dry Freight (TF); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Apex Freight LLC','1191964','AXFH','Drayage, Intermodal, Rail',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Apex Trans Inc','951914','AXNL','Drayage, Intermodal, Rail',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('April Freight Inc','839213','APFF','Drayage, Intermodal, Ocean',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Aps Express Inc','1239390','AEGQ','Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Aqua & Otss Services LLC','1460698','AQNY','Drayage',NULL,'TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Aqua Gulf Xpress','335087','SQLO','Drayage, Intermodal, Truckload',NULL,'Chassis (CH); Cargo Van (CV); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ar Trans Group Inc','038857','ARYB','Drayage',NULL,'Cargo Van (CV);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Araiza Trucking Company LLC','1138321','AZAD','Drayage, Intermodal',NULL,'Chassis (CH); Cargo Van (CV); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Aranas Trucking LLC','566470','2502','Drayage, TL',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ardwin Freight','470797','ADWF','Drayage','12/31/2020',NULL,'Burbank','CA','Carrier','250,000','12/31/2020','1,000,000',NULL,'1,000,000','12/31/2020'),
('Arencibia Trucking Inc','799444','ABAB','Drayage, Intermodal, LTL',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Areum Cargo Transport System Inc','092703','AUMS','Drayage',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Arevalo Transport LLC','898248','AVPP','Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Arg Freight Hauling LLC','1356078','AFQT','Drayage, Intermodal, LTL',NULL,'Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ari Express Inc','1576870','AWZJ','Cartage, Drayage, Intermodal, Ocean, Rail',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Arjak&Agnes Sons Trucking','1021407','ARPS','Drayage, Intermodal, LTL, Parcel, Rail',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Arl','152672','AIPA','Drayage, Intermodal, Rail',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Armchi Transportation','015372','1010','LTL','08/08/2021',NULL,'Sun Valley','CA','Carrier','100,000','08/08/2021','0',NULL,'1,000,000','08/08/2021'),
('Arms Transport LLC','1306929','ARAK','Drayage',NULL,'Chassis (CH); Flat Bed Trailer (FT); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Around Clock Logistics LLC','1293972','ACLN','Drayage, Ocean',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Arrow Trans Corp','697747','AWXO','LTL',NULL,'Cargo Van (CV); Trailer, Refrigerated (TW)',NULL,NULL,NULL,'0',NULL,'0',NULL,'0',NULL),
('Arrowhead Freight Services Inc','1044273','AWHC','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Asap Transport LLC','1304342','ASWB','Drayage, Rail',NULL,'TRACTOR (G4);  (SV); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Asap Trucking LLC','107429','ASPT','LTL',NULL,'Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ascent Logistics',NULL,'AEZG','TL',NULL,NULL,NULL,NULL,NULL,'0',NULL,'0',NULL,'0',NULL),
('Asf Express LLC','1336835','ADCM','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ashland Freightways LLC','1350205','AFVM','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ashline Transportation Inc','867824','ASLJ','Drayage, Intermodal, LTL, Ocean, Rail, Truckload',NULL,'Chassis (CH); Container (CN); Flat Bed Trailer (FT);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Aspen Trucking LLC','081405','AKEW','Drayage, Intermodal, LTL',NULL,'Chassis (CH); Flat Bed Trailer (FT); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Aspire Logistics Inc','1003869','2348','Truckload',NULL,'Truck, Van (TV); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Assemble Logistics','1074517','1011','Drayage',NULL,NULL,'Cambridge','MD','Carrier','0',NULL,'0',NULL,'0',NULL),
('Asset Based Intermodal, Inc.','341318','ASBI','Drayage, Intermodal, Rail',NULL,'Chassis (CH); Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Athena Cargo, Inc.','026281','ACLB',NULL,NULL,'TRACTOR (G4); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Athenas Logistics Inc','039306','2513','Intermodal, LTL, Truckload',NULL,'Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Atl','084147','AQST','Truckload',NULL,'Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Atl Transport, Inc.','578094','ATBV','Drayage, LTL, Truckload',NULL,'TRACTOR (G4);  (SV); Trailer (not otherwise specified) (TL)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Atlantic Anchor Logistics - Savannah Inc','1623642','ATPT','Intermodal',NULL,'Chassis (CH); Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Atlantic Coast Hauling LLC','1029744','ANCN','Drayage, Intermodal, LTL, Ocean, Rail, Truckload',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Atlantic Intermodal Services LLC','543201','AISB','Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Atlas Freight Line Inc','1139120','ATMJ','Drayage, Intermodal, Rail, Truckload',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Atlas Marine, LLC','254567','CGWT','Drayage','02/05/2021',NULL,'Long Beach','CA','Carrier','250,000','02/05/2021','2,000,000','02/26/2021','1,000,000','02/05/2021'),
('Atlas Trucking LLC','1182942','ASKG','Drayage',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Atom Freight Inc','1319259','AOQY','Drayage, Intermodal',NULL,'Chassis (CH); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Atw Transportation LLC','659923','AWXM','Drayage, Intermodal',NULL,'Flat Bed Trailer (FT); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Atwal Freight Inc','1238466','AWNH','Drayage',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Augustus Transport, LLC','795476','ATLE','Drayage, LTL',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Austin Moving & Storage Co., Inc.','1028045','AMFB','Drayage, LTL, Truckload',NULL,'Cargo Van (CV); SMALL STRAIGHT (G2); LARGE STRAIGHT (G3); TRACTOR (G4); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Autograph Logistics, Inc.','930500','AUGF','LTL','09/09/2020',NULL,'Burbank','CA','Carrier','250,000','09/09/2021','1,000,000','09/09/2020','1,000,000','09/09/2020'),
('Automotive Transportation Assistance LLC','1017749','ATVM','Drayage, Intermodal, LTL, Rail',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Av Container Service LLC','1462826','2357','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Avenue 54 Logistics LLC','1291866','1107','Drayage, Intermodal, Rail',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Avet Exoto Inc','101215','AVOJ','Drayage, Intermodal, Truckload',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Aveyan Trucking Inc','824018','AVEY','LTL',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Avila Trucking LLC','1152463','AZVF','Drayage, Intermodal, Ocean, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Avtar Freightways Inc','1169424','AWVR','Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Axela Inc','1092625','AXAI','Intermodal, LTL',NULL,'Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Axis Logistics Management Inc','751898','ALMT','Air Freight, Drayage, Intermodal, LTL, Rail, Truckload',NULL,'TRACTOR (G4);  (SV); Trailer, Dry Freight (TF); Truck, Van (TV); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Axle Transportation LLC','1212632','2470',NULL,NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ayala Transport, LLC','951792','AYAT','Drayage, Intermodal, LTL, Rail',NULL,'Chassis (CH); Cargo Van (CV); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ayden Transport Inc','1150164','AYFB','Drayage, Intermodal, Ocean, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Azalea Moving And Storage, Inc.','804124','AZMS','Intermodal',NULL,'Chassis (CH); Container (CN); Cargo Van (CV); SMALL STRAIGHT (G2); LARGE STRAIGHT (G3); TRACTOR (G4);  (SV); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Azam Express LLC','1522655','3834','LTL',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('B & A Kc Trucking LLC','901495','BAKM','Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('B & K Transit LLC','1249779','BKTE','Drayage, Intermodal',NULL,'Chassis (CH); Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('B & T Transportation LLC','798321','1141','Drayage',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('B B M Xpress LLC','087625','BBML','Intermodal',NULL,'TRACTOR (G4); High Cube Van (HV);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('B H 92 Trucking Inc.','583929','BHNW','Air Freight, Intermodal, LTL, Truckload',NULL,'(SV); Truck, Van (TV); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('B K Trucking LLC','1364495','BKTH','Drayage, Intermodal, Rail',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('B Nice Transportation LLC','1275704','BNTF','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('B Yond Transportation Enterprises','014910','BYED','Drayage, Intermodal, LTL',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('B&C''s White Bulls Logistics LLC','737733','BCSW','Drayage, Intermodal, LTL',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('B-Bag Trucking LLC','324514','BBGK','Drayage, Intermodal, Truckload',NULL,'Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('B. W. Mitchum Trucking Co., Inc.','231970','MBWT','Drayage, Intermodal, LTL',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ba Fast Freight Group Inc','972948','BAAG','Drayage, Intermodal, Ocean',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Baar Services Incorporated','1166267','BSII','Drayage, Intermodal, LTL, Truckload',NULL,'Chassis (CH);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Baby Blue Xpress LLC','1145546','3552','Cartage, Drayage, Intermodal, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Back 2 Back Solutions LLC','1291185','1111','Drayage, Intermodal',NULL,'Chassis (CH); Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Back2back Logistics Inc','1001363','BACK','Drayage','12/14/2020',NULL,'Glendale','CA','Carrier','100,000','12/14/2020','0',NULL,'1,000,000','12/14/2020'),
('Badesha Trans Inc','1167069','2439','Air Freight, Cartage, Drayage, Intermodal, LTL, Ocean, Parcel, Rail, Truckload',NULL,'(SV); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bady''s Trucking LLC','1434474','BDIT','Drayage, Intermodal',NULL,'Chassis (CH);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bahena Express Inc','1024836','BHXO','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4)','Ontario','CA','Carrier',NULL,NULL,NULL,NULL,NULL,NULL),
('Bajwa Express LLC','891019','2581','Intermodal',NULL,'Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bal Trucking Services Inc','884335','BALI','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bala Express Inc','1420162','NONE',NULL,NULL,'Controlled Temperature Trailer (Reefer) (RT);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Baldwin Transfer Company, Inc.','239703','BWIF','Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Balita Transport Corporation','1477439','BTEY','Drayage, Intermodal, Ocean',NULL,'TRACTOR (G4)',NULL,NULL,NULL,'0',NULL,'0',NULL,'0',NULL),
('Balsam Logistics','1216805','3722','LTL, Truckload',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bambi Logistics Inc','1096929','BMBQ',NULL,NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bamjo''s Trucking LLC','1035595','BJSL','Drayage, Intermodal, LTL',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bangash Trucking LLC','1175470','BTWT','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bank On Banks Trucking LLC','1053174','BOBA','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Baolong Logistics Corporation','858955','BLEH','LTL',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bar Logistics LLC','1458345','3472','Cartage, Drayage, Intermodal, LTL, Ocean, Rail, Truckload',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Barajas Drayage LLC','1503997','2562','Drayage, Intermodal',NULL,'Container (CN); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Barber Logistics LLC','1313362','BAOB','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Barima Transport LLC','1351335','3689','Truckload',NULL,'Flat Bed Trailer (FT);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Barnes & Sons Trucking LLC','1327616','2321',NULL,NULL,'TRACTOR (G4); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Barnes Transportation Services, Inc.','271116','BTTE','Drayage, LTL',NULL,'Chassis (CH);  (SV); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Barnets, Inc.','147137','BARM','Drayage',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Barnett Transport LLC','1286155','BRZO','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Barnett Trucking LLC','590949','BNOT','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Barnhart Transportation, LLC','494758','BTFF','Drayage, LTL, Truckload',NULL,'Chassis (CH); Container (CN); Cargo Van (CV); Double-Drop Trailer (DD); Flat Bed Trailer (FT); TRACTOR (G4); Single-Drop Trailer (SD);  (SV); Trailer, Pneumatic (TP); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Barreda J & M Tow LLC','1133336','2518',NULL,NULL,'Cargo Van (CV); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Basuta Brothers Inc','1612855','BAWO','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bay Area Container, Inc.','228029','BACC','Drayage',NULL,'Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bay Hawk Trucking Inc','1081385','BHOP','Drayage, Intermodal, Ocean, Rail',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bay Integrated Logistics Inc','986845','BYIG','Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bay Port Trucking Inc','1653362','3246','Drayage',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bay Valley Trucking Inc','1157366','BCZQ','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bayer Transport LLC','985421','BYTC','Drayage','11/19/2020',NULL,'Las Vegas','NV','Carrier','100,000','11/19/2020','1,000,000','11/19/2020','1,000,000','11/19/2020'),
('Baystar Trans Inc','697404','2381','Air Freight, LTL, Truckload',NULL,'TRACTOR (G4);  (SV); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bayview Trucking','836887','BYVK','Drayage',NULL,'Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bb Trucking Inc.','856968','BBKH','Drayage',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bb&G Transportation LLC','1127015','BBLN','Drayage, Intermodal',NULL,'Container (CN);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bbmc Trucking LLC','366872','BBMC','Intermodal',NULL,'Double-Drop Trailer (DD); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bbs Trucking Inc','1058254','BBUN','Drayage',NULL,'Chassis (CH); Controlled Temperature Trailer (Reefer) (RT); Trailer, Dry Freight (TF); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bbt Logistics, Inc.','434817','BBTO','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bcazar Inc','1244352','BINJ','Drayage, Rail',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bcb Transport LLC','742438','BCBO','Drayage',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bdm Transport LLC','1362116','2310','Truckload',NULL,'Double-Drop Trailer (DD); Fixed-Rack, Flat-bed Trailer (RA)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bdq Logistics Inc','1148574','2454','Intermodal',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bean Trucking LLC','1436758','BNRL','Drayage, Intermodal, Ocean, Rail',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bearcat Carriers LLC','1533030','BGWY','LTL, Truckload',NULL,'LARGE STRAIGHT (G3)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Beasley Group Transportation','107617','BEAS','Drayage','01/17/2021',NULL,'Long Beach','CA','Carrier','100,000','01/03/2021','1,000,000','03/31/2021','1,000,000','01/17/2021'),
('Beasley''s Transportation','1078990','BSEL','Drayage, LTL, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Beattie''s Trucking Group Inc','843139','BTGG','Drayage',NULL,'Chassis (CH)','West Covina','CA','Carrier',NULL,NULL,NULL,NULL,NULL,NULL),
('Bee Jay Transport LLC','627269','BJPR','Drayage',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Beehive Logistics LLC','093125','2865','Truckload',NULL,'Flat Bed Trailer (FT); TRACTOR (G4); Load/unload Device on Equipment (LU);  (SV); Trailer (not otherwise specified) (TL); Truck, Van (TV); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Beemac Trucking','365667','BMEC','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Beholden Enterprise','1196317','2358','Drayage, Intermodal',NULL,'Chassis (CH); Container (CN); TRACTOR (G4); Trailer (not otherwise specified) (TL)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Believe Transportation Inc','0549104','2525','Rail',NULL,'Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bena Transportation LLC','1033686','BTVK','Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bennett Transportation & Supply LLC','1369589','BNSN','Drayage',NULL,'Chassis (CH); Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Benntech Inc','1080217','BIDJ','Drayage, Intermodal, LTL, Rail',NULL,'Chassis (CH); Container (CN); Cargo Van (CV); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bernardo''s Trucking','1298984','2520',NULL,NULL,'SMALL STRAIGHT (G2)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Best Bay Trucking Corporation','756420','BBYG','Drayage',NULL,NULL,'Marina Del Rey','CA','Carrier','250,000','11/12/2020',NULL,NULL,NULL,NULL),
('Best Carrier Solutions Inc','937180','BCSB','Drayage, Intermodal',NULL,'Chassis (CH); Container (CN); Cargo Van (CV); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Best Choice Express Inc','1198355','BCEV','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Best Dray Inc','1429530','BDIW','Drayage, Intermodal, Ocean',NULL,'Chassis (CH); Cargo Van (CV); Flat Bed Trailer (FT); TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Best Drayage Company LLC','132546','BDCQ','Drayage',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Best Transportation LLC','472409','BESR','Drayage',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Best Yet Express Inc','1521248','BTYT','LTL, Truckload',NULL,'SMALL STRAIGHT (G2); LARGE STRAIGHT (G3); TRACTOR (G4); Single-Drop Trailer (SD); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bestman Global LLC','1541182','BIZA','Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bet-Lehem Trucking LLC','955265','BLHT','Drayage, Rail',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bethell Port Transportation Inc','1678247','BFBJ','Drayage, Intermodal, Ocean',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Between State Lines LLC','1078713','1191','Drayage, Intermodal, Truckload',NULL,'Chassis (CH); Cargo Van (CV); TRACTOR (G4); Trailer (not otherwise specified) (TL)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bfe Systems LLC','1097433','BFEW','Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bfm Inc','748219','BFMI','Drayage, Intermodal, LTL, Ocean, Parcel, Rail',NULL,'Chassis (CH); Container (CN); Trailer, Heater/Insulated/Vented (TA); Trailer, Dry Freight (TF); Trailer, Insulated (TI); Trailer, Electric Heat (TQ)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bgg Trucking LLC','1080288','1198','Drayage, Intermodal, Ocean, Rail',NULL,'Container (CN); TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bgs Transport LLC','979460','BGQS','Drayage, Intermodal, LTL, Ocean, Rail',NULL,'Chassis (CH); Flat Bed Trailer (FT);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bgz Transport LLC','1440640','BGZQ','Drayage, Intermodal, Ocean, Rail, Truckload',NULL,'Chassis (CH); Double-Drop Trailer (DD); Flat Bed Trailer (FT); Single-Drop Trailer (SD)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bhandal Logistics LLC','1093678','2360','Truckload',NULL,'TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Big 8 Transportation LLC','1096250','BEQK','Drayage, Intermodal, LTL, Truckload',NULL,'Chassis (CH); TRACTOR (G4); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Big Blue Boxes','451529','3247','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Big Boss Transportation LLC','720546','1193','Drayage, Intermodal, LTL',NULL,'TRACTOR (G4); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Big Boyz Trucking LLC','1429517','BBVC','Drayage, Intermodal, Ocean, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Big Brother Lil Brother Trucking LLC','1240251','2465','Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Big Bucks Transport LLC','1444984','BBZP','Drayage',NULL,'Chassis (CH); Cargo Van (CV); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Big Dog & Sons LLC','1181138','BIGO','LTL',NULL,'Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Big Dream Trucking Inc','1336308','NONE','LTL',NULL,'(SV); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Big F Transport LLC','073795','BFTH','Drayage, LTL',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Big L Transport LLC','1124824','BIGW','Drayage, Rail',NULL,'Chassis (CH); TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Big Q Transportation LLC','1125913','BQTE','LTL',NULL,'Flat Bed Trailer (FT); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Big Rudy','1371548','3386','Drayage, Intermodal, Ocean, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Big Wheelz Trucking LLC','1217166','BWUT','Drayage, Intermodal',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bilkays Trucking Inc','1230779','BKYG','Drayage',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Billion Dollar Miles Inc','1251257','BDQV','Drayage, Intermodal, Rail',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bilol Transportation Inc','009260','1042','Drayage',NULL,'Cargo Van (CV)','Dallas','TX','Carrier',NULL,NULL,NULL,NULL,NULL,NULL),
('Binos Trucking','1409580','BIWM','Drayage, Intermodal, Rail',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bjay Logistics LLC','1343609','BLHP','LTL',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bjl Express LLC','089320','BJLP','Drayage, Intermodal, Rail',NULL,'TRACTOR (G4);  (SV); Trailer (not otherwise specified) (TL)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bl Hill Trucking LLC','1289708','HBLJ','Drayage, Intermodal',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Black Dog Transport Inc','1276752','NONE','Drayage, LTL',NULL,'Cargo Van (CV);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Black Hawk Transport LLC','085229','BHWS','Drayage, Intermodal',NULL,'Container (CN); Cargo Van (CV); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Black Mamba Trucking Inc','1023107','BMMP','Drayage, Intermodal, LTL, Parcel',NULL,'Flat Bed Trailer (FT); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Black Starline Transport','009529','1012','Drayage, Intermodal','04/22/2020',NULL,'Commerce','CA','Carrier','100,000','04/22/2020','0',NULL,'1,000,000','04/22/2020'),
('Blackbird Intermodal','1060893','BKBF','Drayage','11/13/2020',NULL,'Los Angeles','CA','Carrier','100,000','11/13/2020','1,000,000','11/13/2020','1,000,000','11/13/2020'),
('Blackbird Intermodal',NULL,'1202',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Blackman Reign Limited Liability Company','1256670','BLRA','Drayage, Intermodal',NULL,'Chassis (CH); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Blake''s Trucking LLC','552490','BKKE','Drayage, Intermodal',NULL,'Chassis (CH); Cargo Van (CV); Double-Drop Trailer (DD)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Blaque Diamonds Inc','1302647','1110','Intermodal',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Blaque Diamonds Logistics LLC','065085','1040','Drayage',NULL,'TRACTOR (G4); Controlled Temperature Trailer (Reefer) (RT)','Los Angeles','CA','Carrier',NULL,NULL,NULL,NULL,NULL,NULL),
('Blaw Trucking LLC','1332989','BTBP','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Blaze Transport','1117029','BTQP','Drayage, Intermodal, LTL, Ocean',NULL,'Chassis (CH); Trailer, Bulk (TB); Trailer, Tank (Chemicals) (TJ)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Blazer Transportation LLC','1572403','2567','Drayage',NULL,'Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Blessing Of God Limited Liability Company','1441410','BOGH','Air Freight',NULL,'Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Blounts Aja Enterprise LLC','1142498','BAVW','Drayage',NULL,'Chassis (CH); Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Blue & Grey Transport Company, LLC','190263','BGTY','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Blue Bird Freight Inc','1459125','2326','LTL, Truckload',NULL,'Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Blue Diamond Transportation Inc','070052','BMDT','Intermodal','01/22/2021',NULL,'Compton','CA','Carrier','100,000','01/22/2021','1,000,000','01/22/2021','1,000,000','01/22/2021'),
('Blue Flash Express Inc','1047354','BFEH','Drayage',NULL,NULL,'Wilmington','CA','Carrier',NULL,NULL,NULL,NULL,NULL,NULL),
('Bluestar Services LLC','692852','BSVL','Truckload',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bluestreak Transportation Inc','0611842','1045','Drayage, LTL',NULL,'TRACTOR (G4)',NULL,NULL,NULL,'0',NULL,'0',NULL,'0',NULL),
('Bma Logistics Inc','1411293','1241','Truckload',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bmb United Corporation Inc','1184510','BMBY','Drayage, Intermodal, Ocean, Rail, Truckload',NULL,'Chassis (CH); Container (CN); Cargo Van (CV); Double-Drop Trailer (DD); TRACTOR (G4); Fixed-Rack, Flat-bed Trailer (RA); Fixed-Rack, Double Drop Trailer (RD); Controlled Temperature Trailer (Reefer) (RT);  (SV); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bndz Transportation LLC','1194491','BTDY','Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bogg Express LLC','149749','BEOO','Air Freight, Drayage',NULL,'Controlled Temperature Trailer (Reefer) (RT);  (SV); Trailer, Heater/Insulated/Vented (TA); Trailer, Tank (Gas) (TG); Truck, Van (TV); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bolt Cargo Lines LLC','1021103','BGUJ','Drayage, Intermodal, LTL, Rail, Truckload',NULL,'TRACTOR (G4);  (SV); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Boltz Trucking LLC','1373999','BZBB','Drayage, Intermodal, Rail',NULL,'(SV); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bora Som Logistics Inc','1201828','3251','Intermodal, LTL',NULL,'TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Border Thunder Transportation, LLC','865469','BORD','Drayage','05/20/0002',NULL,'Horizon City','TX','Carrier','100,000','05/20/2021',NULL,NULL,'1,000,000','05/20/0002'),
('Borderlanders Inc','1019332','BIDH','Air Freight, LTL, Truckload',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Borderline Carrier Inc','933111','BNCL','Drayage',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Borders Of Blue LLC','128661','BOBM','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Born To Ready Trucking Inc','037061','1036','Drayage',NULL,NULL,'Bakersfield','CA','Carrier','100,000','09/17/2020','0',NULL,'1,000,000','09/17/2020'),
('Bos Transport LLC','666508','BOPA','Drayage, Intermodal',NULL,'Chassis (CH); Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bosquez Trucking Inc','1338062','2469','Drayage, Intermodal',NULL,'Chassis (CH); Container (CN); Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Boss Moves Trucking Company LLC','1190401','BMYF','Drayage, Intermodal',NULL,'TRACTOR (G4); Trailer (not otherwise specified) (TL)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Boss Trucking LLC','1408888','BOST','Drayage, Intermodal, LTL, Ocean, Parcel, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bossmann Logistics, LLC','1306265','3974','Cartage, Drayage, Intermodal, Parcel',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bp White LLC','1095748','WBBA','Drayage',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bpx Logistics LLC','238914','BPXP','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4); Trailer (not otherwise specified) (TL)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Br Transport Express','975961','BRPK','Drayage','11/30/2020',NULL,'Wilmington','CA','Carrier','100,000','11/30/2020','1,000,000','11/30/2020','1,000,000','11/30/2020'),
('Bradford Express Inc','1141426','2286','LTL, Parcel',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Brandon Logistics Inc','744206','BLQJ','Drayage, Intermodal, Ocean',NULL,'Chassis (CH); Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Brandon Transport LLC','1263110','BNQV','Drayage, Intermodal, LTL, Ocean, Parcel, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bravo Motor Carriers, Inc.','373284','BMCA','Drayage, Intermodal, Rail',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Breezeway Logistics LLC','949343','BRCA','Air Freight, Drayage, Intermodal, LTL, Rail, Truckload',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bri Vir Trucking Inc','901494','1074','LTL',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Brian Hill Transportation LLC','1190866','HBNO','Intermodal, Truckload',NULL,'Container (CN);  (SV); Trailer, Dry Freight (TF); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Briana''s Transport LLC','1568804','3084','Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bridgetown Trucking','001304','BDWT','Drayage, Intermodal, LTL, Truckload',NULL,'Chassis (CH); Cargo Van (CV); Flat Bed Trailer (FT);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Brielle Transport LLC','1336680','BLLR','Drayage',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bright Freight Solution, LLC','966354','BFNM','LTL',NULL,'TRACTOR (G4);  (SV); Trailer, Dry Freight (TF); Truck, Van (TV); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bright Logistic Care LLC','089539','BLYJ','Air Freight, Drayage, Intermodal, LTL, Ocean, Parcel, Rail, Truckload',NULL,'Chassis (CH); Cargo Van (CV);  (SV); Trailer, Tank (Gas) (TG); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bright Trucking LLC','116206','BGUC','Drayage, Rail',NULL,'Chassis (CH); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bright Way Trucking LLC','1660111','BRRH','Intermodal',NULL,'Chassis (CH); Container (CN); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Brightstar Transport LLC','125087','1208','Truckload',NULL,'Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Briseno Transport LLC','1220134','2300','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bristol Transportation','996584','BROF','Drayage, Intermodal',NULL,'Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Brjs Transport','1073090','2361','Drayage, Intermodal, Ocean',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Broadus Transportation LLC','1325886','BRQW','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Brokers Cartage Company Inc','512653','BKCH','Drayage, Intermodal, Ocean',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Brosky''s Trucking Inc','1756181','3569','Drayage',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Brothaz Hauling LLC','1121162','3528','LTL',NULL,'Cargo Van (CV); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Brother Express Inc','958124','BXPC','Drayage, Intermodal, LTL, Ocean, Truckload',NULL,'Chassis (CH); TRACTOR (G4); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Brotherhood Transport LLC','626045','BHDB','Drayage',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Brown & Son Trucking LLC','1203742','BWST','Drayage, Intermodal, Ocean, Rail',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Browns Transportation','1192500','BWNS','Drayage, Intermodal',NULL,'Chassis (CH); Cargo Van (CV); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bryant And Sons Trucking, LLC','675941','BASB','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bs Roadlines Inc','1017069','BSQL','Drayage, Rail',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bsb Trucking LLC','1162385','BBAL','Drayage, Intermodal, Rail',NULL,'Chassis (CH); Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bt Express','1185017','BEXE','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Btdm Logistics LLC','1355518','BDZJ','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Buble Logistics Inc','1398317','BUBN','Drayage, Intermodal, LTL',NULL,'Chassis (CH); Container (CN); Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bucci Express Inc','780761','BUCO','Air Freight',NULL,'(SV); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Built 2 Haul LLC','1414997','BHVL','Drayage, Intermodal, LTL, Rail',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bulak Freight LLC','1152241','BKFY','Drayage, Intermodal, Ocean, Parcel, Rail',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bulldog Trucking','1102323','1064','Drayage',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bulls Transport Inc','763384','BTNN','Truckload',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bully Express LLC','1145458','BYEL','Cartage, Drayage, Intermodal, LTL',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bully Transportation LLC','1015316','BUYN','Drayage, Intermodal, LTL',NULL,'Flat Bed Trailer (FT);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bulsim Transportation LLC','561961','2577',NULL,NULL,'Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bumpers Trucking LLC','1210299','BUAB','Drayage, Intermodal',NULL,'Chassis (CH); Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Buraq Limited','1461778','2572','Drayage, Intermodal, LTL',NULL,'Cargo Van (CV); Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Burras & Gentle Logistics LLC','1464978','BGEH','Drayage, Intermodal, Ocean, Rail',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('By Michael Hunt',NULL,'3630',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('By Michael Hunt LLC','1161078','BMHY','Drayage, Intermodal, LTL, Rail',NULL,'Cargo Van (CV); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bz Express Inc','804521','BZEE','Drayage, Intermodal, LTL',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bzl Inc','1065193','BZLN','Drayage',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('C & B Transportation Services, Inc.','406764','CDRK','Drayage, Intermodal',NULL,'Flat Bed Trailer (FT);  (SV); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('C & E Motor Sports','1070518','CEMO','Drayage, Intermodal, LTL',NULL,'LARGE STRAIGHT (G3); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('C & K Logistics LLC','1249974','CKGE','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('C Brown Customs LLC','990327','BCGI','Drayage, Intermodal, LTL, Ocean, Parcel, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('C James Transportation LLC','1264079','1140','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('C N W Trucking LLC','1129816','1155',NULL,NULL,'Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('C&B Transport And Logistic Services LLC','1426271','CBSE','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('C&J Construction Solutions LLC','1348441','2530','Ocean, Truckload',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('C&J Long River Inc','1123551','2277','Drayage, LTL, Truckload',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('C&L Preston Transit LLC','1421618','CLXW','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('C&M Logistics LLC','1303365','1122','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('C&M Transport LLC','1160474','3105','Drayage, Intermodal',NULL,'Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('C&R Family Trucking LLC','1271320','CRFQ','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('C.O. Rodenbaugh Transfer, Inc.','469878','FFTT','Drayage','07/01/2021',NULL,'Lincoln','NE','Carrier','100,000','07/01/2021','1,000,000','07/01/2021','1,000,000','07/01/2021'),
('C1 Delivery, LLC','933499','2529','Parcel',NULL,'Load/unload Device on Equipment (LU); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
ON CONFLICT (scac) DO NOTHING;

INSERT INTO mg_carriers (name,mc_number,scac,modes,early_ins_exp,equipment,loc_city,loc_state,loc_type,cargo_ins_amt,cargo_ins_exp,general_ins_amt,general_ins_exp,liability_ins_amt,liability_ins_exp) VALUES
('C1 Transportation, Inc','970896','COII','Drayage, Intermodal, LTL, Rail',NULL,'Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('C5 Expedite LLC','879378','3814','Truckload',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('COASTAL LOGISTICS, INC','1500665','NONE','Drayage',NULL,NULL,'GARDEN CITY','GA','Carrier','0',NULL,'0',NULL,'0',NULL),
('Cadasap LLC','1191221','CDSO','Drayage',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Cads Transport LLC','1313955','CDUQ','Drayage',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Cal U Transport Inc','1001651','CTBB','Drayage, Intermodal, Rail',NULL,'Chassis (CH);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Caldwell Trucking 1981 LLC','1264411','CWBC','Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Caleb Roadline Inc','925429','CLBR','Drayage, Intermodal, LTL','08/04/2020',NULL,NULL,NULL,NULL,'100,000','08/19/2021','1,000,000','08/04/2020','1,000,000','08/04/2020'),
('Calhoun Truck Lines','201062','CHKD','Drayage',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Caliber Carriers Inc','1282953','CBZB','Intermodal, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Calicoast Trucking Inc','1064058','CIKC','Drayage, Rail',NULL,'Flat Bed Trailer (FT); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('California Drayage Inc','1603217','CQZW','Drayage',NULL,'Chassis (CH); Container (CN); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('California Express Logistics Inc','1064081','CFXJ','Drayage',NULL,'Chassis (CH); Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('California Professional Carriers LLC','1110126','3004','Drayage, Intermodal, LTL, Rail',NULL,'Chassis (CH); Container (CN); Cargo Van (CV);  (SV); Trailer, Tank (Gas) (TG); Trailer, Tank (Food Grade-Liquid) (TK); Trailer, Insulated/Ventilated (TM); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('California Trucking Inc','732989','CAHT','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Calko Transport Company, Inc.','238598','CKOR','Drayage',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Calport & Rail Logistics Inc','041538','CLPF','Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Calport Inc','826311','CLPI','Drayage, Intermodal, LTL, Rail',NULL,'Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Calstar Motor Freight Inc','1226108','2365',NULL,NULL,'Flat Bed Trailer (FT);  (SV); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Caltex Freight LLC','1327994','CJUC','LTL, Truckload',NULL,'(SV); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Calvin''s Courier LLC','1128375','CVJR','Drayage',NULL,'Flat Bed Trailer (FT);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Camacho Transportation L.l.c','778169','CMAS','Drayage',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Camacho''s Express LLC','1300484','CXFB','Intermodal, Ocean, Rail',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Campbell''s Trucking Inc','1187932','CQKG','Drayage',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Campillo Logistics LLC','1539097','CBOF','Truckload',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Campos Trucking Inc','089033','CPST','Drayage, Intermodal',NULL,'Chassis (CH); Container (CN); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Can American Enterprises Ltd.','425491','CANA','Cartage, Drayage, Intermodal, LTL, Ocean, Parcel, Rail, Truckload','10/29/2026','Chassis (CH); Container (CN); Cargo Van (CV); Double-Drop Trailer (DD); Flat Bed Trailer (FT); TRACTOR (G4); Load/unload Device on Equipment (LU); Open Top Van (OV); Fixed-Rack, Flat-bed Trailer (RA); Fixed-Rack, Double Drop Trailer (RD); Fixed-Rack, Single Drop Trailer (RS); Controlled Temperature Trailer (Reefer) (RT); Single-Drop Trailer (SD);  (SV); Trailer, Heater/Insulated/Vented (TA); Trailer, Dry Freight (TF); Trailer (not otherwise specified) (TL); Trailer, Electric Heat (TQ); Truck, Van (TV); Trailer, Refrigerated (TW)',NULL,NULL,NULL,'5,000','10/29/2026',NULL,NULL,NULL,NULL),
('Can Trail Transportation LLC','1241884','CADI','Drayage, Intermodal',NULL,'Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Canady Trucking LLC','1406925','CDAR','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Cancun Transport Inc','1092395','CNAE','Drayage, Rail',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Candor Freight Systems Inc','950656','NONE','TL',NULL,'TRACTOR (G4); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Candor Transport LLC','137606','CNGM','Drayage, Intermodal',NULL,'High Cube Van (HV); Trailer (not otherwise specified) (TL)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Canela & Sons Trucking LLC','924446','2328','Cartage, Drayage, Intermodal, LTL, Ocean, Parcel, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Cannon Truck Lines Inc','965626','CCKE','Drayage, Intermodal, Ocean, Rail',NULL,'Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Canyon Express Transportation LLC','1197707','NONE','TL',NULL,'Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Capital Exports Inc','859307','CEIA','Air Freight, Cartage, Drayage, Intermodal, LTL, Ocean, Parcel, Rail, Truckload',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Capital Logistics, LLC','068352','CLLN','Drayage, Intermodal, LTL',NULL,'Chassis (CH); TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Captain C Logistics, LLC','110474','CCWW','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Cardinal Logistics 1 LLC','1281297','CQBH','Drayage, Intermodal',NULL,'Chassis (CH);  (SV); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Cardona Trucking','127665','CAKD','Drayage',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Cargia Express LLC','038564','CARG','Drayage','03/01/2021',NULL,'Columbia','NJ','Carrier','100,000','03/01/2021','1,000,000','03/01/2021','1,000,000','03/01/2021'),
('Cargo Bay Trucking','691228','CBZS','Drayage, TL',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Cargo Express Logistics Inc','1040648','CARE','Drayage','05/31/2020',NULL,'Woodridge','IL','Carrier','100,000','05/31/2021','1,000,000','05/31/2020','1,000,000','05/31/2020'),
('Cargo Logistics International, LLC','1043457','CGGR','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Cargo Movers LLC','1197090','CQGR','Drayage, Intermodal, Rail',NULL,'TRACTOR (G4);  (SV); Trailer (not otherwise specified) (TL); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Cargo Pac Inc','1167606','CVQM','Drayage',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Cargo Solution Express Inc.','565817','CRHY','Drayage, Intermodal, Ocean, Rail',NULL,'Cargo Van (CV); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
