('Madaris Transportation, LLC','369434','MSSL','Drayage, Intermodal, Rail',NULL,'LARGE STRAIGHT (G3); TRACTOR (G4);  (SV); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Maday Trucking','1309162','MDYW','Drayage, Intermodal, Rail',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Madison Intermodal LLC','670421','MDNW','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Madiu Enterprise LLC','1222835','MAEV','Air Freight, Drayage, Intermodal, Ocean, Rail',NULL,'Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Mae Transport LLC','1089731','1118','Drayage, Intermodal, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Mahogany Logistics','1464596','MHGS','Drayage, Intermodal, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Mainline Transportation & Co, LLC','1090613','MNCH','Drayage, Intermodal, LTL, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Mainline Trucking LLC','1105439','3474','Drayage, Intermodal',NULL,'TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Maj Transportation Inc','1129028','NONE','Intermodal',NULL,'TRACTOR (G4);  (SV)',NULL,NULL,NULL,'0',NULL,'0',NULL,'0',NULL),
('Majestic  Logistics  LLC','103598','MJSM','Drayage',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Majestic Trucking LLC','935158','MJUC','Drayage, Intermodal, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Major Intermodal Inc','1231375','MJIM','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Major League Freight Inc','1298199','MJUE','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Making Moves Express LLC','1750357','3612','Air Freight, Intermodal, LTL',NULL,'TRACTOR (G4); Trailer, Bulk (TB); Trailer, Dry Freight (TF); Trailer, Tank (Food Grade-Liquid) (TK); Trailer (not otherwise specified) (TL)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Makiyo LLC','1168370','MYOK','Drayage, LTL, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Malhi Logistics Inc','1049724','1117','TL',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Mammoth Logistics LLC','074516','MHGB','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Mangat Group Inc','515931','MGGR','Drayage, Intermodal, Truckload',NULL,'Chassis (CH); Controlled Temperature Trailer (Reefer) (RT); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Mango Trucking Company LLC','1095578','1046','Drayage, Intermodal, LTL',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Manna Trucking Inc','016477','MNIW','Drayage, Intermodal',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Manzo Transportation','1034281','2435','LTL, Truckload',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Maracanda Express LLC','1612051','3720','LTL',NULL,'(SV); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Maravillas Transportation LLC','897008','MVSO','Intermodal','03/28/2020',NULL,'Wilmington','CA','Carrier','100,000','04/03/2021','1,000,000','03/28/2020','1,000,000','03/28/2020'),
('Marcello Logistics, Inc.','957618','MRGF','Drayage',NULL,'Chassis (CH)','Westminster','CA','Carrier','200,000','05/30/2021','0',NULL,'0',NULL),
('Margarita Transportation Inc','1058861','MGQT','Air Freight, Drayage, Intermodal, Ocean, Rail, Truckload',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Margo Logistics LLC','1002230','MRGS','Intermodal, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Marin Carrier LLC','1709995','3346','Drayage, Intermodal, LTL, Ocean, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Marine Transport, Inc.','235262','MRPJ','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Maritime  Services,  Ltd.','157885','MRSV','Drayage, Intermodal',NULL,'Chassis (CH); Fixed-Rack, Flat-bed Trailer (RA); Controlled Temperature Trailer (Reefer) (RT);  (SV); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Maritime Delivery Services Inc','594051','MDVC','Drayage, Ocean',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Mark-It Express Logistics LLC','690758','MIEY','Intermodal',NULL,'Chassis (CH); Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Maroli Logistics','1578641','MAZX','Drayage, Intermodal',NULL,'Chassis (CH); Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Marowley Transport LLC','1567568','3257','Drayage, Intermodal, LTL, Rail, Truckload',NULL,'Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Marroquin Trucking Service Inc','859329','2307','Truckload',NULL,'Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Mars Express Lines Inc','1093752','MXSW','Drayage, Intermodal, LTL, Ocean, Parcel, Rail, Truckload',NULL,'Chassis (CH); Flat Bed Trailer (FT); TRACTOR (G4); Controlled Temperature Trailer (Reefer) (RT);  (SV); Trailer, Dry Freight (TF); Truck, Van (TV); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Martin''s Trucking LLC','1358007','1162','Drayage, Intermodal',NULL,'Container (CN); Flat Bed Trailer (FT); TRACTOR (G4); Fixed-Rack, Flat-bed Trailer (RA); Fixed-Rack, Single Drop Trailer (RS); Single-Drop Trailer (SD); Trailer (not otherwise specified) (TL)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Marty Elazer Capp King Mechanical, LLC','807705','1201','LTL',NULL,'TRACTOR (G4);  (SV); Truck, Van (TV); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Marvin Keller Trucking, Inc.','161777','KMTN','Truckload',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Marzett''s Smooth Trucking LLC','1449160','2462','Truckload',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Masa Trucking Co.','392259','MASG','Drayage, Intermodal, LTL','08/28/2020',NULL,'Los Angeles','CA','Carrier','100,000','08/28/2021','1,000,000','08/28/2020','1,000,000','08/28/2020'),
('Masava LLC','1114121','3548','Drayage, Intermodal, LTL, Rail, Truckload',NULL,'Cargo Van (CV); LARGE STRAIGHT (G3); Load/unload Device on Equipment (LU); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Mason And Mefford','259101','MAME','Drayage, LTL',NULL,'Chassis (CH); Cargo Van (CV); Double-Drop Trailer (DD); Flat Bed Trailer (FT); LARGE STRAIGHT (G3); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Master Dispatch & Logistics LLC','1204978','MDLK','Drayage, Intermodal, LTL, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Master Trans Line Inc','739422','MAST','LTL','12/27/2020',NULL,'Montrose','CA','Carrier','100,000','12/27/2020','0',NULL,'1,000,000','12/27/2020'),
('Mather Trucking, Inc.','295119','MTHT','Drayage, Intermodal','11/01/2023','Chassis (CH); TRACTOR (G4);  (SV); Trailer, Dry Freight (TF)',NULL,NULL,NULL,'5,000','11/01/2023',NULL,NULL,NULL,NULL),
('Matrix Inc','750921','MXIK','Air Freight, Cartage',NULL,'Cargo Van (CV);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Maverick Trucking LLC','1311238','MVKI','Air Freight, Drayage, Intermodal, LTL, Ocean, Parcel, Rail',NULL,'Chassis (CH); Container (CN); Flat Bed Trailer (FT); SMALL STRAIGHT (G2); TRACTOR (G4); High Cube Van (HV); Fixed-Rack, Flat-bed Trailer (RA); Controlled Temperature Trailer (Reefer) (RT);  (SV); Trailer, Dry Freight (TF); Trailer, Tank (Chemicals) (TJ); Truck, Van (TV); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Maxi Hauler Corp','1205460','MEFF','Ocean',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Maxie Trucking LLC','1347535','MXLI','Drayage',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Maximus','903806','MAXJ','Intermodal',NULL,'Chassis (CH); Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Maximus Freight Solutions LLC','042853','MFNS','Drayage',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Maximus Transport LLC','1718305','MHXF','Drayage',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Maxlink Logistics Inc','968805','MXLH','Drayage',NULL,'Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Maybach International Group LLC','861485','MIGP','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Mbv Transportation Inc','874172','MBKJ','Drayage, Intermodal, Ocean, Rail',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Mc2 Transportation, LLC','887970','MCZB','Drayage, Intermodal',NULL,'Chassis (CH); Flat Bed Trailer (FT); Fixed-Rack, Flat-bed Trailer (RA)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Mcbride Transport','1185783','MCPT','Truckload',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Mcclendon Logistics Services LLC','1340371','MCDH','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Mccracken Motor Freight, Inc.','000941','MMFG','Intermodal, Rail, Truckload',NULL,'Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Mccray Trucking LLC','172660','MYUL','Drayage, Intermodal',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Mcgee Trucking','657630','MGET','Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Mcilwain Transport LLC','1249892','MWNR','Drayage, Intermodal, Ocean, Rail',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Mckinnons Transport LLC','438725','MKOQ','Drayage, Intermodal, LTL, Parcel, Rail',NULL,'Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Mcx Transport Ny Inc','1094019','MCXR','Drayage',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Mdb Transportation','428691','MDBT','Drayage','06/01/2020',NULL,'Glendale','CA','Carrier','250,000','04/22/2021','1,000,000','06/01/2020','1,000,000','06/21/2020'),
('Mdd Enterprises Grp LLC','1327931','1224','Intermodal, LTL',NULL,'Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Mdot Motor Carriers','1107106','MRYV','Drayage, Intermodal, Ocean, Rail',NULL,'Chassis (CH); Flat Bed Trailer (FT); TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Mdpp Transport LLC','1269136','2478','Drayage',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Mdx Transport Inc','1200233','2523','Truckload',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Me & My Brothers Trucking Corporation','677884','MMRQ','Drayage',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Meazi Express LLC','1340863','2472','LTL, Truckload',NULL,'(SV); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Mecca Transport Inc','661585','AROY','Intermodal, LTL',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Medlog Drayage','268946','CKKI','Drayage, Intermodal, Rail',NULL,'Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Mega Fleet Corp','499871','MFCE',NULL,NULL,'Cargo Van (CV); TRACTOR (G4); Controlled Temperature Trailer (Reefer) (RT);  (SV); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Mega Trucking LLC','916825','MEGA','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Mehr Trucking LLC','1327164','2510','LTL, Truckload',NULL,'TRACTOR (G4);  (SV); Trailer, Dry Freight (TF); Trailer (not otherwise specified) (TL)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Mendez Logistics','1118460','2507','Air Freight, Drayage, LTL, Parcel, Rail, Truckload',NULL,'(SV); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Mendoza C Trucking, Inc','1353840','3671','Drayage, Intermodal, LTL, Rail',NULL,'Cargo Van (CV); Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Mendoza Express LLC','1337935','MEEE','Drayage',NULL,'Chassis (CH); Cargo Van (CV); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Menintrux Transport Services LLC','074404','MXKG','Drayage, Intermodal, LTL',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Mercator Global Logistics LLC','883965','MGBG','Drayage','09/10/2020',NULL,'Elk Grove Village','IL','Carrier','250,000','06/24/2021','1,000,000','09/10/2020','1,000,000','09/10/2020'),
('Merdina Transport LLC','1074635','MZDB','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Meso Trucking','1204250','MEOK','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Metropolitan Transport LLC','742048','MXOL','Drayage, Rail',NULL,'Chassis (CH); Cargo Van (CV); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Mg Trucking Group, Inc','544003','NONE','LTL',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Mga Logistics Corp','1617282','MGCP','Drayage, Intermodal, LTL',NULL,'Chassis (CH); Cargo Van (CV); Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Mga Trucking LLC','683905','1147','Drayage, TL',NULL,'(SV); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Mgr Freight System Inc','576078','MGFY','Drayage',NULL,'Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Mgs Trans Services Inc','737208','2368',NULL,NULL,'Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Mhx - LLC','003409','MHXC','Rail, Truckload',NULL,'Chassis (CH); Flat Bed Trailer (FT); TRACTOR (G4); Load/unload Device on Equipment (LU)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Mi Trucking LLC','703869','MIUM','Intermodal, Rail',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Miami Container Trucking LLC','1508541','MCTJ','Air Freight, Drayage, Intermodal, Ocean, Rail',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Michael L Jr Poole','1051156','MICH','Drayage','08/01/2020',NULL,'Valencia','CA','Carrier','100,000','08/01/2021','1,000,000','08/01/2020','0',NULL),
('Michael Transport Services LLC','1127910','MHPW','Drayage',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Mid Cities Motor Freight, Inc.','145477','MICB','Drayage, Intermodal, LTL, Rail',NULL,'Chassis (CH); TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Mid Lane Carriers Inc','956203','MDLM','Drayage, Intermodal, Ocean',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Middle Bay Transportation','996608','MBYP','Drayage','09/01/2020',NULL,NULL,NULL,NULL,'250,000','09/01/2021','1,000,000','09/01/2020','1,000,000','09/01/2020'),
('Midnight Transportation LLC','1072100','MZDO','Drayage, Intermodal',NULL,'Chassis (CH); Container (CN); TRACTOR (G4); Trailer, Dry Freight (TF); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Midsouth Transit LLC','1021150','MDVA','Drayage, Intermodal',NULL,'TRACTOR (G4); Trailer (not otherwise specified) (TL); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Midwest Cargo Systems, Inc.','146123','MWSC','Drayage, Intermodal, Truckload',NULL,'Chassis (CH); Cargo Van (CV); Controlled Temperature Trailer (Reefer) (RT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Midwest Heavy Transport Inc','956270','MWHA','Drayage, Intermodal',NULL,'(SV); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Midwest Transportation Resources, LLC','434688','MDWT','Drayage, Rail, TL, Warehouse',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Mighty Elephant Transportation  LLC','1238927','MYJO','Drayage',NULL,'TRACTOR (G4); Trailer (not otherwise specified) (TL)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Mike Lindley Trucking LLC','645244','LMTY','Drayage',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Mike Trucking LLC','1302962','MYIV','Drayage, Intermodal',NULL,'Chassis (CH); Container (CN); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Milestone Transportation LLC','1135411','MTBP','Drayage, Intermodal, Rail',NULL,'Chassis (CH); TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Millennium Trucking, Inc.','391099','MIBL','Drayage',NULL,'Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Minotaur Carrier LLC','1375242','MCLH','Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Mirodg Inc','1300942','NONE','LTL',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Mitchell Bros. Truck Line Inc.','032882','MITH','Drayage',NULL,'Chassis (CH); Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Miyah Logistics LLC','1208865','MYHO','Drayage',NULL,'Chassis (CH); Trailer (not otherwise specified) (TL)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Mj Express Logistics LLC','1133698','2403',NULL,NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Mjb Transportation Inc','080694','MJBQ','Drayage','08/07/2021',NULL,'Bakersfield','CA','Carrier','100,000','08/07/2021','1,000,000','08/07/2021','1,200,000','08/07/2021'),
('Mje Express Inc','1254612','1236','Drayage',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Mk Transportation Corp','1613728','3144','Drayage, Intermodal, Ocean',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Mkd Logistics LLC','074132','MKDJ','Drayage',NULL,'Chassis (CH); Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Mkyy Corp','1335339','MKQK','Drayage',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ml Logistics','1543746','2556','LTL',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ml Transportation Service','1055920','MLPY','Air Freight, Cartage, Drayage, LTL, Ocean, Parcel, Truckload',NULL,'SMALL STRAIGHT (G2); Trailer (not otherwise specified) (TL)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Mmm 3 Transport Services Inc','1221001','MTTB','Intermodal',NULL,'Container (CN); Trailer (not otherwise specified) (TL); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Mns Transport Inc','1171951','MQOS','Cartage, Drayage, Intermodal, LTL, Ocean, Parcel, Rail, Truckload',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Mocean Transport LLC','1027209','MOJY','Drayage','09/21/2020',NULL,'Long Beach','CA','Carrier','150,000','09/21/2020','1,000,000','09/21/2020','1,000,000','09/21/2020'),
('Mondo Motion LLC','1149814','2464','Cartage, Drayage, Intermodal',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Moneyline Xpress LLC','683862','MXEH','Drayage, Intermodal',NULL,'TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Monk Transportation, Ltd.','231501','MNKL','Drayage',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Monroy Intermodal Inc','944589','MYIN','Intermodal, Rail',NULL,'TRACTOR (G4); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Monte Express Transport Inc','1049460','MOXH','Drayage, Intermodal',NULL,'TRACTOR (G4)','La Habra','CA','Carrier','100,000','04/01/2021',NULL,NULL,NULL,NULL),
('Montgomery Enterprises & Trucking LLC','987865','1130','Drayage, Intermodal',NULL,'Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Moove Corp.','1132186','2378','Drayage, Intermodal, LTL',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Morataya Transportations','1571149','MPQP','Cartage, Drayage, Intermodal, LTL, Ocean, Rail',NULL,'Chassis (CH); TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Moscoso Express, Inc.','489212','MECO','Air Freight, Cartage, Drayage, Intermodal, LTL, Ocean, Truckload',NULL,'Cargo Van (CV); LARGE STRAIGHT (G3); Load/unload Device on Equipment (LU); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Mountview Transport LLC','1011116','2539','LTL',NULL,'Trailer, Dry Freight (TF); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Moveable LLC','1238571','3611','Cartage, Drayage, Intermodal, LTL, Ocean, Parcel',NULL,'Cargo Van (CV); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Mr B''s Hauling Co LLC','1133641','1080','Drayage, Intermodal, LTL',NULL,'TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Mr Shipping LLC','1229117','MRHA','Drayage, Intermodal, LTL, Parcel, Truckload',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Mr. Frogs Trucking LLC','852728','2329','LTL',NULL,'Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Mri Transportation LLC','803812','MRIP','Drayage, Intermodal',NULL,'Chassis (CH); Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Msh Transport Inc','929099','EVTE','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Msm Logistics LLC','1186021','MVSM','Drayage, Intermodal, Rail',NULL,'TRACTOR (G4);  (SV); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Mt Brothers Group Inc','610776','MTBG','Drayage','07/15/2020',NULL,'La Puente','CA','Carrier','250,000','07/15/2021',NULL,NULL,'1,000,000','07/15/2020'),
('Mt Partners Trucking LLC','849056','MHKK','Drayage',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Mta Transport, Inc.','075032','MUPD','Intermodal, LTL',NULL,'TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Mtf Trucking Corp','1091817','MFPQ','Intermodal',NULL,'Chassis (CH); Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Mtg Transportation LLC','1595989','MGTN','Drayage, Intermodal, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Mti Logistics Inc','065397','MTOQ','Drayage, Intermodal, LTL, Truckload',NULL,'Chassis (CH); SMALL STRAIGHT (G2); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Mti Trucking LLC','1206947','1106','Drayage, Intermodal, Rail',NULL,'Flat Bed Trailer (FT); Single-Drop Trailer (SD)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Mti, Inc. Pa','147923','MTIP','Drayage',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Mtk Transportation Inc','1065216','MKPI','Drayage',NULL,'Chassis (CH)','City Industry','CA','Carrier',NULL,NULL,NULL,NULL,NULL,NULL),
('Mtn Trucking LLC','1298555','MJIT','Drayage',NULL,'Chassis (CH); Container (CN); Cargo Van (CV); Double-Drop Trailer (DD); Flat Bed Trailer (FT); SMALL STRAIGHT (G2); LARGE STRAIGHT (G3); TRACTOR (G4); High Cube Van (HV); Load/unload Device on Equipment (LU); Open Top Van (OV); Fixed-Rack, Flat-bed Trailer (RA); Fixed-Rack, Double Drop Trailer (RD); Fixed-Rack, Single Drop Trailer (RS); Controlled Temperature Trailer (Reefer) (RT); Single-Drop Trailer (SD); Removeable Side Trailer (ST);  (SV); Trailer, Heater/Insulated/Vented (TA); Trailer, Bulk (TB); Trailer, Dry Freight (TF); Trailer, Tank (Gas) (TG); Trailer, Insulated (TI); Trailer, Tank (Chemicals) (TJ); Trailer, Tank (Food Grade-Liquid) (TK); Trailer (not otherwise specified) (TL); Trailer, Insulated/Ventilated (TM); Trailer, Pneumatic (TP); Trailer, Electric Heat (TQ); Truck, Van (TV); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Mtp Logistics LLC','1305673','MLYY','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Mtz Trucking Inc','743596','MNZY','Drayage, Intermodal',NULL,'Container (CN); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Mtz Trucking LLC','1082261','MTZH','Drayage, Ocean',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Mudki Express Inc','794644','1021','Drayage','07/15/2021',NULL,'Lathrop','CA','Carrier','100,000','07/15/2021','0',NULL,'1,000,000','07/15/2021'),
('Muncy Trucking','1134683','MUOF','Cartage, Drayage, Intermodal, LTL, Parcel, Rail, Truckload',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Murari Transport Inc','1589893','MUUN','Drayage, Intermodal, LTL, Rail',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Muuk Logistics Inc','114213','MUUL','Drayage, Ocean',NULL,'Chassis (CH); Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Mws Intermodal Services, LLC','955437','MWST','Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Mxj Enterprises','1249074','MENB','Drayage',NULL,'Chassis (CH); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('My Family Trucking LLC','1395338','MFTJ','Drayage, Intermodal',NULL,'Chassis (CH); Container (CN); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('My Intermodal LLC','1701297','MYJL','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Myers Made Trucking LLC','1322280','1124','Drayage',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('N & J Trucking','289084','1225','LTL',NULL,'Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('N & L Express LLC','1184562','NONE',NULL,NULL,'(SV); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('N & S Trucking','548553','NSTY','Drayage','06/17/2021',NULL,'Montebello','CA','Carrier','100,000','06/17/2021','0',NULL,'1,000,000','06/17/2021'),
('N Ravenell Trucking LLC','1312869','RVKK','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('N3y Corp','1468842','NYVT','Drayage, Intermodal, LTL, Ocean, Truckload',NULL,'Chassis (CH); Cargo Van (CV); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Nandini K Express LLC','1019197','2504','Drayage, Intermodal, TL',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Naperville Trucking LLC','1592499','NAPR','Drayage, LTL',NULL,'Flat Bed Trailer (FT); Single-Drop Trailer (SD)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Napoleon Trees Hauling''s & Sales Inc','584811','NTHS','Drayage, Intermodal, LTL, Ocean, Rail',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Narwal Trucking','873803','NWLG','Drayage, Intermodal, Ocean',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Nasa Logistic LLC','1163346','NASA','Drayage, Intermodal',NULL,'Chassis (CH); Container (CN); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('National Drayage Services (De), LLC','639627','NDSV','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('National Loads Corp','1041472','NLCW','Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Nationwide Logistics LLC','733838','NWLW','TL',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Nationwide Xpress Inc','1122089','NXIE','Drayage, Intermodal, LTL, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Nav Express Inc','1210067','2487','Truckload',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Nav Freight Inc','1449226','NFRC','Drayage, Intermodal, Ocean, Rail',NULL,'Chassis (CH); Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Navak Transportation LLC','1572528','3026','Drayage, Intermodal, LTL',NULL,'TRACTOR (G4); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Navigate Transportation Inc','1488838','2337','LTL, Truckload',NULL,'Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Nbbl Group Inc','809986','NBBL','Drayage, Intermodal',NULL,'Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ncn Transport Inc.','559473','NCNP','Drayage',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Neema Express LLC','066702','NEND','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Neichev Logistics LLC','1449399','2391','Intermodal, LTL',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Neri Logistics LLC','518400','1176','Truckload',NULL,'TRACTOR (G4);  (SV); Trailer, Dry Freight (TF); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Network Trucking LLC','1192510','2544','LTL',NULL,'LARGE STRAIGHT (G3); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Never Alone Transport LLC','1152230','1044','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('New Age Moving Co','1193624','1090','LTL',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('New Opportunities Trucking Inc','1094729','NOTQ','Drayage',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('New Royal Transport Inc','1165969','1255','Intermodal',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('New Sun Transport Corp','1050931','2481','Drayage, Intermodal, Rail',NULL,'Chassis (CH);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('New Testament Logistics LLC','518080','NTLI','LTL, Truckload',NULL,'High Cube Van (HV); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('New Transport Logistics','1118223','NEZD','Drayage, Intermodal, Rail',NULL,'Chassis (CH); TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('New World Drayage Inc','624948','NWDW','Drayage',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Newton Transport LLC','1045547','NEWT','Drayage, Intermodal','06/25/2020',NULL,'Hawthorne','CA','Carrier','100,000','06/25/2021','1,000,000','06/25/2020','1,000,000','06/25/2020'),
('Nexgen Trucking Inc','075659','NXGK','Drayage, Intermodal','05/08/2020','Trailer, Dry Freight (TF)','Carson','CA','Carrier','250,000','05/08/2021','1,000,000','05/08/2020','1,000,000','05/08/2020'),
('Next Generation Transportation Services LLC','1274352','NGAO','Drayage, Intermodal',NULL,'Chassis (CH); Container (CN); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Next Level Freight LLC','1318850','2447','LTL',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Next Mile Logistics','1017312','REFQ','Drayage, Intermodal, Rail',NULL,'Chassis (CH); Container (CN); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Next Unlimited Trucking Service LLC','1101771','NXUT','Drayage',NULL,'(SV); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Nexus Transportation LLC','1042965','2420','LTL, Truckload',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ngd Logistics LLC','1139515','NGDS','Drayage, Intermodal, Truckload',NULL,'Chassis (CH); TRACTOR (G4); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ngl Transportation LLC','583458','NGLN','Drayage, Intermodal, LTL',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Nht Transport LLC','122959','NHBP','Drayage, Intermodal, Rail',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Nickey Transportation, LLC','646348','NKYT','Drayage, Intermodal, LTL, Ocean, Rail, Truckload',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Nita Logistic LLC','1676644','3259','Drayage, Intermodal, Rail',NULL,'Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('No Limits LLC','1042809','NLBW','LTL, Truckload',NULL,'Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Noble Transport LLC','1045928','2390','Air Freight, Cartage, Truckload',NULL,'LARGE STRAIGHT (G3)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Nolan Logistics Inc','1301269','NNLI','Drayage, Intermodal, Rail',NULL,'Chassis (CH); TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Nonstop Trucking Inc','996090','NNST','Truckload',NULL,'TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Noor Pheonix LLC','1155323','1104','LTL',NULL,'Cargo Van (CV); SMALL STRAIGHT (G2); LARGE STRAIGHT (G3);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Norfleet And Nelson Trucking LLC','1217041','NANH','Intermodal',NULL,'Flat Bed Trailer (FT); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Norfleet Transportation, LLC','399412','NRFT','Drayage, Intermodal, LTL',NULL,'Cargo Van (CV); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('North America Lines Inc','749205','2497',NULL,NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('North Shore Transportation Co., Inc.','171441','NOHE','Drayage',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Northern Atlantic Logistics LLC','1278450','NAJG','Drayage, Intermodal, Rail',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Northstar Transport LLC','680909','1153','Drayage',NULL,'TRACTOR (G4); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Northwest Carrier Express LLC','553683','NCEC','Drayage',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Nosleep Logistics LLC','1136585','NSPT','Drayage, Intermodal, Ocean, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Nova Start Inc','1373344','2331','LTL, Truckload',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Npc Trucking Inc','021916','NTXS','Drayage, Intermodal, Rail',NULL,'Cargo Van (CV);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Nrg Trucking Company','915234','NRGW','Air Freight, Drayage, Intermodal',NULL,'(SV); Trailer, Dry Freight (TF); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ns Trucking Inc','852766','2410','TL',NULL,'Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Nte Services Corp','757206','NTEV','Drayage, Ocean',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Nts','642014','NTSW','Drayage, Intermodal, Rail',NULL,'Chassis (CH); Container (CN); Cargo Van (CV);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Nu Chapter Transport LLC','1118951','2284','Drayage, Intermodal, Rail',NULL,'TRACTOR (G4); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Nu Lyfe Trucking LLC','977980','NLFB','Drayage',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Nur Transport Inc','1312351','NTUA','Drayage, Intermodal, Ocean',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Nv Logistics Inc','1087634','NVLC','Drayage, LTL',NULL,'(SV); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Nvk Logistics Inc.','424428','NVKP','LTL','05/21/2026','(SV); Trailer, Refrigerated (TW)',NULL,NULL,NULL,'4,000,000','05/21/2026',NULL,NULL,NULL,NULL),
('O Grinhard Trucking Inc','1198176','GOTN','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('O Medina Trucking','1098071','2742','Cartage, Drayage',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('O&j Logistic LLC','1120685','2387',NULL,NULL,'TRACTOR (G4);  (SV); Trailer, Dry Freight (TF); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('O''neill Logistics Transportation Ca LLC','951408','ONLJ','Drayage',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('O5 Express Inc','1003568','OFOP','Drayage, Intermodal, Rail',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Oakland Container Trucking','038220','OAKR','Drayage',NULL,'Chassis (CH); Container (CN); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Oasis Port Transportation, Inc','1151706','OASY','Drayage, Intermodal, LTL, Rail',NULL,'Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ocean Bridge Transport LLC','983435','OBTI','Drayage, Intermodal, Ocean',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ocean Connect Cartage','1552036','OCEF','Cartage, Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ocean Express Transportation','500331','1217','Drayage',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Oddy Ann Denise Trucking LLC','1053644','OADK','Drayage',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Off Ramp Truck LLC','577350','ORTW','Drayage, Intermodal, Ocean',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ofori''s Trucking LLC','053349','OFKC','Drayage, Intermodal, Rail',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Oh Macon Express LLC','1353661','2498','Drayage, Intermodal, Rail',NULL,'Chassis (CH); Cargo Van (CV);  (SV); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ohio Intermodal Services LLC','937260','OISC','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ojeda''s Transport LLC','131696','OJDA','Drayage','03/07/2020',NULL,'Whittier','CA','Carrier','100,000','04/01/2021','1,000,000','06/01/2020','100,000','03/07/2020'),
('Ol Transportation LLC','075878','OITL','LTL','12/26/2020',NULL,'Cleveland','TX','Carrier','100,000','12/26/2020','1,000,000','12/26/2020','1,000,000','12/26/2020'),
('Olb Transport Corp','1233734','OLBC','Drayage, Intermodal',NULL,'Chassis (CH); Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Old Brother Truckers LLC','1199974','1261','Drayage, Intermodal, LTL, Ocean, Parcel, Rail',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Old Empire Inc','1041482','NONE','Drayage, LTL',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Old West Transport Inc','079216','OWTS','Drayage, Intermodal, Ocean',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Oliva And Company Inc','0577218','OACA','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Om Cornavaca Transportation LLC','1418135','OCTO','Drayage',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Om Trucking','0445680','2450','TL',NULL,'(SV); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Omarion Logistics, LLC','1174121','OMNJ','Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('On Going Express','585483','OGEX','LTL',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('On My Way Trucking LLC','1106650','OMWT','Drayage, Intermodal',NULL,'Chassis (CH);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('On Point Transportation LLC','707713','OPTN','Drayage, Intermodal, LTL',NULL,'Chassis (CH); TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('On Site Logistics','1228188','1258','Truckload',NULL,'Flat Bed Trailer (FT); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('On Time Truckers Inc','658578','OTTM','Intermodal, LTL, Ocean',NULL,'Container (CN); Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
ON CONFLICT (scac) DO NOTHING;

INSERT INTO mg_carriers (name,mc_number,scac,modes,early_ins_exp,equipment,loc_city,loc_state,loc_type,cargo_ins_amt,cargo_ins_exp,general_ins_amt,general_ins_exp,liability_ins_amt,liability_ins_exp) VALUES
('On Track Express LLC','888633','1084','Drayage',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('One Call Transport LLC','053679','2405','Drayage',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('One Love Transportation Services, LLC','977195','OLTV','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('One Way Logistics Inc','1129965','2457','LTL',NULL,'(SV); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('One West Logistics Inc','1235956','OWLS','Drayage, Intermodal, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ontiveros Trucking Inc','1153863','1095','Drayage',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Open Highway Transport LLC','1239401','OHTJ','Drayage, Intermodal, Rail',NULL,'TRACTOR (G4); Trailer, Bulk (TB); Trailer, Dry Freight (TF); Trailer (not otherwise specified) (TL)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Opt Logistics Inc','1078009','OLIJ','Drayage, Intermodal, LTL, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Optimal Transportation, Inc','1071013','OPMN','Drayage, Intermodal, Ocean',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Orange Courier Inc.','327888','ORGC','Drayage, Intermodal, LTL, Parcel, Rail',NULL,'Chassis (CH); Cargo Van (CV); Double-Drop Trailer (DD); SMALL STRAIGHT (G2); LARGE STRAIGHT (G3); TRACTOR (G4); Fixed-Rack, Flat-bed Trailer (RA); Controlled Temperature Trailer (Reefer) (RT); Single-Drop Trailer (SD)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ord Trans Inc','797356','ORDN','Air Freight, LTL, Truckload',NULL,'Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Orozco Trucking Inc','681958','OROZ','Drayage','06/01/2021',NULL,'Elk Grove Village','IL','Carrier','250,000','06/01/2021','1,000,000','10/11/2021','1,000,000','06/01/2021'),
('Orozcos Trucking','755993','3253','Drayage, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ortas Trucking','0473614','ORSK','LTL','09/23/2020',NULL,'Los Angeles','CA','Carrier','100,000','09/23/2020','0',NULL,'1,000,000','09/23/2020'),
('Oruc Logistics LLC','963752','ORCS','Drayage, Intermodal, LTL',NULL,'Chassis (CH); Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Oryan Trucking Inc','1041356','1240','Drayage',NULL,'Chassis (CH); Container (CN); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Osvego Inc','969524','2561','LTL',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Otac Warehousing And Logistics','1092057','OWAL','Drayage',NULL,'Cargo Van (CV); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Otss Express LLC','1304390','OEAJ','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ozone Trucking LLC','1163242','OZNG','Intermodal, Rail',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('P & Family LLC','1258755','2371','Drayage, Rail',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('P & T Savannah Trucking LLC','1247540','PVHK','Drayage',NULL,'Chassis (CH); Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('P G R Transportation Inc','1135501','1168','Drayage',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('P I Xpress Inc','540639','PICF','Ocean',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('P K Transport','1368998','2266','Drayage, Intermodal, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('P Moreno Transportation LLC','0623684','3694','Drayage, Intermodal, Rail',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('P U S H','895970','PUSH','Drayage, Intermodal',NULL,'Chassis (CH); Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('P&P Transport LLC','1393138','PPZC','Air Freight, Drayage',NULL,'Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('P&e Freight Co, Inc.','1056615','PEFO','Drayage',NULL,'Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('P. B. Express, Inc.','259674','PBXI','Drayage, Intermodal, Rail',NULL,'Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('P. L. R. Transport, Inc.','186964','1203','Drayage, Intermodal, LTL',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Pa Carriers Inc','137420','PCIR','Drayage, Intermodal, Ocean, Rail',NULL,'Chassis (CH); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Pac Anchor Transportation, Inc.','486876','PCAK','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Pace Transportation Services LLC','1121493','PCND','Truckload',NULL,'Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Pacheco Services Inc','844272','PCVQ','Drayage, Intermodal, Rail',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Pacific Drayage Services LLC','1045744','PIDA','Drayage, Intermodal','12/01/2020',NULL,'Memphis','TN','Carrier','100,000','05/01/2021','1,000,000','12/01/2020','1,000,000','01/01/2021'),
('Pacific Expressway, Inc.','405190','PCFE','Drayage','12/30/2020','Chassis (CH); TRACTOR (G4)','West Covina','CA','Carrier','100,000','12/30/2020','1,000,000','12/30/2020','1,000,000','12/30/2020'),
('Pacific Freight Logistics Inc','827941','PFLI','Drayage','11/20/2020',NULL,'Bell Gardens','CA','Carrier','100,000','11/20/2020','1,000,000','11/20/2020','1,000,000','11/20/2020'),
('Pacific Green Trucking Inc','692174','PGKI','Drayage, Ocean, Rail',NULL,'Chassis (CH); Flat Bed Trailer (FT); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Pacific Merchant Transport LLC','1489015','PFMD','Drayage, Intermodal, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Pacific Ocean Lines, Inc','782645','PONL','Drayage, Intermodal','10/19/2020',NULL,'Fairfield','CA','Carrier','250,000','10/19/2020','1,000,000','10/19/2020','1,000,000','10/19/2020'),
('Pacific Trans Express Corp','085265','PAFA','Drayage, Intermodal',NULL,'Chassis (CH); Double-Drop Trailer (DD); Flat Bed Trailer (FT); TRACTOR (G4)','Wilmington','CA','Carrier',NULL,NULL,NULL,NULL,NULL,NULL),
('Packard Specialized Carriers LLC','736648','2322','Drayage, Intermodal, LTL, Rail, Truckload',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Padilla Trucking LLC','1199403','PDKC','Drayage, Intermodal',NULL,'Chassis (CH); Container (CN); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Paige Global Logistics','1333908','PCSW','Air Freight, Cartage, Drayage, Intermodal, LTL, Parcel, Truckload',NULL,'Cargo Van (CV); Flat Bed Trailer (FT); LARGE STRAIGHT (G3); TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Palma Trucking LLC','677438','PMKY','Drayage, Intermodal, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Pamela And Anthony Carries LLC','1303953','PBDY','Drayage, Intermodal',NULL,'TRACTOR (G4); Single-Drop Trailer (SD); Trailer (not otherwise specified) (TL); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Pan Ocean Freight Systems Inc','834859','POFS','Drayage',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Paper Soldiers Ss LLC','1116049','PSAD','Intermodal, LTL, Truckload',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Paperboie Trucking LLC','1302111','PAHY','Drayage',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Paperchase X-Press Trucking Company LLC','084670','1048','Drayage',NULL,'Container (CN); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Paradox Logistics LLC','1257711','PLVQ','Drayage, Intermodal, Rail',NULL,'Container (CN); Cargo Van (CV);  (SV); Trailer, Tank (Food Grade-Liquid) (TK)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Paragistics Freight Company LLC','1225252','PFJH','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Paramount Intermodal Systems Inc','784567','PISN','Drayage',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Paramount Logistics Inc','852992','PARB','Drayage, Intermodal',NULL,'Chassis (CH); Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Park & Go Co','045014','PARK','Drayage','10/23/2020',NULL,'Chicago','IL','Carrier','100,000','10/23/2020',NULL,NULL,'1,000,000','10/23/2020'),
('Park Avenue Intermodal LLC','839011','PAIM','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Patriot Logistics Inc','438147','PATG','Drayage',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Paul A Chang','919894','CGPP','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Paul Trucking Corp','059914','3770','Drayage, Intermodal, Rail',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Pb07 Logistics','1249366','2541','LTL',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Pcc Logistics','274237','PCCN','Drayage, Intermodal, LTL, Rail',NULL,'Chassis (CH); Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Pch 1 Transport','1173911','PCHO','Drayage, Intermodal, Ocean, Rail',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Pcs Trucking, LLC','240110','PFCD','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Pdc Trucking Inc','1072957','PTXK','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Pdj Carriers Llp','1242111','PCUM','Drayage',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Pdj Express LLC','1480518','PDJJ',NULL,NULL,'Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Pdp Trucking Inc','694987','PDPT','LTL','06/29/2021',NULL,'Cedar Hill','TX','Carrier','250,000','07/01/2021','2,000,000','06/29/2021','1,000,000','07/01/2021'),
('Peace Keeper Trucking LLC','1538774','PEBQ','Drayage, Intermodal, LTL',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Peloton Express, Inc.','335333','PEJE','Drayage, Intermodal, Ocean',NULL,'Chassis (CH); Flat Bed Trailer (FT); TRACTOR (G4); Controlled Temperature Trailer (Reefer) (RT); Trailer (not otherwise specified) (TL)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Penate Fam Trucking LLC','1625708','PFTH','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Penn Boyz Transportation LLC','1066370','1262','Drayage, Intermodal, LTL, Rail',NULL,'Chassis (CH); Container (CN); Controlled Temperature Trailer (Reefer) (RT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Penn Intermodal','242115','BWYV','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Pentagon Logistics Inc','548406','PICI','LTL, Truckload',NULL,'Flat Bed Trailer (FT); TRACTOR (G4); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Perbleto LLC','1095423','2429','TL',NULL,'(SV); Trailer, Bulk (TB); Trailer, Dry Freight (TF); Trailer, Insulated (TI); Trailer, Insulated/Ventilated (TM); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Perfect Lif3 LLC','1070687','2377',NULL,NULL,'Container (CN);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Persistence LLC','1070131','3249','Drayage, Intermodal, LTL, Rail, Truckload',NULL,'Cargo Van (CV); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Pg Trucking','0504375','1207','Truckload',NULL,'Chassis (CH); Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Phase Ii Transportation, Inc.','325249','PHSN','Drayage, Intermodal, Rail','04/13/2026','Chassis (CH); Flat Bed Trailer (FT); TRACTOR (G4);  (SV); Trailer, Dry Freight (TF)',NULL,NULL,NULL,'100,000','04/13/2026',NULL,NULL,NULL,NULL),
('Philly Line Express Inc','667564','2265','Other, TL Dry','11/25/2022','VAN (G1)',NULL,NULL,NULL,'100,000','11/25/2022',NULL,NULL,'1,000,000','11/25/2022'),
('Phipps Transport Inc','057508','PTUN','Drayage, Truckload',NULL,'Chassis (CH); TRACTOR (G4);  (SV); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Phoenix Trans Services Corp','1578740','PHQD','Drayage, Intermodal',NULL,'Chassis (CH); Container (CN); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Phoenix Transportation & Logistics Inc','1194962','1133','Drayage',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Phyxius Logistics Inc','983898','PYXL','Drayage, Intermodal, Rail',NULL,'Chassis (CH); Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Piazza Trucking','231685','PZZA','Truckload',NULL,'TRACTOR (G4); Trailer (not otherwise specified) (TL)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Pier Link System, Inc.','896722','PLSM','Drayage, Truckload',NULL,'Chassis (CH); TRACTOR (G4); Trailer, Bulk (TB); Trailer (not otherwise specified) (TL)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Pier Ratz Trucking LLC','684660','PRZL','Drayage',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Piggyback Service Co.','369006','PGYB','Intermodal, Truckload',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Pin Point Logistics Inc','034912','1083','LTL',NULL,'Cargo Van (CV);  (SV); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Pin To Pin Trucking LLC','1471887','PPCF','Intermodal, Ocean',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Pinch Intermodal LLC','841557','PILQ','Drayage, Intermodal',NULL,'Chassis (CH); Flat Bed Trailer (FT); Single-Drop Trailer (SD)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Pinch Runner Freight Solutions LLC','1213826','PRFQ','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Pinkney Logistical Holdings LLC','1257312','1160','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Pinos Transport LLC','1619622','PIOE','Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Pinto Transfer & Packing Corp.','710205','PTPG','Drayage, Intermodal','07/01/2020',NULL,'Doral','FL','Carrier','250,000','07/01/2021','1,000,000','07/01/2020','1,000,000','07/01/2020'),
('Pioneer Transport, Inc.','197249','PTPW','Cartage, Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Piramid Trucking Inc','841592','NONE','Drayage',NULL,'Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Platinium Logistics Services Inc','1417994','2335','LTL',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Platinum Cartage, Inc.','793978','PCAN','Drayage, Ocean',NULL,'(SV); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Players Exclusive Logistics LLC','1237845','PYEI','Drayage, Intermodal, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Plentitude Transportation Inc','1063918','PNDH','Drayage, Intermodal','06/27/2021',NULL,'Huntingtn Bch','CA','Carrier','100,000','06/27/2021','1,000,000','06/27/2021','1,000,000','06/27/2021'),
('Plh Logistics LLC','1237564','1127','Drayage, Intermodal, LTL, Parcel, Truckload',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Pluma Blanca Transport','1695675','3789','Drayage',NULL,'TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Pma Express LLC','1282273','PEJP','Drayage, Intermodal, Rail',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Pms Logistics LLC','093299','PMLK','Drayage, Intermodal, Rail',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Pod Logistics Incorporated','043068','PODC','Drayage, Intermodal, Ocean, Truckload',NULL,'Chassis (CH); Cargo Van (CV); TRACTOR (G4); Controlled Temperature Trailer (Reefer) (RT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Point Logistics, LLC','849596','PLIJ','Air Freight, Truckload',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Pointe 2 Pointe Transport LLC','1324302','POGW','Air Freight, Cartage, Drayage, Intermodal, LTL, Ocean, Rail',NULL,'Chassis (CH); Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Pointman Trucking LLC','1327299','POHD','Drayage, Intermodal, Ocean, Rail',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ponce Transport Services LLC','1412826','2552','Drayage, Rail',NULL,'Chassis (CH); Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Port City Transportation','174301','POCM','Drayage, Intermodal','06/01/2025','Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,'10,000','06/01/2026',NULL,NULL,NULL,NULL),
('Port Connect Intermodal Inc','1438763','PCBG','Drayage, Intermodal, Rail',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Port Fleet','1114817','PFXE','Drayage, Rail',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Port To Port Transport LLC','1242882','PPAO','Drayage, Rail',NULL,'Chassis (CH); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Port Transport Intermodal, Llc.','715389','PXIL','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Porter Hauling LLC','1298343','PHBJ','Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Potro Trucking Inc','107432','2325','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Powell''s Trucking LLC','905226','POFJ','Intermodal',NULL,'Chassis (CH); Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Power Haul LLC','1170732','PHCJ','Drayage, LTL, Parcel, Rail',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Power Transporting LLC','114330','PWBJ','Drayage',NULL,'Chassis (CH); Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Prado Logistics Inc','1119085','PDOJ','Drayage, LTL, Rail',NULL,'Chassis (CH); Cargo Van (CV); TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Precise Logistics','1230737','3204',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Precise Logistics LLC','1230737','PCLG','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Precise Transportation Inc','893086','PR01','Drayage','08/01/2020',NULL,'Asheville','NC','Carrier','150,000','01/14/2021','1,000,000','02/01/2021','2,000,000','08/01/2020'),
('Precision Transport LLC','772686','3104','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Precision Worldwide Logistics, Inc.','1012608','PWLB','Drayage',NULL,'Chassis (CH); Cargo Van (CV); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Preferred Carrier Of California','051464','PCOR','Air Freight, Cartage, Drayage, Intermodal, LTL, Ocean, Parcel, Rail, Truckload',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Preferred Transport & Distribution, Inc.','239652','PRPD','Drayage, LTL, Truckload',NULL,'Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Premier Fuel Delivery Service','024117','1022','Drayage','01/20/2021',NULL,'Riverside','CA','Carrier','100,000','01/20/2021','1,000,000','01/20/2021','1,000,000','01/20/2021'),
('Premier Haulers LLC','1157646','PMHH','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Premier Lines Inc','635521','2304','LTL',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Prescott Trucking LLC','1232473','PSYY','Intermodal, LTL, Truckload',NULL,'Flat Bed Trailer (FT); TRACTOR (G4); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('President','1480361','2353','Drayage',NULL,'Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Presidential Transport','107930','PRIR','Drayage, Intermodal, Rail, Truckload',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Prestige','553373','PREW','Drayage',NULL,'Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Prevalent Logistics Inc','900289','PREA','LTL, Ocean, Truckload',NULL,'Chassis (CH); TRACTOR (G4); Trailer (not otherwise specified) (TL)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Prime Freight LLC','1119401','1195','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Prime Logix','893630','PIME','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Prime Time Auto Transport LLC','770004','1222','Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Prime Time Trucking Tsa LLC','1246084','PTMW','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Pro Group Logistics','1061781','JLOK','Drayage, Intermodal, LTL','11/27/2020',NULL,'Sparks','NV','Carrier','100,000','11/27/2020','1,000,000','11/27/2020','1,000,000','11/27/2020'),
('Pro Trans Freight Solutions Inc','1411018','PFST',NULL,NULL,'(SV); Trailer (not otherwise specified) (TL)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Pro Transport Charleston, Inc.','621650','PCHI','Drayage, Intermodal, Rail',NULL,'Chassis (CH); Container (CN); Fixed-Rack, Flat-bed Trailer (RA); Trailer, Bulk (TB); Trailer (not otherwise specified) (TL); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Pro-Formance Intermodel Inc','043643','PFTW','Air Freight, Drayage, Intermodal, Ocean, Rail, Truckload',NULL,'Chassis (CH); Container (CN); Controlled Temperature Trailer (Reefer) (RT);  (SV); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Progression Transport LLC','1237397','PROG','Intermodal, LTL',NULL,'Chassis (CH); Flat Bed Trailer (FT); TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Prolific Logistics','1096742','PLOF','Drayage, Intermodal',NULL,'TRACTOR (G4); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Prolific Trucking LLC','1320271','1125','Drayage',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Pros And Cons Trucking LLC','863999','PNDY','Intermodal',NULL,'Controlled Temperature Trailer (Reefer) (RT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Prospect Trans Inc','1280377','PPCW','Drayage, Intermodal, Ocean',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Prospect Transportation Inc','1003646','1170','Drayage, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Protrust Logistics LLC','1532346','2964','LTL',NULL,'TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Proud Logistics LLC','127670','PLLQ','Drayage, Intermodal, LTL',NULL,'Chassis (CH); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Psg Transport Inc','1009601','1112','TL',NULL,'(SV); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ptp Logistics  LLC','005947','PPLD','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Punia Freight Line Inc','1049986','2486','Truckload',NULL,'TRACTOR (G4);  (SV); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Punjab Express Inc','113138','PJBE','Drayage',NULL,'Chassis (CH); Container (CN)','Old Bridge','NJ','Carrier',NULL,NULL,NULL,NULL,NULL,NULL),
('Purpose Logistics Limited','1215165','PPNL','Air Freight, Drayage, Intermodal, LTL, Ocean, Parcel, Rail, Truckload',NULL,'TRACTOR (G4); Controlled Temperature Trailer (Reefer) (RT); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Pvl Universal Inc','920337','3691','LTL',NULL,'Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Pyramid Trucking Inc.','1092473','PTYX','Drayage, Intermodal, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Q-Logistics And Services LLC','1385207','QLAA','Drayage',NULL,'Chassis (CH); Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Qamar Trucking','1019313','QTRN','Drayage, Intermodal, Ocean, Rail',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Qfs Transportation LLC','683552','QFSR','Drayage, Intermodal','06/27/2021',NULL,'Greendale','IN','Carrier','250,000','07/01/2021','1,000,000','06/27/2021','1,000,000','06/27/2021'),
('Quad Logistics LLC','917513','QLLC','Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Quaker Transport, Inc.','287214','QUAK','Cartage, Drayage, Intermodal',NULL,'Chassis (CH); Flat Bed Trailer (FT); TRACTOR (G4); Trailer, Bulk (TB)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Quality Control Trucking Inc','0597845','1228','Drayage, Intermodal, LTL',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Quality Transportation Services Qts, LLC','1262074','QTAD','Drayage, LTL',NULL,'Chassis (CH); Cargo Van (CV); TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Quality Wheels LLC','1476571','QWHA','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Quasar Publishing LLC','1583777','3258','Drayage',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Queens Transportation LLC','1295261','QTAJ','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Quick Pick Transportation Inc','927841','QPAB','Intermodal',NULL,'Container (CN); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Quick Transport','709954','QTRT','Drayage, Intermodal, LTL',NULL,'(SV); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Quickway Transportation, Inc.','341699','QWYT','Drayage',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Quintana Logistics Inc','1001269','2428','LTL',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Qx Logistix LLC','1036799','QXLC','Drayage, Intermodal',NULL,'Chassis (CH); Container (CN); Cargo Van (CV); LARGE STRAIGHT (G3); TRACTOR (G4); High Cube Van (HV); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('R & B Trucking Inc','629090','1041','Drayage',NULL,NULL,'Fresno','CA','Carrier',NULL,NULL,NULL,NULL,NULL,NULL),
('R & M Trucking Inc','0539028','2396','Air Freight, LTL, Truckload',NULL,'TRACTOR (G4); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('R & N Bellamy LLC','1311116','1139','Drayage, Intermodal',NULL,'Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('R & Q Transportation LLC','203184','RQTN','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('R & R Transport Services Inc','291801','RRMP','Intermodal, LTL',NULL,'Cargo Van (CV);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('R And S Logistics LLC','1317566','RAKB','Drayage',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('R C Freight Line Inc','1279754','2422','LTL',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('R C Transportation Inc.','522439','RCTQ','Drayage, Intermodal, Ocean, Rail',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('R Castaneda Transport LLC','1379714','2297','Drayage',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('R D M Express LLC','1526087','3812','LTL',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('R D T Transportation LLC','991555','RDTQ','Drayage, Intermodal, Parcel',NULL,'TRACTOR (G4);  (SV); Trailer, Dry Freight (TF); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('R E E L Transport','836808','1023','Drayage','09/12/2020',NULL,NULL,NULL,NULL,'100,000','09/12/2021','0',NULL,'1,000,000','09/12/2020'),
('R Hernandez Express Inc','1263477','2306','Intermodal, LTL',NULL,'Flat Bed Trailer (FT); Single-Drop Trailer (SD)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('R M T Trucking LLC','1141267','1166','Drayage, Intermodal',NULL,'TRACTOR (G4); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('R Q G Trucking Inc','1424822','2340','Drayage, Intermodal, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('R R Enterprises','1120295','RRPS','Drayage, Intermodal',NULL,'SMALL STRAIGHT (G2); TRACTOR (G4);  (SV); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('R Transport','1281472','ROPB','Drayage',NULL,'LARGE STRAIGHT (G3); TRACTOR (G4); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('R Wilson Hauling LLC','1378837','1182','Drayage, Intermodal',NULL,'Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('R&E Express Inc','1435682','2317','Drayage, Intermodal, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('R&G De La Torre Trucking LLC','1481352','2290','Drayage, Ocean, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('R&G Logistics Inc','1331913','RGLE','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('R&R Trans Inc','047554','RROI','Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('R&S Trucking & Logistics LLC','1105017','RSTI','Drayage, Intermodal',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('R&e Transport LLC','1459059','REZA','Drayage, Intermodal, LTL, Parcel, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('R&t Trucklines Inc','1576534','RTUE','Intermodal',NULL,'Container (CN); Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('R. H. Stover Transport Services, Inc.','508722','SQVH','Drayage, Intermodal, Truckload',NULL,'Chassis (CH); Double-Drop Trailer (DD); Fixed-Rack, Single Drop Trailer (RS)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('R. R. Plett Trucking Ltd.','282553','PTRR','Drayage',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('R.P.R Trucking LLC','960881','RPRB','Drayage, Intermodal, LTL, Rail',NULL,'Chassis (CH)',NULL,NULL,NULL,'0',NULL,'0',NULL,'0',NULL),
('R2r Intermodal Inc','595400','RIIL','Intermodal',NULL,'Chassis (CH); Cargo Van (CV); Load/unload Device on Equipment (LU)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ra Trans Group LLC','1188380','RNAR','Air Freight, Drayage, Intermodal, Rail, Truckload',NULL,'Container (CN); Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Rabbit''s Transport, Inc','015042','RALB','Drayage, Intermodal, Ocean, Truckload',NULL,'Chassis (CH); Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Rahim Transport LLC','1332326','RTBS','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Rail Connect Transportation & Distrib. Svcs. Inc.','126-850-860','RCON','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Railport Services, LLC.','670621','TLVL','LTL',NULL,'Chassis (CH); Cargo Van (CV); Flat Bed Trailer (FT); Load/unload Device on Equipment (LU); Trailer, Bulk (TB); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Rain Or Shine Trans Inc','1058136','ROJD','Drayage, Intermodal, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Raincity Transport LLC','089507','RTYP','Air Freight, Cartage, Drayage, Intermodal, LTL, Ocean, Rail, Truckload',NULL,'Chassis (CH); Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Raj''s Delivery Enterprise, LLC','770056','RSDS','Drayage, Intermodal',NULL,'Chassis (CH); Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Rajo Transportation LLC','1209052','RJBH','Drayage, Intermodal',NULL,'Chassis (CH);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ram Enterprise Express Trucking LLC','1332870','REUV','Drayage, Intermodal, Rail',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ram Tranz LLC','1629478','RANL','Drayage, Intermodal, Rail',NULL,'(SV); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ramirez Express Inc','1300466','RMZE','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ramos Trucking','716049','NONE','TL',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Randev Enterprise Inc','1035465','RDVD','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Rangel Freight LLC','1498299','2281','Intermodal, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ranokx Logistics Inc','681983','RXLQ','Drayage, Intermodal, LTL, Ocean, Rail',NULL,'Chassis (CH); Container (CN); Controlled Temperature Trailer (Reefer) (RT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Rapid Freight LLC','657475','RFAE','Drayage, Intermodal, LTL','09/09/2020',NULL,'Vancouver','WA','Carrier','250,000','10/01/2021','1,000,000','09/09/2020','1,000,000','09/09/2020'),
('Rapid Intermodal LLC','1368162','3184','Drayage, Intermodal',NULL,'Chassis (CH); Flat Bed Trailer (FT); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Rapid Supply Logistics LLC','1440869','RPSP','LTL, Truckload',NULL,'Cargo Van (CV); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Rapid Transport LLC','929817','RPDQ','Drayage, Intermodal, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ravan Transit LLC','1212600','RVNS','Drayage, Intermodal',NULL,'Chassis (CH); Container (CN); TRACTOR (G4); Controlled Temperature Trailer (Reefer) (RT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Raw Haul Transport LLC','1205855','RHBJ','Intermodal',NULL,'Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Raymonvil Transportation LLC','1306515','RYJL','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Rays Towing And Transport LLC','711064','RYSO','Drayage, Intermodal, LTL, Rail',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Rblll Trucking LLC','1357722','RTAH','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Rbm Logistics LLC','079742','2402',NULL,NULL,'Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Rcs Express Inc','882620','RCXM','Ocean',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Rdc Transport LLC','1458993','3407','Drayage, Intermodal',NULL,'Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Rdk Precision LLC','1172159','2563','LTL',NULL,'LARGE STRAIGHT (G3); TRACTOR (G4); Load/unload Device on Equipment (LU);  (SV); Trailer (not otherwise specified) (TL); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Real Logistics Lllp','1725708','RFXO','Drayage, Intermodal, Rail',NULL,'TRACTOR (G4); Controlled Temperature Trailer (Reefer) (RT); Trailer, Dry Freight (TF); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Red 1 Express Inc','0536797','2279','Air Freight',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Red Baron Logistics Group Corp','101603','RBRW','Drayage',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Red Flame Express Inc','051390','3473','LTL, Truckload',NULL,'Cargo Van (CV);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Red Fox Transportation LLC','1546019','REWH','Drayage, Intermodal, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Red Lion Trucking LLC','062055','RLNB','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Redbird Carriers And Fastrack Auto Transport','178936','SHGM','Drayage, Intermodal',NULL,'Container (CN); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Redefined Transportation Inc','946460','RDNQ','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4)','Long Beach','CA','Carrier',NULL,NULL,NULL,NULL,NULL,NULL),
('Redemption Trucking LLC','1341791','1250','Drayage, Intermodal, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Redline Freight Systems','548616','RFSD','Drayage, Intermodal, LTL',NULL,'Chassis (CH); Cargo Van (CV); Flat Bed Trailer (FT); SMALL STRAIGHT (G2); Controlled Temperature Trailer (Reefer) (RT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Redmex Transport Inc','0614010','2319','LTL, Truckload',NULL,'Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Reedway Global Enterprise LLC','1442886','RGEV','Drayage, Intermodal',NULL,'Chassis (CH);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Regent Trucking Group Inc','734297','2346','Cartage, Drayage, Intermodal',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Reggie Transportation Inc','1185828','1085','Drayage, Intermodal, LTL, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Reinaldo Esteban Vargas','693589','EVTE','Intermodal, Ocean',NULL,'Chassis (CH); Container (CN); Cargo Van (CV); Double-Drop Trailer (DD); Flat Bed Trailer (FT); SMALL STRAIGHT (G2); LARGE STRAIGHT (G3); TRACTOR (G4); High Cube Van (HV); Load/unload Device on Equipment (LU); Open Top Van (OV); Fixed-Rack, Flat-bed Trailer (RA); Fixed-Rack, Double Drop Trailer (RD); Fixed-Rack, Single Drop Trailer (RS); Controlled Temperature Trailer (Reefer) (RT); Single-Drop Trailer (SD); Removeable Side Trailer (ST);  (SV); Trailer, Heater/Insulated/Vented (TA); Trailer, Bulk (TB); Trailer, Dry Freight (TF); Trailer, Tank (Gas) (TG); Trailer, Insulated (TI); Trailer, Tank (Chemicals) (TJ); Trailer, Tank (Food Grade-Liquid) (TK); Trailer (not otherwise specified) (TL); Trailer, Insulated/Ventilated (TM); Trailer, Pneumatic (TP); Trailer, Electric Heat (TQ); Truck, Van (TV); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Reliable Deliveries LLC','1120589','3549','Truckload',NULL,'Flat Bed Trailer (FT); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Reliable Freight Logistics Inc','1106060','RFHJ','Drayage, Intermodal','05/21/2021',NULL,'long beach','CA','Carrier','100,000','05/21/2021','1,000,000','05/21/2021','1,000,000','05/21/2021'),
('Reliable Road Carriers Inc','1563636','RRDW','Drayage',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Reliable Transportation Specialists, Inc.','221046','RELT','Drayage, Intermodal, Ocean',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Reliable Trucking LLC','114744','RAKR','Drayage, Intermodal','12/01/2020',NULL,'Burien','WA','Carrier','100,000','12/01/2020','1,000,000','12/01/2020','1,000,000','12/01/2020'),
('Reliant Transportation Inc','1311108','2534','Drayage, Intermodal, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Reload Transport Inc','1085313','RLDQ','Intermodal, LTL',NULL,'Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Rely-Ance Transport  LLC','1313785','RYTW','Drayage, Intermodal, LTL, Rail',NULL,'Chassis (CH); TRACTOR (G4); Trailer (not otherwise specified) (TL)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Republic Premier Transit LLC','1026989','RPBR','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Reverse Domestic Logistics Inc','1325935','RDUF','Drayage, Intermodal, Ocean, Rail, Truckload',NULL,'Chassis (CH); Trailer (not otherwise specified) (TL)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Revival Transportation, Inc','891136','RVVP','Drayage, LTL',NULL,'High Cube Van (HV); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Revolucion Logistics Inc','1081065','2347','Drayage',NULL,'Cargo Van (CV);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Reynaga Trucking Inc','987230','RTUV','Drayage, Ocean, Rail',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Rfb Transport LLC','1325654','RLQR','Drayage, Intermodal',NULL,'Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Rg''s Transportation, Inc.','923381','RGPN','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Rgm Transport LLC','1166065','2276','LTL',NULL,'TRACTOR (G4);  (SV); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Rh Freight Transport LLC','1447541','2356','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Richard Daniels Transportation','272372','DLRT','Intermodal',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Richards Transport LLC','1191458','3713','Drayage, Intermodal, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ricky Mar Transport LLC','1159529','RKYP','Drayage',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Rickys Transport Corporation','120440','RKYK','Drayage',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ride Freight Transport','737809','RFTV','Drayage',NULL,'Container (CN);  (SV)','Fresno','CA','Carrier',NULL,NULL,NULL,NULL,NULL,NULL),
('Ridgeback Truckline LLC','912295','3260','Air Freight, Cartage, Drayage, Ocean, Parcel, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Right Away Logistics Inc','1167585','RIHA','Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Right Ways Logistics Inc','1639647','RIIH','Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Risenberg Logistics','1343981','RLON','Drayage, Intermodal, Rail',NULL,'Chassis (CH); TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ritehaul Logistics LLC','1317606','RLQF','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('River Trucking Inc','1634843','RIVN','Cartage, Drayage, Intermodal, Ocean, Rail',NULL,'Chassis (CH); Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Riverdawg Transport LLC','809390','RDWH','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Rizzo Business Solutions LLC','1334534','RBSP','Drayage, Intermodal, LTL, Truckload',NULL,'Chassis (CH); Flat Bed Trailer (FT); Fixed-Rack, Flat-bed Trailer (RA); Fixed-Rack, Single Drop Trailer (RS)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Rj Quality Dump, LLC','1165006','RDQA','Drayage, Intermodal, LTL, Truckload',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Rjg Trucking Inc','1372243','3266','Drayage',NULL,'Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Rk Shipping Inc','1058670','RKHQ','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Rkj Transport LLC','1440861','2285','Drayage',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Rl Lines Inc','108197','RLLH','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Rlh Trucking LLC','642514','RLHK','Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Rlj Thour Trucking LLC','1359408','RLJC','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Rlm Transportation Inc','1163883','3206','Drayage, Intermodal, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Rm Transportation Solutions LLC','920461','RMNM','Drayage',NULL,'Chassis (CH); Container (CN); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Rmis  Can Broker Test (Qa Test) - Can Broker','9999189','1178',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Rmis Delta Test','9999777','1035','Truckload',NULL,'Cargo Van (CV)','Burbank','CA','Carrier','100,000','03/24/2021',NULL,NULL,NULL,NULL),
('Rmv Transport LLC','1336398','2342','Drayage',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Rmx Logistics LLC','1045858','2370','LTL',NULL,'TRACTOR (G4); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Rnr Transportation','1144127','RNTP','Drayage, Intermodal, Rail',NULL,'TRACTOR (G4); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Road King Transportation LLC','1404160','RKAB','Drayage, Intermodal',NULL,'TRACTOR (G4); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Road Ready Transport LLC','1337862','1159','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Road Runner 316 LLC','860514','RRLP','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Road Runner Trucking Inc','792826','1131','Drayage',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Road Titans Inc','1236236','2392',NULL,NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Road To Richie','1452423','2521','LTL, Truckload',NULL,'SMALL STRAIGHT (G2)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Road World Transportation LLC','1681500','RPWB','Cartage, Drayage, Intermodal, Ocean, Parcel, Rail',NULL,'Container (CN); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Roaddawgs Trucking LLC','1400344','RDHW','Drayage, Intermodal, LTL',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Roadex Cy Inc','589053','RDXY','Drayage',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Roadlink Carrier','507142','RLKE','Drayage, Intermodal, Ocean, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Roadmaster Trucking Inc','532763','ROAM','Drayage, Intermodal, LTL, Ocean, Rail',NULL,'Chassis (CH); Cargo Van (CV); Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Roadrunner','170247','RDFS','LTL',NULL,'TRACTOR (G4); Trailer, Dry Freight (TF); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Roadstar Express Logistics LLC','1578726','RPPH','Intermodal',NULL,'Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Robert J Turner Jr R&R Transport LLC','443808','RRQT','Drayage, LTL, Rail',NULL,'Cargo Van (CV); Flat Bed Trailer (FT); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Robert L Jenkins Jr Trucking LLC','1221246','1097','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Roberts Transport Enterprises LLC','1268475','RBIS','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Robin Inc','727878','1100','Drayage, Intermodal',NULL,'Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Robinson Cargo LLC','1241226','RCQV','Drayage',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Roca Express LLC','879493','2522','LTL, Truckload',NULL,'TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Rocha''s Transport Inc','1392207','RSTP','Drayage, Intermodal, Rail',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Rocky Mountain Trucking LLC','1095203','RMJF','Drayage',NULL,'Controlled Temperature Trailer (Reefer) (RT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Rodina Trucking LLC','1329763','RDNN','Drayage, Intermodal, Ocean, Rail',NULL,'Chassis (CH); Container (CN); Cargo Van (CV); TRACTOR (G4); Controlled Temperature Trailer (Reefer) (RT); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Rodma LLC','1604292','RQAA','Cartage, Drayage, Intermodal',NULL,'Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Roger Transport Co','1227857','RTJK','Drayage, Intermodal, LTL',NULL,'Chassis (CH); Container (CN); Flat Bed Trailer (FT);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Roldan''s Trucking Services Inc','029512','RNSR','Drayage, Intermodal',NULL,'Chassis (CH); Cargo Van (CV); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Rolling Express LLC','1668336','ROPO','Drayage',NULL,'Chassis (CH); TRACTOR (G4); Load/unload Device on Equipment (LU)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Roman Trucking LLC','1623303','3810','Drayage',NULL,'Cargo Van (CV); Flat Bed Trailer (FT); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Romco','996833','ROMC','LTL',NULL,'Controlled Temperature Trailer (Reefer) (RT);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Romo Carriers Inc','1208274','1158','LTL',NULL,'TRACTOR (G4);  (SV); Trailer, Dry Freight (TF); Truck, Van (TV); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Rose Transportation, Incorporated','169487','RSEN','Drayage, Intermodal, LTL, Ocean, Rail',NULL,'Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Roseway Transport LLC','061405','RSYL','Drayage',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ross & Family Inc','1305677','RFIY','Drayage',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Rotation Transportation & Logistics LLC','1251249','RTUT','Intermodal, Ocean, Rail',NULL,'TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Round 2 Trucking LLC','1293963','RWOG','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Rouse Trucking LLC','1285292','RERL','Drayage',NULL,'Container (CN);  (SV); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Route 4 Intermodal LLC','1022746','RFIM','Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Route 7 Express Inc','934452','NONE',NULL,NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Royal Freight Transportation','587146','RYAH','Drayage, LTL, Ocean',NULL,'Chassis (CH); Cargo Van (CV); TRACTOR (G4); Trailer (not otherwise specified) (TL); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Royal Intermodal Inc','971885','RIIQ','Drayage, Intermodal, Ocean, Rail',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Rpm Freightlines, LLC','1468146','RPMG','Air Freight',NULL,'Controlled Temperature Trailer (Reefer) (RT);  (SV); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Rr Logistics LLC','1267867','RLNM','Drayage, Intermodal, Rail',NULL,'Chassis (CH); TRACTOR (G4); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Rs Freight Service LLC','863793','RFSO','Drayage',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Rs&V Trucking Inc','1217743','3045','Drayage',NULL,'Container (CN); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Rsf Logistics LLC','060450','RSFS','Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Rta Trucking LLC','0625790','2533','Drayage, Intermodal, Rail',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Rtg Freight Inc','1356723','RTFG','Intermodal',NULL,'Chassis (CH); Container (CN);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Rth Trucking LLC','1154862','RTZK','Drayage, Intermodal, Rail',NULL,'Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
