('Gq 1 Inc','1022807','GOBD','Intermodal',NULL,'Container (CN); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Grace Hauling LLC','1214459','GHBG','Drayage, Intermodal, Ocean, Parcel',NULL,'TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Grade A Transport LLC','938409','1047','Drayage',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Grand Canyon Logistics Inc','105082','GCYQ','Drayage',NULL,'Chassis (CH); Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Grand Service Logistics LLC','847220','GSVL','Drayage','10/30/2020',NULL,'Federal Way','WA','Carrier','100,000','10/30/2020','1,000,000','10/30/2020','1,000,000','10/30/2020'),
('Grand Stretch LLC','1021689','1052','Drayage, Intermodal, Rail',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Grand Trucking LLC','1121530','GRUN','Drayage, Rail',NULL,'Flat Bed Trailer (FT); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Grapevine Express, LLC','017966','GVNP','Drayage, Intermodal, LTL, Rail',NULL,'TRACTOR (G4); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Graphite Logistics','688169','GPHL','Drayage, Intermodal','10/02/2020','Chassis (CH); TRACTOR (G4)','Dallas','TX','Carrier','100,000','10/02/2020','1,000,000','10/02/2020','1,000,000','10/02/2020'),
('Grateful Bill Inc','033867','GBIH','Drayage, Intermodal, LTL, Ocean, Truckload',NULL,'TRACTOR (G4); Controlled Temperature Trailer (Reefer) (RT); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Gratitude Trucking LLC','1171278','GDTJ','Drayage, LTL, Truckload',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Grc Trucking LLC','1127512','GRCQ','Drayage, Intermodal, LTL',NULL,'Container (CN); Cargo Van (CV); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Great American Transportation Services Inc','600257','2864','Air Freight, Drayage, Intermodal, LTL, Ocean, Parcel, Rail, Truckload',NULL,'Chassis (CH); Cargo Van (CV); LARGE STRAIGHT (G3); Trailer, Dry Freight (TF); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Great American Transportation Services Inc','600257','2864','Drayage, Intermodal, LTL, Ocean, Parcel, Rail',NULL,'Chassis (CH); Cargo Van (CV); LARGE STRAIGHT (G3); Trailer, Dry Freight (TF); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Great American Trucking Services','827031','1070','TL',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Great Central Transport, Inc.','171892','GCTN','Drayage, Intermodal, LTL, Ocean, Rail',NULL,'Chassis (CH); Controlled Temperature Trailer (Reefer) (RT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Great White Logistics Inc','864989','NONE','Drayage, LTL',NULL,'Cargo Van (CV);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Greater Heights Transportation LLC','1215962','GHPR','Drayage, Intermodal',NULL,'Controlled Temperature Trailer (Reefer) (RT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Green America Trucking Inc','823973','3408','LTL',NULL,'Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Green Boy Inc','820571','1034','Drayage',NULL,NULL,'Rancho Cucamonga','CA','Carrier','100,000','04/05/2021',NULL,NULL,NULL,NULL),
('Green Drayage Systems Inc','691199','GDSW',NULL,NULL,'Controlled Temperature Trailer (Reefer) (RT);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Green Fleet Systems LLC','629533','GFSK','Drayage, Intermodal, LTL, Truckload',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Green Mile Logistics LLC','1264187','GMHD','Drayage, Intermodal, LTL, Truckload',NULL,'Chassis (CH); SMALL STRAIGHT (G2); Load/unload Device on Equipment (LU); Fixed-Rack, Flat-bed Trailer (RA); Trailer, Dry Freight (TF); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Green Mountain Transportation, Inc.','296979','GEMN','Drayage, Intermodal',NULL,'Chassis (CH); Container (CN); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Green Route Transport','1425730','GRPQ','Drayage',NULL,'Cargo Van (CV); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Green Shield Transport LLC','1392230','GNJM','LTL, Truckload',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Green Trucking','866918','2432','Air Freight, Drayage, Rail',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Green Trucking Logistics LLC','1145958','1152','Drayage',NULL,'Cargo Van (CV);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Greenify Inc','060343','GINJ','Drayage, Intermodal, Rail',NULL,'Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Greenline Express Transportation Inc.','549687','2372','LTL',NULL,'Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Greg Brodka Trucking LLC','1281551','BDZK','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Gregory Trucking LLC','633421','2924','Drayage, LTL',NULL,'Cargo Van (CV); TRACTOR (G4); Single-Drop Trailer (SD);  (SV); Trailer, Dry Freight (TF); Trailer (not otherwise specified) (TL); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Grid-Iron Transit LLC','1192242','GRIP','Intermodal, LTL, Truckload',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Grow Logistics, Inc.','958473','GLHL','Drayage, Intermodal, LTL',NULL,'Chassis (CH); Cargo Van (CV); Flat Bed Trailer (FT); Load/unload Device on Equipment (LU); Controlled Temperature Trailer (Reefer) (RT);  (SV); Trailer, Tank (Chemicals) (TJ); Trailer, Insulated/Ventilated (TM); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Grower Alliance Logistics LLC','1310974','GRWC','LTL, Truckload',NULL,'Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Gs Freight Transport, Inc.','884943','GSFG','Drayage, LTL, Ocean',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Gsk Trucking Inc','990404','GSUK','Drayage, Intermodal',NULL,'Chassis (CH); Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Gsm Transport Company','560612','GRGW','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Gsr Expedite','1637748','GSRS',NULL,NULL,'Cargo Van (CV);  (SV); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Gss Logistics LLC','1649334','3710','Air Freight, LTL',NULL,'LARGE STRAIGHT (G3)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Gt Expedited Inc','609469','GEIV','LTL, Truckload',NULL,'(SV); Trailer, Dry Freight (TF); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Gt Transport','864977','GCIS','Drayage, Intermodal, LTL, Ocean, Parcel, Rail',NULL,'Chassis (CH); Cargo Van (CV); Flat Bed Trailer (FT); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Gti','652728','GTJJ','LTL, TL',NULL,'Truck, Van (TV); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Guevara Transportation Inc','057501','GVRP','Drayage, Intermodal','03/01/2020',NULL,'Wilmington','CA','Carrier','250,000','04/01/2021','1,000,000','03/01/2020','1,000,000','03/01/2020'),
('Guidance Transportation LLC','631723','GTJF','Drayage','10/01/2020',NULL,'Renton','WA','Carrier','100,000','10/01/2020','1,000,000','10/01/2020','1,000,000','10/01/2020'),
('Guiding Light LLC','1305718','GULJ','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Gulf Intermodal Services LLC','660128','GINF','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Gulf States Trucking Inc','666354','GFKI','Drayage, Intermodal, LTL, Parcel, Rail',NULL,'Chassis (CH); Container (CN); Cargo Van (CV); Flat Bed Trailer (FT); SMALL STRAIGHT (G2); LARGE STRAIGHT (G3); TRACTOR (G4); Controlled Temperature Trailer (Reefer) (RT); Single-Drop Trailer (SD);  (SV); Trailer, Dry Freight (TF); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Gulf Winds International,  Inc.','320104','GWID','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Gulfstream Logistics, Inc.','983676','GFMN','Drayage, Intermodal, TL',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Gur Nanak Freight Inc','081565','GNAN','Drayage, Intermodal, Rail',NULL,'TRACTOR (G4);  (SV); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Gurfateh Logistics Inc','1414167','GUTD','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Gurgen Trucking Inc','537632','1209','TL',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Gus Bros Lite LLC','1530941','2436','Drayage, Intermodal, TL',NULL,'Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('H & A Transport LLC','1298033','HATB','Drayage',NULL,'Chassis (CH); Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('H & P Logistics Inc','896641','HPLP','Drayage, Intermodal',NULL,'Chassis (CH)','Gardena','CA','Carrier','100,000','07/17/2021','1,000,000','07/17/2021','1,000,000','07/17/2021'),
('H Pastrana Transport LLC','1576383','3813','Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('H R Trucking','1091456','HRTR','Intermodal, LTL, Parcel',NULL,'TRACTOR (G4); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('H Transport LLC','1218119','HTPS',NULL,NULL,'Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('H&M Intermodal Services LLC','059670','HMIV','Drayage, Intermodal',NULL,'Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('H&M Trucking','1324264','HMHN','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('H&s Sangha, Inc.','978899','SGPQ','Drayage, Intermodal, Ocean, Rail',NULL,'Container (CN); Cargo Van (CV); Controlled Temperature Trailer (Reefer) (RT);  (SV); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('H2 Express Transport LLC','1266533','HTHC','Drayage, Intermodal, Rail',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Hallmark Trucking LLC','136172','HMKV','Drayage, Intermodal',NULL,'Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Hamed Trucking Inc','1381768','HMDN','Drayage, Intermodal, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Hankerson Transport Inc','1080764','HKSN','Drayage, Intermodal, Ocean',NULL,'Chassis (CH); Container (CN); TRACTOR (G4);  (SV); Trailer, Dry Freight (TF); Trailer, Tank (Food Grade-Liquid) (TK); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Happy Hayday Trucking LLC','1227115','1189','Drayage',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Happy Toyz Trucking LLC','1410571','HPAB','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Happy Valley Trucking LLC','947386','2338','Drayage, Intermodal',NULL,'TRACTOR (G4); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Harbor Division','195568','HBDV','Drayage, Intermodal, Rail',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Harbor Dream Inc','965747','3769','Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Harbor Intermodal Inc','1031670','HIIC','Drayage, Intermodal',NULL,'Chassis (CH); Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Harbor Pro Logistics','1019955','3529','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Harbor Team Logistics Inc','911701','HBML','Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Harbor Transport Inc','929796','HBRN','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Harbour Link Container Services Inc','695925','HLCV','Drayage',NULL,'Chassis (CH); Single-Drop Trailer (SD)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Hardbody Trucking Inc','820539','HDBY','Drayage, Intermodal',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Hardcore Transport Inc','101112','HDCO','Drayage',NULL,'Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Harrell And Son''s Trucking','1252172','1244','Drayage',NULL,'Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Harris Bros Logistics LLC','1598577','HBEF','Drayage, Intermodal, LTL',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Harris Trucking LLC','1249233','2682','Air Freight, Intermodal',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Harvey Pro Trucking LLC','1387344','HPTC','Drayage, Ocean',NULL,'Chassis (CH); Container (CN); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Harvey Transportation LLC','1193183','HTVL','Drayage, Intermodal',NULL,'Chassis (CH); Flat Bed Trailer (FT); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Hat Logistics Inc','186486','HATS','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Haulit Transport LLC','018406','HTGF','Drayage',NULL,'Chassis (CH); TRACTOR (G4); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Haulplus Logistics LLC','879877','HPSG','Intermodal',NULL,'Chassis (CH); Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Haulpro Transport LLC','1340540','2527','LTL, Truckload',NULL,'Flat Bed Trailer (FT); Single-Drop Trailer (SD)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Hawkeye Transport LLC','1252146','2330','LTL, Parcel',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Hbb Trans Inc','1439858','2334','Air Freight, Cartage',NULL,'Cargo Van (CV); TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Hd Drayage & Container Services LLC','1264835','HDAY','Drayage, Intermodal, LTL, Rail',NULL,'Chassis (CH); Container (CN); TRACTOR (G4); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Hd Trans Inc','1100623','2379','Truckload',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Hd Transport LLC','1383200','HTMM','Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Hdr Logistics LLC','074596','HDRW','LTL',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Hdt 24Hr Transportation LLC','1652953','3590','Cartage, Drayage, Intermodal, LTL',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Heartsdale Trucking LLC','897360','HTLV','Drayage, Intermodal',NULL,'Chassis (CH); Double-Drop Trailer (DD); Flat Bed Trailer (FT); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Heavy Haulers LLC','1235715','2299','Intermodal',NULL,'Chassis (CH); Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Heavy Rolling Logistics LLC','1336869','2482','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Hellcat Trucking Inc','1387181','1243','LTL, Parcel',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Henderson Logistics   64 LLC','1117312','HNDI','Drayage',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Heritage 23 LLC.','955299','HTYH','Truckload',NULL,'Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Hero Expressway','1046943','HOXW','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Herrera Logistics LLC','1115363','HRRW','Drayage, Intermodal, LTL, Rail',NULL,'Chassis (CH); Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Herrera Transport Inc','009649','HRWP','Drayage, LTL',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Herrera''s Express Inc','813003','2383','Drayage',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Hess Transportation LLC','1742192','3613','Air Freight, Cartage, Drayage, Intermodal, LTL, Rail, Truckload',NULL,'Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Heyward Trucking And Distribution LLC','1186472','HTAO','Drayage, Intermodal',NULL,'Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Hgg Transport & Logistics LLC','1217522','HTDJ','Drayage, Intermodal, Rail',NULL,'TRACTOR (G4); Trailer (not otherwise specified) (TL)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Hhm Intl Inc','133208','HHMI','Drayage','10/19/2019',NULL,'Signal Hill','CA','Carrier','100,000','08/13/2021','1,000,000','10/19/2019','0',NULL),
('Hi-Lite Trucking LLC','1081954','HLTW','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Hibbco Trucking LLC','1267497','HTXP','Intermodal',NULL,'TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Higgins Transportation LLC','954598','HTMY','Drayage, Intermodal, LTL, Ocean, Parcel, Rail',NULL,'Cargo Van (CV); Single-Drop Trailer (SD)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('High Mountain Transport, LLC','224896','HMTA','Drayage, Intermodal, Parcel, Rail',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('High Rollers Transport LLC','756308','HRFR','Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Highlane','1394226','HIGE','Intermodal',NULL,'Chassis (CH); Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Highlight Motor Freight','158-137-502','3894','LTL, Truckload',NULL,'TRACTOR (G4); Trailer (not otherwise specified) (TL)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Hight Electric','813383','KRDD','Intermodal',NULL,'Chassis (CH); Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Highway Hustlers LLC','1584970','3508','Truckload',NULL,'(SV); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Highway Legends Inc','1131304','HWGD','LTL, Truckload',NULL,'Controlled Temperature Trailer (Reefer) (RT);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Highways & Skyways Of Nc','446371','GVTT','Drayage, Truckload',NULL,'Chassis (CH); TRACTOR (G4); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Hillside Warehouse & Trucking Co., Inc.','180854','HLSH','Drayage, LTL',NULL,'Chassis (CH); TRACTOR (G4); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Hiload Moving Company LLC','1511687','2451','Drayage',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Hirschbach Solutions','275598','HTSH','Truckload',NULL,'Controlled Temperature Trailer (Reefer) (RT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Hjq Transportation Inc','0647248','HJQY','Parcel',NULL,'Container (CN); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Hk Logistics Corp','1184563','3186','Drayage, LTL',NULL,'Chassis (CH); Cargo Van (CV);  (SV); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Hla Transport LLC','1542703','HLUV','Cartage, Drayage, Intermodal, LTL, Ocean, Parcel, Rail, Truckload',NULL,'Chassis (CH);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Hldd Trucking Inc','1439833','2316','Intermodal, LTL',NULL,'Flat Bed Trailer (FT);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Hmt Trans Inc','981554','2362','Truckload',NULL,'TRACTOR (G4); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Holmes Elite Trucking LLC','1290427','HMUL','Drayage, Intermodal, LTL',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Homeland 1 Logistics LLC','583632','HOLL','Drayage','08/01/2025','Cargo Van (CV)',NULL,NULL,NULL,'250,000','08/01/2025',NULL,NULL,NULL,NULL),
('Homeland Transport Inc','806611','HOME','Drayage','12/01/2020',NULL,'Elk Grove Village','IL','Carrier','250,000','12/01/2020','1,000,000','12/01/2020','1,000,000','12/01/2020'),
('Homer Trucking','131312','HTXO','Cartage, Drayage, Intermodal, LTL, Ocean, Parcel, Rail, Truckload',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Hong Sheng Group Inc','040115','2303','LTL',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Hooks Transportation LLC','1375130','HOKP','Intermodal',NULL,'Chassis (CH); Container (CN); Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Hookwell Trucking LLC','1238175','HTDV','Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Hope Logistics Inc','1393124','HPAL','Drayage, Intermodal, Ocean, Rail',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Horizon Freight System, Inc.','169607','HZNF','Drayage, Intermodal',NULL,'Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Horizon Mid Atlantic, Inc.','770152','HMAC','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Horizon Midwest Inc','791331','HZMQ','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Horizon West Inc','791357','HZWI','Drayage','09/01/2020',NULL,'Cleveland','OH','Carrier','100,000','09/01/2021','2,000,000','09/01/2020','2,000,000','09/01/2020'),
('Hot Way Trucking Inc','1134267','1066','TL',NULL,'Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Houger Express LLC','894475','HGXE','Drayage, Intermodal, LTL',NULL,'Flat Bed Trailer (FT); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Howard'' S  Express','193781','RISF','LTL, Truckload',NULL,'Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Hp Express Inc','819495','2466','LTL, Truckload',NULL,'Controlled Temperature Trailer (Reefer) (RT);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Hph Trucking Inc','657807','3718','Air Freight, LTL, Truckload',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Hr Translink Inc','1039375','3406','TL',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Hr05 Roadline Inc','1399200','3715','Drayage',NULL,'Cargo Van (CV); TRACTOR (G4); Single-Drop Trailer (SD);  (SV); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Hrg Transport Inc','784825','HRGN','Drayage','03/04/2021',NULL,'Ontario','CA','Carrier','100,000','03/04/2021','1,000,000','03/04/2021','1,000,000','03/04/2021'),
('Hsp Express','1158310','3589','LTL',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ht Transport','1038040','HTPF','Drayage',NULL,'Chassis (CH); Container (CN); Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Hta Logistics LLC','1450201','HLME',NULL,NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Hudson Intermodal','762864','WSSH','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Huk Transport LLC','101403','HTWY','LTL, Truckload',NULL,'Cargo Van (CV); High Cube Van (HV); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Hurry Transport','1671945','HURY','Drayage, Intermodal, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Husky Trucking Co., LLC','697140','3916','LTL, Parcel',NULL,'Flat Bed Trailer (FT); TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('I Am Logistics LLC','015463','2382','Drayage, Intermodal, LTL',NULL,'TRACTOR (G4); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('I Esqueda Trucking LLC','1224026','1151','Drayage',NULL,'Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('I T Nella Inc','663512','ITNJ','LTL, Truckload',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('I Truck Road, LLC','954791','3250','Drayage, Intermodal, Ocean, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('I&T Transport Inc','1373293','ITTF','Drayage',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('I-Go Trans LLC','897901','IGPD','LTL',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('I.T.L.','388086','ITLK','Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Iaa Logistics Inc','1479964','2475','LTL, Truckload',NULL,'Truck, Van (TV); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Iba Transport Inc','1081043','1256','Drayage, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ibt','337584','IBTP','Drayage, Intermodal, Ocean, Rail, Truckload',NULL,'Chassis (CH); Cargo Van (CV); Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ibv LLC','640746','IBVL','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Icon Logistics Group Inc','734783','ILGA','Drayage, Intermodal','09/05/2020',NULL,'Fontana','CA','Carrier','250,000','09/05/2021','1,000,000','09/05/2020','1,000,000','09/05/2020'),
('Idray LLC','1492301','IDRA','Cartage, Drayage, Intermodal, LTL, Ocean, Rail, Truckload',NULL,'Chassis (CH); Flat Bed Trailer (FT); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Igj Trucking Company LLC','093553','ITHG','Drayage, Intermodal, Ocean, Rail',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ikaros Transport LLC','0569374','IKRP','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Imc','187562','RFBJ','Cartage, Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Imex Logistics, LLC','013986','IMXS','Drayage, Intermodal',NULL,NULL,'Las Vegas','NV','Carrier','250,000','06/01/2021','0',NULL,'0',NULL),
('Iml 1225 Trucking LLC','1104187','IOAE','Drayage, Intermodal, LTL',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Immaculate Transportation LLC','1346451','1148','Drayage, Intermodal',NULL,'Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Impact Transportation, LLC','297354','IMPC','Drayage, Intermodal',NULL,'Chassis (CH); Double-Drop Trailer (DD); Flat Bed Trailer (FT); Single-Drop Trailer (SD);  (SV)','Emeryville','CA','Carrier',NULL,NULL,NULL,NULL,NULL,NULL),
('Imperial Transportation Corp','124883','ITCB','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Imperio Trucks LLC','1688801','IMQV','Intermodal, LTL',NULL,'Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('In Route Trucking LLC','1067755','IRTC','Drayage, Intermodal, LTL',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('In Time Trucking LLC','1509614','PRQR','Drayage, Rail',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Inazumi Express LLC','1436836','2722','Air Freight, Cartage, Drayage, Intermodal, LTL, Ocean, Parcel, Rail, Truckload',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Indiana Transport Of Hammond LLC','910320','INDI','Drayage','11/15/2020',NULL,'Baton Rouge','LA','Carrier','100,000','11/15/2020','0',NULL,'1,000,000','11/15/2020'),
('Indiemodal Trucking','1029885','MCLQ','Drayage',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Industrial Transportation L.L.C.','222324','INUS','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Inheritance Logistics','088146','IHNL','Drayage','09/25/2020',NULL,'San Pedro','CA','Carrier','100,000','09/25/2020','1,000,000','09/25/2020','1,000,000','09/25/2020'),
('Inn Tranz Lines Inc','1510112','2345','Drayage, LTL',NULL,'Flat Bed Trailer (FT);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Innovation Freight System LLC','1026059','3064','Intermodal, LTL, Truckload',NULL,'Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Innovation Transportation Inc','1209606','IVNP','Drayage',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Innovative Intermodal Inc','704622','IIIC','Drayage, Intermodal','09/01/2020','Chassis (CH); Container (CN); TRACTOR (G4)','Woodridge','IL','Carrier','250,000','09/01/2021','1,000,000','09/01/2020','1,000,000','09/01/2020'),
('Inontime','358129','INJM','Drayage, LTL',NULL,'Chassis (CH); Cargo Van (CV); TRACTOR (G4); Controlled Temperature Trailer (Reefer) (RT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Insomnia 888 Corp','196032','IEEE','Drayage',NULL,'Cargo Van (CV); TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Instant Trucking Inc','659261','ITBK','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Inteco Corp','1164305','ICOR','Drayage, Intermodal, LTL',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Interatlas Logistics Inc','805625','ILIB','Drayage, Intermodal, Ocean, Rail',NULL,'Chassis (CH); TRACTOR (G4); Trailer, Bulk (TB); Trailer, Tank (Chemicals) (TJ)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Intercity Express','825924','IYEP','Drayage, Intermodal','03/01/2021',NULL,'Seattle','WA','Carrier','250,000','03/01/2021','1,000,000','03/01/2021','1,000,000','03/01/2021'),
('Interline Trucking Inc','001154','ITIK','Drayage, LTL',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Intermodal Carrier Corporation','1627122','INVW','Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Intermodal Transportation And Consulting','1018255','ITAS','Drayage, Intermodal',NULL,'Chassis (CH); Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Intermodall','957081','INTM','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('International Cellars LLC','1282030','ICNR','Drayage',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('International Container Group Inc','1074687','ICBH','Drayage, Intermodal',NULL,NULL,'Los Angeles','CA','Carrier','100,000','01/10/2021',NULL,NULL,NULL,NULL),
('International Motor Freight, Inc.','212742','IMRF','Drayage',NULL,'Chassis (CH); Container (CN); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('International Transport Assoc','674654','1077','Drayage, LTL, Parcel',NULL,'Cargo Van (CV); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Interpoint Transport','813653','IPTA','Intermodal',NULL,'Cargo Van (CV); Flat Bed Trailer (FT); TRACTOR (G4); Fixed-Rack, Flat-bed Trailer (RA); Fixed-Rack, Double Drop Trailer (RD); Controlled Temperature Trailer (Reefer) (RT);  (SV); Trailer, Bulk (TB); Trailer, Dry Freight (TF); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Intransit Express Delivery','543886','INTA','Intermodal, LTL, Ocean, Parcel',NULL,'Chassis (CH); TRACTOR (G4); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Iraheta Bros 2 Inc','876779','IBIQ','Drayage, Rail, Truckload',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Isais Logistics Inc','888123','ILGE',NULL,NULL,'TRACTOR (G4); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Isr Transportation Inc','1146767','1091','Drayage, Intermodal, Parcel',NULL,'Cargo Van (CV); High Cube Van (HV); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Issa Logistics LLC','862636','ISSC','Truckload',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Itrack Inc','103241','IKIC','Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Itz-Ohlson Transport, Inc.','240943','ITZO','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ivan & Sons Transportation L L C','1210550','1113','Drayage, Intermodal, LTL, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ivcinya Company LLC','156266','IVCM','Drayage, Rail',NULL,'TRACTOR (G4); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ixt','407473','IXPT','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Izbicki Trucking LLC','492700','2560','Drayage',NULL,'Cargo Van (CV); Flat Bed Trailer (FT); Single-Drop Trailer (SD)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('J & A Logistics LLC','1257115','JAAD','Drayage, Intermodal',NULL,'Flat Bed Trailer (FT); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('J & C Custom Deliveries, Inc.','407784','JCCV','Drayage, Intermodal',NULL,'Chassis (CH); Cargo Van (CV); LARGE STRAIGHT (G3); TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('J & E Abad Transport Corp','1131732','AJIJ','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('J & J Pathways','1355383','JJPW','Truckload',NULL,'TRACTOR (G4);  (SV); Trailer, Dry Freight (TF); Trailer, Insulated (TI); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('J & L Transport LLC','914517','JLTE','Drayage, Intermodal, Rail',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('J & R Trucking','1076302','2323','Drayage, Intermodal',NULL,'Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('J & S Drayage, LLC','716085','JSDL','Drayage',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('J 2 M Trucking Inc','1150354','JTMD','Drayage, Intermodal, LTL',NULL,'Chassis (CH); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('J And L Express LLC','1503600','2388','Drayage',NULL,'Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('J And M Baker Logistics LLC','1124414','BJAH','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4);  (SV); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('J Barbas Trucking','1278364','2350','Drayage',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('J Baxter Transportation LLC','1283838','BJBS','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('J C A Inc','1282990','JCGQ','Drayage',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('J K S Transport Ltd','070873','JKSD','Truckload',NULL,'Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('J S Dhatt Trucking Inc','986600','1252','LTL',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('J Star Inc','1580009','JSTG','Drayage, Intermodal, Rail',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('J Swafford Transports LLC','1116130','1051','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('J&M Tilshore LLC','1306162','SCAC','Drayage',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('J&M Trans Inc','1176438','GSHF','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('J&W Logistics LLC','1522975','3470','Truckload',NULL,'(SV); Trailer, Dry Freight (TF); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('J1s Trucking LLC','1194839','JOSL','Drayage, Intermodal, Rail',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('J4me LLC','1151577','JFMJ','Drayage, Intermodal, Ocean, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jaaron Logistics LLC','096940','JLLH','Drayage',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jack Freeman Trucking Co., Inc.','121493','FREJ','Drayage, Intermodal',NULL,'Chassis (CH); Flat Bed Trailer (FT); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jacksons Transportation Solutions LLC','1239345','JKNJ','Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jacky Lines Inc','500282','JLIY','LTL',NULL,'Cargo Van (CV);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jad Import & Export LLC','031727','1065','LTL',NULL,'Controlled Temperature Trailer (Reefer) (RT);  (SV); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jada Xpress Transportation LLC','1307774','JXTA','Intermodal',NULL,'Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jagjot Express Inc','512236','JGXI','LTL, Truckload',NULL,'(SV); Trailer, Heater/Insulated/Vented (TA); Trailer, Insulated (TI); Trailer (not otherwise specified) (TL); Trailer, Insulated/Ventilated (TM); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jaguar Transportation LLC','1350032','JTZQ','Drayage, Ocean',NULL,'Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jam Freight Trucking LLC','1480342','JFCG','Drayage, Intermodal, Rail, Truckload',NULL,'Chassis (CH);  (SV); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jano Logistics Inc','788202','JLOJ','Drayage, Intermodal, Rail',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jaro Fleet Technologies Inc','1723269','JFBF','Drayage, Intermodal, Truckload',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jasmin Logistics LLC','741705','JSMG','LTL',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jaspem Truck Line Inc','918873','JPMK','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jay Chantel Transportation LLC','1305213','CJBM','Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jay Kay Trucking LLC','1212306','JKAN','Air Freight, Drayage, Intermodal, Ocean, Rail',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jaz Express LLC','1309420','JEFE','Drayage, Intermodal',NULL,'Chassis (CH); Container (CN); Cargo Van (CV); Controlled Temperature Trailer (Reefer) (RT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jazmine Transport LLC','1117541','2573','Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jb Intermodal Inc','1088708','JIBB','Intermodal, Rail',NULL,'(SV); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jba Transport LLC','1093185','JBEY','Drayage, Intermodal, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jbs Transport LLC','123536','1167','Drayage, Intermodal, Rail',NULL,'Container (CN); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jc Moreno Trucking LLC','980365','MJCC','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4); Trailer (not otherwise specified) (TL)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jcd Transport Inc','873686','JCDP','Intermodal, Ocean, Rail',NULL,'Chassis (CH); SMALL STRAIGHT (G2); TRACTOR (G4); Open Top Van (OV); Single-Drop Trailer (SD); Removeable Side Trailer (ST);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jce Transport LLC','132608','2984','Drayage, Intermodal, LTL',NULL,'TRACTOR (G4); Trailer (not otherwise specified) (TL)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jcs Transportations LLC','786317','JCSP','Intermodal, Rail',NULL,'Cargo Van (CV); TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jd & La Trucking Inc','529361','JCTK','Drayage, Intermodal',NULL,'Chassis (CH); Double-Drop Trailer (DD); TRACTOR (G4); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jd Express, Inc','822597','JDES','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jda Transportation Inc','559082','JDA','Drayage, Intermodal, LTL',NULL,'Chassis (CH); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jdc Now LLC','1303083','JDCW','Drayage, Intermodal, Ocean',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jde Transportation Inc.','925593','JDEJ','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4)','Wilmington','CA','Carrier','250,000','07/10/2021',NULL,NULL,NULL,NULL),
('Jdg Logistics LLC','1283590','JLDR','Drayage, Intermodal, Rail',NULL,'Chassis (CH); TRACTOR (G4); Controlled Temperature Trailer (Reefer) (RT);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jed Logistics Inc','075547','JEDI','Drayage','04/01/2020',NULL,'Hesperia','CA','Carrier','100,000','04/12/2021','1,000,000','04/01/2020','1,000,000','04/01/2020'),
('Jeet Logistics,Inc.','726497','JEES','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jep Trading Inc','1315674','JTWE','Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jep Transportation Inc','1070527','1019','Drayage','11/25/2020',NULL,'Laredo','TX','Carrier','100,000','01/14/2021','0',NULL,'1,000,000','11/25/2020'),
('Jeron Lewis Transportation LLC','092463','1157',NULL,NULL,'TRACTOR (G4); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jes Logistics Corporation','067123','JLCK','Intermodal',NULL,'Fixed-Rack, Flat-bed Trailer (RA)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jessie James Trucking LLC','1090753','3366','Drayage, Intermodal, Rail',NULL,'Chassis (CH); Container (CN); Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jessie''s Trucking LLC','865103','JSSN','Drayage, Intermodal',NULL,'Chassis (CH); Flat Bed Trailer (FT); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jet City Trucking','039604','JCYK','Drayage, Intermodal',NULL,'Chassis (CH); Cargo Van (CV); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jet I Trans LLC','1192131','JEWL','Drayage, Intermodal',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jetman Trucking Inc','1536696','JEUJ','Drayage, Intermodal, Ocean, Rail',NULL,'Chassis (CH); Double-Drop Trailer (DD); Flat Bed Trailer (FT); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jfk Logistics & Transport','997501','JFKL','Drayage, Intermodal',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jfl Trucking & Logistics LLC','1138028','JTNM','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jh & M Logistics Corp','1401550','JMLK','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jhr Transportation Inc','1222201','JHRP','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jin Cheng Trucking Inc','1186477','3609','LTL, Truckload',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jio Transport Inc','1057954','JIOP','Drayage, Intermodal, LTL, Ocean, Parcel, Rail',NULL,'Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jj & Gg Carriers LLC','1251291','JGCL','Drayage, Intermodal',NULL,'Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jj Chicas LLC','1466398','2500','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jj Chicas Trucking LLC','1586996','3570','Cartage, Drayage, Intermodal, LTL, Rail',NULL,'LARGE STRAIGHT (G3); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jj Trucking','056875','2280','LTL',NULL,'TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jj Trucking','1018090','2423','Drayage',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jj Williams Trucking LLC','1256431','2301','Drayage',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jkl5 Trucking LLC','1335191','JFJL','Drayage, Intermodal',NULL,'Double-Drop Trailer (DD)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jl Logistics LLC','034536','JPLG','LTL',NULL,'Flat Bed Trailer (FT);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jla Express LLC','1120494','1194','Drayage',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jlc Trucking LLC','1414007','JLCN','Drayage, Intermodal, Rail',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jlj Transport Inc','1084732','JLJP','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jlm Logistics Inc','829490','JLMQ','Drayage',NULL,'Chassis (CH); Container (CN); Cargo Van (CV); Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jlw Expressway LLC','1276180','JLWO','Drayage, Truckload',NULL,'Chassis (CH); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jm Transportation Inc','733695','JMXJ','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jm Transports LLC','1018865','JMNP','Air Freight',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jmc Freight Inc','1410012','2274','LTL, Truckload',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jmc Trucking','1251020','2524','Truckload',NULL,'Flat Bed Trailer (FT); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jmj Logistex LLC','011432','JMJF','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jmna Trucking LLC','1141795','JMNS','Cartage, Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jmo Trucking LLC','1255618','JMOE','Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jms Trucking LLC','005969','NONE','LTL',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jmtm LLC','1445734','JLFM','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jng Carriers LLC','1689531','3326','Drayage, Intermodal, LTL, Rail, Truckload',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jnn Logistics','1170840','JNXA','Intermodal, LTL, Rail, Truckload',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jnq Logistics Corp','1213545','JNQL','Drayage, Intermodal, LTL, Rail',NULL,'TRACTOR (G4); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jns Transport','940641','JNPO','Drayage, Intermodal, LTL','01/19/2021',NULL,'Long Beach','CA','Carrier','100,000','01/19/2021','1,000,000','01/19/2021','1,000,000','01/19/2021'),
('Joepearl Trucking LLC','1297279','JOAE','Drayage, Intermodal, Ocean, Rail',NULL,'Chassis (CH); Flat Bed Trailer (FT); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jof Intermodal Inc','739183','JIIA','Drayage, Intermodal',NULL,'Chassis (CH); Cargo Van (CV); TRACTOR (G4);  (SV); Trailer (not otherwise specified) (TL); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Johal United Inc','1056333','2514','LTL, Truckload',NULL,'Cargo Van (CV); Flat Bed Trailer (FT); TRACTOR (G4);  (SV); Trailer, Dry Freight (TF); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('John Calkins Trucking','209639','CAJH','LTL, Truckload',NULL,'Cargo Van (CV); TRACTOR (G4);  (SV); Trailer, Bulk (TB); Trailer, Dry Freight (TF); Trailer, Insulated (TI); Trailer (not otherwise specified) (TL); Trailer, Insulated/Ventilated (TM); Trailer, Electric Heat (TQ)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('John Dm Trucking Limited Liability Company','1134181','JDTY','Drayage, Intermodal, LTL, Ocean, Rail',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('John Fayard Moving & Warehousing, LLC','432866','FJMW','Drayage',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Johnson Express Trucking LLC','1383508','JEAK','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jon''s Hauling Inc.','1040195','JHAF','Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jones Fleet Express LLC','1370730','JFEA','Drayage, Intermodal, LTL, Rail, Truckload',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jones Transportation Group LLC','045726','JOTL','Drayage, Intermodal',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jordan Highway Transport Company LLC','362839','JHWY','Drayage, Intermodal',NULL,'TRACTOR (G4); Trailer, Dry Freight (TF); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jorge A Deleon Perez','1258163','2369','Air Freight',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jos Logistics Inc','1648080','JOVS','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jot Trucking Inc','679312','2336','Air Freight, Drayage, Parcel',NULL,'TRACTOR (G4); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jovanni Trucking Inc','1149507','JVNI','Drayage, Intermodal, Rail',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Joyride Logistics LLC','882528','JYRG','Drayage',NULL,'Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jq Trucking LLC','1114467','JQKL','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jra Transport LLC','1028987','JTJI','Drayage, LTL, Rail, Truckload',NULL,'Chassis (CH);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jre Transportation Inc','1019824','2503','LTL',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jri','901415','JRIJ','Drayage, Intermodal, Rail',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Js Dispatch Service LLC','1150181','1128','LTL, Truckload',NULL,'TRACTOR (G4);  (SV); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Js Trucking Company LLC','069360','2386','Truckload',NULL,'Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jsp Express Transport LLC','748502','JSPP','Drayage, Ocean',NULL,'Chassis (CH); Single-Drop Trailer (SD)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jt Transport LLC','1328043','JTYS','Drayage, Intermodal, Ocean',NULL,'Chassis (CH); Container (CN); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jta Trucking LLC','1184961','1257','Ocean',NULL,'Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jtees Transport','1445220','NA','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jts Transport LLC','1170422','JTSC','Drayage, Intermodal',NULL,'Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jucamp Trucking LLC','1142160','JTOJ','Drayage',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Junction Collaborative Transports','870931','JCTD','Drayage',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jung Truck Service, Inc','038984','JUTS','Drayage, Intermodal',NULL,'Chassis (CH); Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Just Right Transportation','749245','JRXQ','Intermodal, Ocean',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Just-n-time Logistics LLC','082321','3248','Truckload',NULL,'TRACTOR (G4); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Justice Logistics LLC','1376197','JLLW','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Justin L Walter Transportation LLC','1153820','WJLI','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jv & Son''s Transport LLC','1217276','JSSR','Air Freight, Cartage, Drayage, LTL, Parcel, Rail, Truckload',NULL,'TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jvm Transports LLC','1066853','JVMP','Drayage',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jvz Trucking LLC','1570270','3719',NULL,NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jy Trucking','813577','JYTR','Drayage','05/06/2020',NULL,'Millersburg','IN','Carrier','0','05/06/2020','0','05/06/2020','0','05/06/2020'),
('Jyc Trucking LLC','204623','JTFJ','Drayage',NULL,'Chassis (CH); Cargo Van (CV); TRACTOR (G4); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jz Transportation Inc','087446','JZTP','Drayage, Intermodal, Rail',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jzc Trucking LLC','1318041','JZCK','Drayage, LTL, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('K & A Express, Inc','639358','KAEI','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('K & J Express Logistics LLC','1107363','KJFK','LTL, Truckload',NULL,'SMALL STRAIGHT (G2); LARGE STRAIGHT (G3); TRACTOR (G4); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('K & J Trucking Concord LLC','781064','2385','TL',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('K & K Transport, Inc.','761772','KAKQ','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('K & P Trucking Inc','857078','KPTI','Drayage, Intermodal','03/11/2021',NULL,'Whittier','CA','Carrier','100,000','03/11/2021','1,000,000','03/11/2021','1,000,000','03/11/2021'),
('K & S Enterprise Of Kansas City, Inc.','737778','KSEI','Drayage, Intermodal',NULL,'Chassis (CH); Flat Bed Trailer (FT); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('K And K Transportation','487381','1154','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
ON CONFLICT (scac) DO NOTHING;

INSERT INTO mg_carriers (name,mc_number,scac,modes,early_ins_exp,equipment,loc_city,loc_state,loc_type,cargo_ins_amt,cargo_ins_exp,general_ins_amt,general_ins_exp,liability_ins_amt,liability_ins_exp) VALUES
('K Line Group Inc','1435588','KLGQ','Intermodal, Rail',NULL,'Trailer, Dry Freight (TF); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('K Mccoy Enterprises LLC','1272468','KMDQ','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('K N D Transport And Trucking LLC','931945','KNDL','Drayage',NULL,'Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('K&C Fenix Trucking LLC','1480075','KCFF','Drayage, Intermodal',NULL,'Chassis (CH); Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('K&M Logistics Services Inc','888684','NONE','Air Freight, Drayage, LTL, Parcel, Truckload',NULL,'(SV); Truck, Van (TV); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('K''dub Trucking LLC','1288206','2434',NULL,NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('K-1 Logistics LLC','933701','KFKC','Drayage, Intermodal',NULL,'Chassis (CH)','ELIZABETH','NJ','Carrier',NULL,NULL,NULL,NULL,NULL,NULL),
('K-9 Henriquez Trucking Inc','1172176','KNHR','Drayage',NULL,'Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('K-Low Trucking LLC','1225195','KLJO','Drayage',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('K.M.E. Express LLC','1264142','KELY','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('K.W. Trans, LLC','839520','KWTH','Intermodal, LTL',NULL,'Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('K1 Transfreight Inc','902154','KOKF','LTL, Truckload',NULL,'Flat Bed Trailer (FT); Trailer, Dry Freight (TF); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Kaav Transportation LLC','1369757','KTJL','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Kadads LLC','1075080','KLDL','Air Freight',NULL,'(SV); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Kair Harbor Transport Inc','068879','KHTC','Drayage, Intermodal',NULL,'Chassis (CH); Double-Drop Trailer (DD); Flat Bed Trailer (FT); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Kairo Trucking LLC','1711270','3809','Drayage, Intermodal',NULL,'Flat Bed Trailer (FT); TRACTOR (G4);  (SV); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Kali Carriers LLC','0580356','1205','Drayage',NULL,'Flat Bed Trailer (FT); TRACTOR (G4)',NULL,NULL,NULL,'0',NULL,'0',NULL,'0',NULL),
('Kamilas Big Kar LLC','1289320','3255','Drayage, Intermodal, Rail',NULL,'Cargo Van (CV); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Kansas City Intermodal LLC','820295','KCIS','Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Kansas Freight Line Inc.','743008','KFLS','Intermodal',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Karl''s Sons Express Inc','952246','KSED','LTL',NULL,'Trailer, Dry Freight (TF); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Karlis Transport Inc','1175526','3024','Intermodal',NULL,'Chassis (CH); Container (CN); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Karvon Group Transportation LLC','1249546','KAVP','LTL, Truckload',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Katyusha Trucking','1117764','3448','LTL',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Kavkaz Express LLC','876637','KVZE','Drayage, Intermodal',NULL,'Chassis (CH); Flat Bed Trailer (FT);  (SV); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Kbm Trucking LLC','078461','KBMG','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Kc Roadway Inc.','943889','KCRW','Drayage, Ocean, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Kcd','1100942','KCDB','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Kcm Transport LLC','1313124','KCMF','Drayage, Intermodal, LTL, Truckload',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Kds Trucking LLC','941562','2415','LTL',NULL,'Flat Bed Trailer (FT); TRACTOR (G4); Controlled Temperature Trailer (Reefer) (RT); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Keeping It Moving Trucking LLC','1320971','1188','Air Freight',NULL,'(SV); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Kefeng Truck Inc','1180251','3915','LTL',NULL,'(SV); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Kelchamel LLC','1015664','KCMC','Drayage',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Keld Enterprises','1102924','1053','Drayage, Intermodal, LTL, Ocean, Parcel, Rail',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ken Transportation LLC','1235128','1075','TL',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Kentucky Container Service, Inc.','160261','KYCS','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Kevin Noel','019561','NKEC','Drayage',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Keystone Logistics, Inc.','309165','KSLO','Intermodal, LTL, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Keyword Trucking LLC','1076345','KYWK','Drayage, Intermodal, LTL',NULL,'Chassis (CH); Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Kfmt LLC','1116069','KTFW','Drayage, Ocean, Rail',NULL,'Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Kglx Transport LLC','498528','3571','Drayage, Ocean, Rail',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Kgn Transport LLC','1456462','KGNV','Drayage, Intermodal, LTL, Rail, Truckload',NULL,'Chassis (CH); Cargo Van (CV); Flat Bed Trailer (FT); Controlled Temperature Trailer (Reefer) (RT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Kgtl LLC','1416051','KLAW','Drayage, Intermodal, Rail',NULL,'Container (CN);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Kgz Transport Corp','950864','KGZP','Air Freight, Cartage, Drayage, Intermodal, LTL, Ocean, Parcel, Rail, Truckload',NULL,'Cargo Van (CV); Double-Drop Trailer (DD)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Kik, LLC','924363','KIKL','TL',NULL,'Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Kinda Express Inc','1448436','KEAY','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('King Logistics Tx Inc','1029093','KGXI','Intermodal',NULL,'Chassis (CH); Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('King Transportation Services LLC','763346','1098','Drayage, Intermodal',NULL,'Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Kingdom Hauling LLC','978066','KHLK','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Kings & Queens Transpo','1672767','KISH','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Kings Logistics Transport LLC','1175704','KLVN','Drayage',NULL,'Chassis (CH); Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Kingz Freight LLC','1217731','KFLJ','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Kinney Express Carriers LLC','1134015','KCAO','Drayage, Intermodal, LTL, Rail',NULL,'Chassis (CH); Cargo Van (CV); TRACTOR (G4); Trailer (not otherwise specified) (TL)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Kinos Trucking LLC','1266696','2373','LTL, Truckload',NULL,'TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Kirk Vaghner Transport LLC','1133285','VKTN','Drayage',NULL,'Chassis (CH); TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Kiss Trucking LLC','1502591','2327','Drayage, Rail',NULL,'Chassis (CH); Container (CN); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Kiswani National Inc','678756','KSWA','Drayage, Intermodal',NULL,'Chassis (CH); Container (CN); Cargo Van (CV); Double-Drop Trailer (DD); Flat Bed Trailer (FT); SMALL STRAIGHT (G2); LARGE STRAIGHT (G3); TRACTOR (G4); High Cube Van (HV); Load/unload Device on Equipment (LU); Open Top Van (OV); Fixed-Rack, Flat-bed Trailer (RA); Fixed-Rack, Double Drop Trailer (RD); Fixed-Rack, Single Drop Trailer (RS); Controlled Temperature Trailer (Reefer) (RT); Single-Drop Trailer (SD); Removeable Side Trailer (ST);  (SV); Trailer, Heater/Insulated/Vented (TA); Trailer, Bulk (TB); Trailer, Dry Freight (TF); Trailer, Tank (Gas) (TG); Trailer, Insulated (TI); Trailer, Tank (Chemicals) (TJ); Trailer, Tank (Food Grade-Liquid) (TK); Trailer (not otherwise specified) (TL); Trailer, Insulated/Ventilated (TM); Trailer, Pneumatic (TP); Trailer, Electric Heat (TQ); Truck, Van (TV); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Kito Trucking Services LLC','1062172','1089','Drayage',NULL,'TRACTOR (G4); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Kitt Logistics Inc','1427473','KLBB','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Kj Transports LLC','1557437','KJUA','Drayage, Intermodal, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Kjc Trucking','1054987','KJCI','Drayage, Rail',NULL,'Chassis (CH); TRACTOR (G4);  (SV); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Kjp Trucking LLC','1256750','KJAJ','Drayage',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Kkb Logistics Corp','1131085','KKBQ','Drayage',NULL,'TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Kl & A Transportation LLC','954726','KLAH','Drayage, Intermodal, LTL',NULL,'TRACTOR (G4); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Klf Transport Inc','974209','KLFP','Drayage',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Klik Way Logistics Inc','1027474','KWLQ','Drayage, TL',NULL,'(SV); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Knight Express Inc','1125702','KNXE','Drayage, Intermodal, LTL, Parcel, Rail',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Knight Sky Express LLC','000881','KSEL','LTL','01/30/2021',NULL,'Medford','OR','Carrier','100,000','01/30/2021',NULL,NULL,'1,000,000','01/30/2021'),
('Knl Luxury Inc','1001314','KNLY','Drayage, Intermodal, Rail',NULL,'Chassis (CH); SMALL STRAIGHT (G2); TRACTOR (G4); Single-Drop Trailer (SD)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Knott Logistics LLC','1166694','1067','Drayage, Intermodal',NULL,'Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Knr Logistic Inc','847967','KNRN','Drayage',NULL,'Truck, Van (TV)','Corona','CA','Carrier',NULL,NULL,NULL,NULL,NULL,NULL),
('Kns Logistics Group Inc','1158631','NONE','LTL',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Kntes LLC','1046734','KLEJ','Intermodal, LTL, Parcel, Rail',NULL,'LARGE STRAIGHT (G3); TRACTOR (G4);  (SV); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Koi Transport Inc','048642','PAYO','Air Freight, LTL',NULL,'Flat Bed Trailer (FT); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Kools Trucking LLC','046824','KOOS','Drayage, Intermodal, LTL, Rail, Truckload',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Kooner Carrier Inc','1202236','3721','Drayage, LTL, TL',NULL,'Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Korah For Christ LLC','1147945','KFAL','Drayage, Intermodal',NULL,'Chassis (CH); Container (CN); TRACTOR (G4); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Kp Gold Star Inc','513083','2576','Air Freight, Cartage, Drayage',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Kpm Logistics LLC','1268121','2421','TL',NULL,'Trailer, Dry Freight (TF); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Kri','1434412','KAXJ','Intermodal',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Krixu Global Concept Limited','1568940','2535','Air Freight, Cartage, Drayage, Intermodal, LTL, Ocean, Parcel, Rail, Truckload',NULL,'Cargo Van (CV); SMALL STRAIGHT (G2); LARGE STRAIGHT (G3); TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ksk Transport Inc.','067349','KSKT','LTL, Truckload',NULL,'Trailer, Heater/Insulated/Vented (TA); Trailer, Dry Freight (TF); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Kstallion Inc','1399252','KINW','LTL',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ktan Trucking LLC','1193329','KTNK','Drayage, Intermodal',NULL,'Chassis (CH); Container (CN); Cargo Van (CV);  (SV); Trailer, Dry Freight (TF); Trailer (not otherwise specified) (TL); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Kti, LLC','362051','KTIL','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Kular Trucking Inc','796100','1143','Drayage, Parcel',NULL,'Container (CN);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Kuroneko Transport, Inc','194488','KTMY','Air Freight, Drayage',NULL,'Chassis (CH); Trailer, Insulated/Ventilated (TM); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Kvc  Logistics  Corp','041080','KVCK','Drayage, Intermodal, Ocean, Rail',NULL,'Chassis (CH);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Kx Transportation LLC','1673062','KXTS','Drayage',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Kxk Transport LLC','1211132','KXKP','Drayage',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Kyns Transport Inc','1041128','KYNS','Drayage, Ocean',NULL,'Chassis (CH); Container (CN); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Kyrows Trucking Inc','1072131','KTBO','Truckload',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('L & D Transport Inc','644792','LDTQ','Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('L & D Transport, LLC','822268','LADW','Drayage',NULL,'Chassis (CH); Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('L & L Express Transport LLC','1282956','LLEI','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('L & X Transportation LLC','1337156','2456','Intermodal, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('L And R Carrier LLC','1297141','LRHE','Drayage, Intermodal, LTL',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('L M D Express LLC','1389702','LMDB','Drayage, Intermodal, Parcel',NULL,'Flat Bed Trailer (FT); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('L Power Enterprise','1071179','PWRW','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('L&A Trucking Of Brunswick LLC','033250','LATF','Drayage',NULL,'Chassis (CH); TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('L&L Hauling LLC','461570','LHBD','Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('L&M Solutions LLC','1230620','LMNI','Drayage, Intermodal',NULL,'Chassis (CH);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('L&W Trucking LLC','988196','LWBQ','Drayage, Intermodal, Ocean',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('L. J. Rogers, Jr. Trucking, Inc.','195477','RGLJ','Air Freight, Drayage, Intermodal, LTL, Ocean, Parcel, Rail, Truckload',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('L1 Freight Inc','1041631','LOLF','Drayage','06/23/2021',NULL,'Los Angeles','CA','Carrier','100,000','06/23/2021','1,000,000','06/23/2021','1,000,000','06/23/2021'),
('LOUP LOGISTICS COMPANY','161736','SMNN','Intermodal',NULL,NULL,'Omaha','NE','Carrier','0',NULL,'0',NULL,'0',NULL),
('La Cabal Transportation Inc','1011662','LCBA','Truckload',NULL,'Cargo Van (CV); Flat Bed Trailer (FT);  (SV); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Laa Trucking Inc.','1190386','2547','Drayage',NULL,'Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Labcarriers LLC','1281153','LLVC','Air Freight, Drayage, Intermodal, LTL',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Lake Logistics Inc','1648498','LLAY','LTL',NULL,'Cargo Van (CV);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Lamba Transport LLC','1710871','3650','Drayage, Intermodal, LTL, Parcel, Truckload',NULL,'TRACTOR (G4); Controlled Temperature Trailer (Reefer) (RT);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Lamontree Trucking, Inc','725805','LZMT','TL',NULL,'TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Lancaster Transportation, L.L.C.','304669','LNCS','Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Land & Sea Delivery Inc','989625','LSDN','Drayage, Intermodal, LTL, Ocean, Parcel, Rail',NULL,'Chassis (CH); Container (CN); Cargo Van (CV); Double-Drop Trailer (DD); Flat Bed Trailer (FT); SMALL STRAIGHT (G2); LARGE STRAIGHT (G3); TRACTOR (G4); Fixed-Rack, Flat-bed Trailer (RA); Fixed-Rack, Double Drop Trailer (RD); Controlled Temperature Trailer (Reefer) (RT); Single-Drop Trailer (SD); Trailer, Heater/Insulated/Vented (TA); Trailer, Bulk (TB); Trailer, Dry Freight (TF); Trailer, Insulated (TI); Trailer (not otherwise specified) (TL); Trailer, Insulated/Ventilated (TM); Trailer, Electric Heat (TQ); Truck, Van (TV); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Landjet Intermodal LLC','1638048','LAOD','Intermodal, LTL',NULL,'Chassis (CH); Container (CN); Load/unload Device on Equipment (LU)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Landmark Trucking, Inc.','365201','LMKR','Drayage, Intermodal, Rail',NULL,'Chassis (CH);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Landolt Logistics Company LLC','1141069','LDAC','Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Landstar Ranger, Inc.','166960','LAND','Drayage',NULL,'Flat Bed Trailer (FT);  (SV); Trailer, Refrigerated (TW)','Jacksonville','FL','Carrier','250,000','05/01/2021','5,000,000',NULL,'1,000,000',NULL),
('Landstar Ranger, Inc.','166960','LAND','Drayage',NULL,NULL,'Jacksonville','FL','Carrier',NULL,NULL,'5,000,000',NULL,'1,000,000',NULL),
('Lanham Transport LLC','1417210','LMAH','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Laporta Logistics','1476473','LAAH','Drayage, Intermodal',NULL,'Chassis (CH); Container (CN); Flat Bed Trailer (FT); TRACTOR (G4); Trailer, Dry Freight (TF)',NULL,NULL,NULL,'0',NULL,'0',NULL,'0',NULL),
('Larsen Intermodal Services, Inc.','259966','LISV','Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Lasham LLC','1181174','2579','LTL, Truckload',NULL,'Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Lasie Logistics','166074','LLOV','Air Freight, Drayage, Intermodal, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Lawrence Trucking LLC','1272945','LTYE','Drayage, Intermodal, LTL, Truckload',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Lawsons Family Trucking LLC','1600004','3934','LTL',NULL,'LARGE STRAIGHT (G3)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Lbv Trucking LLC','1348120','1184','Drayage, Intermodal',NULL,'Chassis (CH); Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Lcg Freight, Inc','1171040','LCGF','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Lcpl Osbrany Trucking LLC','1290620','LCPO','Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Leadway Transportation Inc','859668','LWYP','Intermodal, LTL',NULL,'(SV); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Leg Freight Solutions','1407172','LFSN','LTL',NULL,'LARGE STRAIGHT (G3)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Legacy Drayage Inc','1454103','LDRQ','Cartage, Drayage, Intermodal, Ocean, Rail',NULL,'Chassis (CH); TRACTOR (G4); Load/unload Device on Equipment (LU)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Legacy Express Trucking Inc','772181','LETI','Drayage',NULL,'Chassis (CH); Container (CN); Cargo Van (CV); Controlled Temperature Trailer (Reefer) (RT); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Legacy Transportation LLC','994270','2459','Truckload',NULL,'TRACTOR (G4);  (SV); Trailer, Tank (Gas) (TG); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Legendary Group Ma LLC','1053945','LGMD','Drayage, Intermodal',NULL,'Chassis (CH); Trailer, Dry Freight (TF); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Leighton Transportation Services, Inc.','744920','LHKL','Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Lengner & Sons Express','156852','LASO','Drayage',NULL,'Chassis (CH); Container (CN); TRACTOR (G4)','Oakland','CA','Carrier','250,000','03/01/2021',NULL,NULL,NULL,NULL),
('Lenox LLC','862783','LONL',NULL,NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Leon Transport LLC','1387298','1238','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,'0',NULL,'0',NULL,'0',NULL),
('Leones Transportation Inc','1346284','LTRY','Drayage, Rail',NULL,'Chassis (CH); Cargo Van (CV); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Leoness Express Inc.','931455','LNSS','Drayage','08/31/2020','Chassis (CH)','Long Beach','CA','Carrier','100,000','08/31/2021','1,000,000','08/31/2020','1,000,000','08/31/2020'),
('Leons Freight Services Inc','733521','LFSI','Air Freight, Drayage, Intermodal, LTL, Ocean, Rail, Truckload',NULL,'Chassis (CH); Flat Bed Trailer (FT); LARGE STRAIGHT (G3); TRACTOR (G4); Trailer, Bulk (TB); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Let Inbev Carriers Inc.','1031377','LIBC','Drayage, Intermodal, Ocean, Rail',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Lewis And Associates Investments LLC','1333024','LWAW','Air Freight, Drayage, Intermodal, LTL, Ocean, Parcel, Rail, Truckload',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Lewis Hauling & Logistics LLC','1175188','LHAN','Drayage, Intermodal, Ocean',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Lewislewis Transportation LLC','1116923','LWLP','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Lexacar LLC','1543380','NO','LTL',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Lexington Intermodal LLC','349593','LEXG','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Lia Transport Services LLC','1348398','LTSH','Drayage, Rail',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Liang Trucking LLC','1135533','LIGK','Drayage, Intermodal',NULL,'Chassis (CH); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Liberty Express','924762','LYEP','LTL','11/25/2020',NULL,'Watsonville','CA','Carrier','100,000','05/29/2021','1,000,000','11/25/2020','100,000','05/29/2021'),
('Life Express, LLC','629831','BFCT','Drayage','07/07/2020','Chassis (CH)','Kent','WA','Carrier','100,000','01/07/2021','1,000,000','07/07/2020','1,000,000','07/07/2020'),
('Lightning Transportation, Inc.','204764','LTNG','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Lightning Xpress Inc','921261','LXIR','Drayage, Intermodal, Ocean, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Lightscale Logistics LLC','1525093','2570','Drayage, Intermodal, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Lima Freight Solutions Inc','1059072','LMFP',NULL,NULL,'TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Limitless Carriers Corp','1057326','LCCA','Drayage',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Lincoln Transport Phoenix Inc','664657','LTPQ','Drayage',NULL,'Chassis (CH); Container (CN)','Phoenix','AZ','Carrier','200,000','12/31/2020',NULL,NULL,NULL,NULL),
('Lincoln Transportation Services, Inc.','458933','LINL','Drayage','12/31/2020',NULL,'Compton','CA','Carrier','250,000','09/27/2020','1,000,000','12/31/2020','1,000,000','12/31/2020'),
('Link Logistics Solutions Inc','086991','LLST','Air Freight, Cartage, Drayage, Intermodal, LTL, Truckload',NULL,'Chassis (CH); TRACTOR (G4); Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Lionhart Transportation LLC','765913','LHTL','Drayage','08/01/2025','Cargo Van (CV)',NULL,NULL,NULL,'250,000','08/01/2025',NULL,NULL,NULL,NULL),
('Lizard Logistics Inc','1025739','1020','Drayage','07/29/2020',NULL,'San Diego','CA','Carrier','100,000','07/29/2020','0',NULL,'1,000,000','07/29/2020'),
('Lj Galloway & Sons Trucking','1196939','GLVW','Drayage, Intermodal, Rail',NULL,'Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ll Brother Trucking Inc','1398089','CA','Air Freight, LTL',NULL,'Cargo Van (CV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ll&g Transportation LLC','1012918','LGBF','Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Llj Transport Inc','1313540','LTZH','Drayage, Intermodal',NULL,'TRACTOR (G4); Trailer, Tank (Chemicals) (TJ)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Lma Transport LLC','1128928','LTHD','Drayage, Intermodal',NULL,'Container (CN); TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Lme Transport LLC','624930','LMEO','Intermodal, LTL',NULL,'Flat Bed Trailer (FT); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Lmk Transportation','1002114','LMRB','Drayage, Ocean',NULL,'Container (CN); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Load One, LLC','456807','LONE','Truckload',NULL,'Cargo Van (CV); Double-Drop Trailer (DD); Flat Bed Trailer (FT); SMALL STRAIGHT (G2); LARGE STRAIGHT (G3); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Loadgistic Solutions LLC','0541594','1082','Drayage',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Local Haul Express LLC','732510','LHEP','Drayage, Intermodal, Truckload',NULL,'Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Logiflex','734742','LFXI','Drayage, Intermodal, LTL',NULL,'Chassis (CH); Controlled Temperature Trailer (Reefer) (RT);  (SV); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Logistic Pros LLC','114610','LPAF','Drayage','08/14/2020',NULL,'St. Charles','MO','Carrier','100,000','05/17/2021','1,000,000','08/14/2020','1,000,000','05/15/2021'),
('Logistics Specialist Inc','1202247','LGSP','LTL, Parcel',NULL,'High Cube Van (HV);  (SV); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Lone Star Transportation, LLC','210209','LSST','Drayage',NULL,'Double-Drop Trailer (DD); Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Long Beach Container Transport Solutions Inc','1110112','LBCA','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Long Distance Logistics LLC','1182339','2453','Cartage, Drayage, Intermodal, LTL, Ocean, Parcel, Rail',NULL,'Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Long Road Transportation LLC','113242','LRDP','Drayage','02/24/2021',NULL,'Kent','WA','Carrier','100,000','02/24/2021','1,000,000','02/24/2021','1,000,000','02/24/2021'),
('Longway Trucking LLC','1199746','LWYB','Drayage, Intermodal',NULL,'Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Longway Truckline Inc','133479','LOBY','Drayage, Intermodal, Ocean, Rail',NULL,'Chassis (CH); Container (CN); Cargo Van (CV); Flat Bed Trailer (FT); LARGE STRAIGHT (G3); TRACTOR (G4); Open Top Van (OV); Controlled Temperature Trailer (Reefer) (RT); Single-Drop Trailer (SD);  (SV); Trailer (not otherwise specified) (TL); Truck, Van (TV); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Lopes Trucking Service, Inc.','121768','LOPS','Drayage, Intermodal, LTL',NULL,'Chassis (CH); Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Lopez Logistics LLC','1072053','LORB','Cartage, Drayage, Intermodal, LTL, Ocean, Rail',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Lord''s Favor Trucking LLC','652023','LFVK','Drayage, Intermodal, Rail',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Lorna Bean Trucking LLC','872241','BLTC','Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Los Bros Transport LLC','1494848','2557','Drayage',NULL,'(SV); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Los Murillos Trucking LLC','1157688','LMTZ','Intermodal, LTL',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Los Ochoas Trucking, Inc.','469485','LOTM','LTL',NULL,'Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Lotus Terminals Ltd','1049948','LTNL','Cartage, Drayage, Intermodal, Truckload','09/15/2026','Chassis (CH); Cargo Van (CV); Flat Bed Trailer (FT)',NULL,NULL,NULL,'500,000','09/15/2026',NULL,NULL,NULL,NULL),
('Loup Logistics Co',NULL,'1239',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Love In Motion Express','1350904','LIJA','Drayage, Intermodal, Rail',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Love It & Lock It LLC','1464113','LVKO','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Low And Heavy LLC','1266151','2863','Truckload',NULL,'Flat Bed Trailer (FT); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Low Country Hauling LLC','1366974','LCHM','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,'0',NULL,'0',NULL,'0',NULL),
('Lsj Express LLC','1361164','LSQB','Drayage, Intermodal',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Lt Sprinkle Trucking LLC','976441','SLHT','Drayage, Intermodal',NULL,'Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Lucky Five Trucking LLC','1625752','LUFQ','Air Freight, Drayage, Intermodal, LTL, Rail',NULL,'Container (CN); Cargo Van (CV);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Luka Transportation Inc','835981','LUKA',NULL,NULL,'High Cube Van (HV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Lulu Express, LLC','798535','LULE','Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Luna Services Trucking','1602606','LUOE','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Luxor Logistics','036791','LUXO','LTL','08/25/2020',NULL,'Las Vegas','NV','Carrier','100,000','08/31/2021','1,000,000','08/25/2020','1,000,000','08/25/2020'),
('Lv Transport','871943','LTLL','Drayage',NULL,'Chassis (CH); Container (CN); Cargo Van (CV); Trailer (not otherwise specified) (TL); Truck, Van (TV)','Downey','CA','Carrier',NULL,NULL,NULL,NULL,NULL,NULL),
('Lve Express Inc','017031','LVES','Drayage','10/05/2020','Cargo Van (CV); TRACTOR (G4)','Carson','CA','Carrier','100,000','10/05/2020','1,000,000','10/05/2020','0','10/05/2020'),
('Lynx Logistics LLC','919518','LYNY','Intermodal',NULL,'Chassis (CH); TRACTOR (G4); Trailer (not otherwise specified) (TL)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Lyons Den Logistics LLC','1437363','LDAO','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Lyons Logistics LLC','1079150','LYLT','LTL',NULL,'Chassis (CH); Controlled Temperature Trailer (Reefer) (RT); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Lz Trans','783988','OCMD','Cartage, Drayage, Intermodal, LTL, Ocean, Parcel, Rail',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('M & C Transportation And Logistics LLC','1402446','MRBG','Drayage, Intermodal, LTL, Ocean, Parcel, Rail',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('M & S Cargo Express Corp','570004','MSCY','Drayage, Ocean',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('M 3 B Trucking LLC','1368106','2492','LTL, Truckload',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('M A G Transport Services L.L.C.','1017818','3510','LTL, Truckload',NULL,'Flat Bed Trailer (FT); SMALL STRAIGHT (G2); LARGE STRAIGHT (G3); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('M A Shaw Transport LLC','1267448','MSVW','Drayage, Intermodal, LTL',NULL,'(SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('M And J Transportation','092048','MAJY','LTL',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('M And R Trucking','1059475','MARR','Drayage, Ocean',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('M Fonsecas Enterprises Inc','1653117','MFRG','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('M G & M C Transportation','1066221','1180','Drayage, Intermodal',NULL,'Trailer (not otherwise specified) (TL)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('M Holmes Trucking, LLC','1303803','HTZB','Drayage, Intermodal',NULL,'Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('M J R Transport LLC','1058971','EVTE','Drayage',NULL,'Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('M M Logistics LLC','1366229','MMHA','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('M R M Trucking','1195729','2542','Drayage, Intermodal, LTL',NULL,'Container (CN)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('M Square Trucking LLC','1246416','MSTI','Air Freight, Cartage, Drayage, Intermodal, LTL, Ocean, Parcel, Rail, Truckload',NULL,'TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('M&A Logistics Of Nc LLC','726703','1156','Drayage, Intermodal, Rail',NULL,'Flat Bed Trailer (FT)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('M&D Logistics LLC','809902','2271','Drayage, TL',NULL,'Cargo Van (CV); TRACTOR (G4); High Cube Van (HV);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('M&H Express LLC','1309905','2468','Drayage, LTL',NULL,'Chassis (CH);  (SV); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('M&H Transportation LLC','1216060','2545','Truckload',NULL,'Cargo Van (CV);  (SV); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('M&T Lowery Trucking LLC','1216348','LWMT','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('M&Vb Trucking LLC','043946','MVTJ','Drayage, Intermodal',NULL,'Trailer, Dry Freight (TF)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('M&j International Services LLC','1465166','MJIP','Drayage, Intermodal, Ocean, Rail',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('M&k Worldwide Transports LLC','1372755','MKQD','Drayage, Intermodal',NULL,'TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('M&l Expressway Inc','454888','MLXS','Drayage, Ocean',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('M&l Trucking LLC','1184608','MLYE','Drayage, LTL',NULL,'Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('M.A.C.K. Logistics','328613','MACC','Drayage',NULL,'Container (CN); Cargo Van (CV); TRACTOR (G4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('MTZ Trucking Services Inc','851254','MTZG','Drayage, Intermodal, Rail',NULL,'Chassis (CH); SMALL STRAIGHT (G2); TRACTOR (G4); High Cube Van (HV); Load/unload Device on Equipment (LU); Fixed-Rack, Double Drop Trailer (RD); Fixed-Rack, Single Drop Trailer (RS); Single-Drop Trailer (SD); Removeable Side Trailer (ST);  (SV); Trailer, Tank (Food Grade-Liquid) (TK); Trailer (not otherwise specified) (TL); Truck, Van (TV); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ma & Co 58 Transport Inc','1441315','MCWD','Drayage',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ma&J Trucking, Inc.','863600','MAAH','Air Freight, Cartage, Drayage, Intermodal, LTL, Ocean, Parcel, Rail, Truckload',NULL,'Chassis (CH); TRACTOR (G4); Trailer, Refrigerated (TW)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Mac Tranz Inc','126789','MACD','Drayage, Rail, Truckload',NULL,'Container (CN); Flat Bed Trailer (FT); Single-Drop Trailer (SD)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Machuca Transportation','0507425','MACH','Drayage','01/22/2021',NULL,'Bakersfield','CA','Carrier','100,000','01/22/2021','0',NULL,'1,000,000','01/22/2021'),
('Mack Shipping LLC','1289086','MSNY','Drayage, Intermodal',NULL,'Chassis (CH)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Mack Trucking LLC','891493','MKKW','Drayage, Intermodal',NULL,'Chassis (CH); Container (CN); Double-Drop Trailer (DD); Flat Bed Trailer (FT); TRACTOR (G4); High Cube Van (HV); Open Top Van (OV); Fixed-Rack, Flat-bed Trailer (RA); Fixed-Rack, Double Drop Trailer (RD); Fixed-Rack, Single Drop Trailer (RS); Controlled Temperature Trailer (Reefer) (RT); Trailer, Dry Freight (TF); Trailer (not otherwise specified) (TL); Truck, Van (TV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Macs Hauling LLC','1194336','1060','Drayage',NULL,'Chassis (CH); TRACTOR (G4)',NULL,NULL,NULL,'0',NULL,'0',NULL,'0',NULL),
('Mad Shark Express LLC','964861','2449','LTL',NULL,'TRACTOR (G4);  (SV)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
